uxlfoundation/oneDPL

include/pstl/internal/algorithm_impl.h
include/pstl/internal/execution_defs.h
include/pstl/internal/execution_impl.h
include/pstl/internal/glue_algorithm_defs.h
include/pstl/internal/glue_algorithm_impl.h
include/pstl/internal/glue_execution_defs.h
include/pstl/internal/glue_memory_defs.h
include/pstl/internal/glue_memory_impl.h
include/pstl/internal/glue_numeric_defs.h
include/pstl/internal/glue_numeric_impl.h
include/pstl/internal/numeric_impl.h
include/pstl/internal/parallel_backend_tbb.h
include/pstl/internal/parallel_backend_utils.h
include/pstl/internal/parallel_impl.h
include/pstl/internal/unseq_backend_simd.h
include/pstl/internal/utils.h
include/pstl/iterators.h
test/test_iterators.cpp
test/test_mismatch.cpp
test/test_partition_copy.cpp
test/test_reduce.cpp
test/test_replace.cpp
test/test_transform_reduce.cpp
test/test_transform_scan.cpp
test/utils.h

The gist of this change is to rename all public template parameters, arguments, and locals in line with libstdc++ "uglification" protocols to avoid issues with preprocessor macros colliding with our internal identifier names.
Also, the using namespace declarations have been adjusted to avoid ADL name collision issues.
** Please note this is the first set of changes of this nature
This *must* be applied to *every* implementation file. I have held off applying these changes to the rest of include/pstl/internal because I want to avoid any major merge conflicts with backend updates.
I would like to amend this pull request with the rest of the changes, but I need to request that you hold off on *any* concurrent changes to files under include/pstl until this pull req is complete and accepted. …

Initial pass "hardening" against macro and ADL issues

---

CMakeLists.txt
ParallelSTLConfig.cmake.in

Updates in comparison with PR #5:
- Applied changes according to https://github.com/intel/parallelstl/pull/5#issuecomment-382045081.
- Re-worked logic of PARALLELSTL_USE_PARALLEL_POLICIES and PARALLELSTL_BACKEND interaction.
- Used more precise dependency on TBB.
- Added Apache 2.0 copyright notices.

Initiate CMake support in Parallel STL: updated pull-request #5.

---

.travis.yml
README.md

Travis CI can be used in order to perform minimal testing of incoming PRs to master branch.
The PR creates a configuration for Travis CI with the following coverage:
- Linux:
- gcc 4.8
- gcc 7
- clang (default is 5.0.0)
- OS X:
- xcode 7.3 with default clang
- xcode 9.3 with default clang
- xcode 8 with gcc 6
Core verification command is `make test compiler="$PSTL_COMPILER"`
Successful results will look like [this](https://travis-ci.org/AlexVeprev/parallelstl/builds/388700806).
Enabling of the CI can be done on https://travis-ci.org. Also master branch can be protected direct commits and commits without successful CI checks.

Travis CI configuration: covers gcc/clang on Linux/OSX

---

make/Makefile
make/Makefile.common
test/CMakeLists.txt

These changes fix CMake/Makefiles after #50

CMake/make: fix after renaming test/pstl_testsuite

---

test/CMakeLists.txt

This patch allows ctest properly handle test execution, particularly `Not run` status.

CMake: set env for tests using ENVIRONMENT property

---

CMakeLists.txt

Discussed with @capatober some options, let's continue further discussions here.
Current changes have the following effect:
- `-O0` is added for non-MSVC-like compilers in debug configuration.
- C++ standard is not passed to compiler by default.
- Build type is not set by default.
So we have the following cases:
- `CMAKE_BUILD_TYPE` and `CMAKE_CXX_STANDARD` are not set: no specific optimization/debug/standard options are passed to compiler.
- `CMAKE_CXX_STANDARD=11`: `-std=c++11` is passed to compiler, the same for other standards.
- `CMAKE_BUILD_TYPE=Debug`: `-O0 -g` are passed.
- `CMAKE_BUILD_TYPE=RelWithDebInfo`:  `-O2 -g` are passed.
- `CMAKE_BUILD_TYPE=Release`: `-O3` is passed

CMake: set O0 for Debug and disable default standard passing

---

include/oneapi/dpl/internal/function.h

Resolves compilation error when compiling header_inclusion_order_algorithm_1.pass with a non-SYCL compiler.
Signed-off-by: Timmie Smith <timmie.smith@intel.com>

Removing unused internal buffer type inclusion

---

jenkinsfiles/Windows_Check.groovy

Fix CI failure in windows check --- fatal error: 'support/pstl_test_config.h' file not found.
Since the file under test/parallel_api requires to include "support/pstl_test_config.h", the windows CI script need to add /test folder in /I option when compiling. 
If not, CI will fail when compiling with following error message:
dpcpp /W0 /nologo /D _UNICODE /D UNICODE /Zi /WX- /EHsc /Fetest.exe /Isrc/include /Isrc/test/parallel_api src\test\parallel_api\algorithm\alg.modifying.operations\alg.partitions\partition.pass.cpp 
08:24:32  src\test\parallel_api\algorithm\alg.modifying.operations\alg.partitions\partition.pass.cpp(17,10): fatal error: 'support/pstl_test_config.h' file not found
08:24:32  #include "support/pstl_test_config.h"
08:24:32           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
08:24:32  1 …

[CI]Fix CI failure in windows check

---

documentation/library_guide/pstl/macros.rst
include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/onedpl_config.h
test/support/utils_sycl.h

There is an issue that global policy objects presence is not needed for some cases, e.g. only oneDPL headers are included into DLL.
The patch introduces the `ONEDPL_USE_PREDEFINED_POLICIES` public macro that disables global policy objects (equal to 1 by default). Name can be changed.
The following are disabled when `ONEDPL_USE_PREDEFINED_POLICIES==0`:
* `dpcpp_default`
* `dpcpp_fpga`
* `make_device_policy()`
* `make_fpga_policy()`
**Testing**: tested when the macro is switched on (default) or is switched off (explicitly)

Added a macro to disable global policy objects

---

CMakeLists.txt

Without this fix `-O0` is passed only during compilation, but not linkage, it causes problems if default optimization level is not `-O0`

CMake: fix -O0 key adding

---

cmake/README.md
cmake/scripts/generate_config.cmake
cmake/templates/oneDPLConfig.cmake.in
cmake/templates/oneDPLConfigVersion.cmake.in

Documentation: https://github.com/oneapi-src/oneDPL/tree/dev/cmake-config-files/cmake#onedplconfig-files
Currently oneDPLConfig works with backends in a following way:
1. Try to find oneTBB and link it if found or set `ONEDPL_USE_TBB_BACKEND=0` otherwise.
1. Check if compiler supports `-fsycl` and set `ONEDPL_USE_DPCPP_BACKEND=0` if it is not.

CMake: add oneDPLConfig files support

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

A 'decay' type fixes for __SYCL_UNNAMED_LAMBDA__ mode

[dpc++] A 'decay' type fixes for __SYCL_UNNAMED_LAMBDA__ mode

---

test/CMakeLists.txt
test/rng_testsuite/conformance_tests/common_for_conformance_tests.hpp
test/rng_testsuite/conformance_tests/minstd_rand_rand0_test.pass.cpp
test/rng_testsuite/conformance_tests/ranlux_24_48_base_test.pass.cpp
test/rng_testsuite/conformance_tests/ranlux_24_48_test.pass.cpp
test/rng_testsuite/statistics_tests/normal_distribution_test.pass.cpp
test/rng_testsuite/statistics_tests/uniform_int_distribution_test.pass.cpp
test/rng_testsuite/statistics_tests/uniform_real_distribution_test.pass.cpp
test/rng_testsuite/template_tests/discard_block_std_template_test.pass.cpp
test/rng_testsuite/template_tests/linear_congruential_std_template_test.pass.cpp
test/rng_testsuite/template_tests/subtract_with_carry_std_template_test.pass.cpp

1) Template RNG test scope was reduced for regular testing procedures
2) Add tests skipping in case of non-SYCL compilers

[RNG][Tests] Add tests skipping for non-SYCL compilers + reduce test scope

---

include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
test/extensions_testsuite/dpl_namespace.pass.cpp

Changes:
1. Replace `auto` with actual type for `dpl_namespace.pass` to let it run with C++11.
2. Include a header file for `exclusive_scan_by_segment_impl.h` to prevent failures with `clang++`

Fixed some test failures

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/onedpl_config.h

`get_workgroup_info` and `get_sub_group_info` queries have been deprecated in favor of  “device-specific kernel” `get_info`
queries (`info::kernel_device_specific`).

Use kernel_device_specific queries instead of the deprecated ones

---

include/oneapi/dpl/internal/random_impl/discard_block_engine.h
include/oneapi/dpl/internal/random_impl/linear_congruential_engine.h
include/oneapi/dpl/internal/random_impl/normal_distribution.h
include/oneapi/dpl/internal/random_impl/subtract_with_carry_engine.h
include/oneapi/dpl/internal/random_impl/uniform_int_distribution.h
include/oneapi/dpl/internal/random_impl/uniform_real_distribution.h

Optimize skip-ahead procedure of LCG instantiations
Apply clang-format for RNG files

[RNG] Optimize LCG engine + apply clang-format for RNG files

---

documentation/library_guide/conf.py

`conf.py` for documentation contains configs that are specific for oneDAL and are not needed in oneDPL docs

[DOC] Removed oneDAL-related configs

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

Besides of improving scalability of the scan phase, it rebalances a workload in such a way that the scan phase performs more work freeing other phases by reducing size of a segment.

Optimize radix sort by making scan phase more scalable

---

CMakeLists.txt
cmake/README.md
include/oneapi/dpl/pstl/onedpl_config.h
include/oneapi/dpl/ranges
test/parallel_api/ranges/copy_ranges_factory_sycl.pass.cpp
test/parallel_api/ranges/copy_ranges_sycl.pass.cpp
test/parallel_api/ranges/exclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/find_end_ranges_sycl.pass.cpp
test/parallel_api/ranges/find_first_of_ranges_sycl.pass.cpp
test/parallel_api/ranges/find_ranges_sycl.pass.cpp
test/parallel_api/ranges/for_each_ranges_sycl.pass.cpp
test/parallel_api/ranges/inclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/is_sorted_ranges_sycl.pass.cpp
test/parallel_api/ranges/is_sorted_until_ranges_sycl.pass.cpp
test/parallel_api/ranges/merge_ranges_sycl.pass.cpp
test/parallel_api/ranges/minmax_ranges_sycl.pass.cpp
test/parallel_api/ranges/reduce_ranges_sycl.pass.cpp
test/parallel_api/ranges/search_n_ranges_sycl.pass.cpp
test/parallel_api/ranges/search_ranges_sycl.pass.cpp
test/parallel_api/ranges/sort_ranges_sycl.pass.cpp
test/parallel_api/ranges/stable_sort_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform2_ranges_factory_sycl.pass.cpp
test/parallel_api/ranges/transform2_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform_exclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform_inclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform_ranges_factory_sycl.pass.cpp
test/parallel_api/ranges/transform_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform_reduce_ranges_sycl.pass.cpp
test/parallel_api/ranges/zip_view.pass.cpp
test/support/pstl_test_config.h

[CMake]: 
* Remove unnecessary variables and macro from the main CMakeLists.txt: ONEDPL_USE_PARALLEL_POLICIES, ONEDPL_USE_RANGES_API
* Add check for the serial back-end
[Testing]
* Add check for C++ standard and standard library versions for the testing of ranges

Add check for standard library/C++ standard version for the ranges testing, fix the main CMake file

---

test/general/interface_check.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/binary.search/binary_search.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/lower.bound/lower_bound.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/upper.bound/upper_bound.pass.cpp
test/parallel_api/iterator/discard_iterator.pass.cpp
test/parallel_api/iterator/permutation_iterator.pass.cpp
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/support/pstl_test_config.h

The tests modified here fail to compile when dpcpp is used with `-DONEDPL_USE_DPCPP_BACKEND=0`
Signed-off-by: Timmie Smith <timmie.smith@intel.com>

Allow compilation with DPC++ compiler and non-DPCPP backend

---

test/support/pstl_test_config.h

Fix _ENABLE_RANGES_TESTING macro definition: add DPCPP_BE check to run range tests correctly with non-DPCPP-BE.

Add check of DPCPP-BE for ranges testing files

---

test/parallel_api/algorithm/alg.modifying.operations/alg.copy/copy_if.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/remove_copy.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/unique_copy_equal.pass.cpp

Fix some issues after the fixing of warnings: add macro guards for variables, which used/not used depending on BE-type to avoid wanings during compilation.

Add macro guards for variables, which used/not used depending on BE-type

---

test/general/dpl_namespace.pass.cpp

Add macro guards for dpcpp-specific code (header inclusion and the main code block) to dpl_namespace test.

Add macro guards for dpcpp-specific code to dpl_namespace test

---

test/parallel_api/iterator/discard_iterator.pass.cpp
test/parallel_api/iterator/permutation_iterator.pass.cpp

Add <vector> inclusion to discard/permutation iterator tests to avoid build errors at some platforms.

Add <vector> inclusion to discard/permutation iterator tests

---

test/general/interface_check.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/binary.search/binary_search.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/lower.bound/lower_bound.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/upper.bound/upper_bound.pass.cpp
test/parallel_api/iterator/discard_iterator.pass.cpp
test/parallel_api/iterator/permutation_iterator.pass.cpp
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp

For our nightly test, it will add 'oneDPL/test/support' file path to 'CPATH'. So I request to remove this including path for some test codes.

Remove include 'support' folder relative path for some test codes

---

test/CMakeLists.txt

Tests from xpu_api folder are not supported for non-dpcpp backends. This patch provides a short-term solution to skip these tests. Later more scalable/universal solution may be proposed if needed.

CMake: skip xpu_api test for non-dpcpp backends

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

Remove unnecessary barriers and add "constexpr" attribute to iteration number in scan brick In order to improve performance and to avoid disabling some FE-compiler optimization.

Remove unnecessary barriers and add constexpr attribute in scan brick

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

Seems it was added by mistake during debugging type names.

Remove extra class from parallel_backend_sycl.h

---

CMakeLists.txt
cmake/README.md
include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/reduce_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
test/general/lambda_naming.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/shift_left_right.pass.cpp
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/parallel_api/ranges/merge_ranges_sycl.pass.cpp

1. It was found that names of oneDPL kernel's are too long. The patch is reduced names
2. Make policy name unique for `shift_left_right`, `set_union` patterns, `*_by_segment` algorithms

Refactor generated names of kernels

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

It continues fixing that started at https://github.com/oneapi-src/oneDPL/pull/107.
Th thing is code worked incorrect if work group size = 10, n = 9, for example. Now I've changed the logic based on the thing that we work with current local id, not with others id.

Fix for reduction stage of scan pattern

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

```if (__val_idx < __inout_buf_size)``` condition may have caused divergence of work items within the same group and subgroup. When the divergence occurs with use of the collective algorithms (e.g. ```sycl::ONEAPI::reduce```), then behavior is undefined. The patch gets rid of the divergence as well as removes unused methods.

Fix reorder phase in radix sort

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
test/general/lambda_naming.pass.cpp

This is the fix for the #113 PR.
Regression test:
```
int main() {
sycl::queue q;
sycl::usm_allocator<int, sycl::usm::alloc::shared> alloc(q);
int* storage = alloc.allocate(4);
std::vector<int> hv = {1, 2, 3, 4}; // host vector
auto policy = oneapi::dpl::execution::make_device_policy(q);
std::copy(policy, hv.begin(), hv.end(), storage);
std::copy(policy, storage, storage + 4, hv.begin());
return 0;
}
```

Fix for kernel names check

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

Fix an issue with segmentation fault in the global scan functor, which causes memory corruption and double memory free operation (CPU, Debug)

Fix segmentation fault in the global scan functor

---

CMakeLists.txt
test/CMakeLists.txt

oneDPL test harness may initialize a C++ iterator using an iterator with different type. That may break code when using Intel(R) C++ Compiler Classic with -O3 flag on Linux. This optimization is turned off on Windows by default.

Turn off strict aliasing optimization if used

---

test/parallel_api/numeric/numeric.ops/scan.pass.cpp

Testing of `scan.pass` takes too much time on CPU devices when there are a few number of cores (e.g. due to limits in docker containers). This reduces testing time by ~30% when the test is built in debug mode. 
Reduction is not necessary with release mode, so let's keep it as is. 
Testing in debug mode with large number of elements may detect some specific issues, so let's test such scenario, but reduce the number to have reasonable execution time.

Reduce number of elements to scan due to taking too much time when testing

---

jenkinsfiles/UB18_Check.groovy

It is observed that "setting env" step may fail for UB18 test due to mount folder issue from infrastructure side. 
This PR can improve stability of UB18 CI check by adding retry/try catch method.
The PR has been verified with link below:
http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/OneDPL_CI%2FUB1804_Check/detail/UB1804_Check/355/pipeline
Signed-off-by: Xiaodong, Li <xiaodong.li@intel.com>

[Pre-CI] Will add retry/try catch protection for UB18 test

---

test/parallel_api/experimental/asynch.pass.cpp

moving tests for async API from xpu-api test folder to experimental algorithm folder. Extending guards to fully skip test on host.

move async test

---

documentation/library_guide/before_you_begin.rst
documentation/library_guide/extension_api.rst
documentation/library_guide/intel_variables.txt
documentation/library_guide/pstl/dpcpp_policies_usage.rst
documentation/library_guide/pstl/macros.rst
documentation/library_guide/pstl_main.rst
documentation/library_guide/random.rst
documentation/library_guide/tested_standard_cpp_api.rst

modified:   before_you_begin.rst
modified:   extension_api.rst
new file:   intel_variables.txt
modified:   pstl/dpcpp_policies_usage.rst
modified:   pstl/macros.rst
modified:   pstl_main.rst
modified:   random.rst
modified:   tested_standard_cpp_api.rst
modified:   variables.txt

Added substitution elements for building docs

---

include/oneapi/dpl/pstl/glue_algorithm_ranges_defs.h
include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
test/parallel_api/ranges/remove_if_ranges_sycl.pass.cpp
test/parallel_api/ranges/remove_ranges_sycl.pass.cpp

- Added range based API for remove and remove_if algorithms. 
- Added simple test for both algorithms. 
- Removed unused `__get_mask` function. 
- Moved `__create_mask` to `unseq_backend_sycl.h` for reusing it with ranges.

Range based API for remove and remove_if algorithms

---

test/parallel_api/ranges/copy_ranges_factory_sycl.pass.cpp
test/parallel_api/ranges/copy_ranges_sycl.pass.cpp
test/parallel_api/ranges/find_end_ranges_sycl.pass.cpp
test/parallel_api/ranges/find_first_of_ranges_sycl.pass.cpp
test/parallel_api/ranges/for_each_ranges_sycl.pass.cpp
test/parallel_api/ranges/search_n_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform2_ranges_factory_sycl.pass.cpp
test/parallel_api/ranges/transform_exclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform_ranges_factory_sycl.pass.cpp

This fixes the following issue (arises during build stage):
```c++
onedpl/test/parallel_api/ranges/search_n_ranges_sycl.pass.cpp:16:
onedpl/include/oneapi/dpl/execution:65:
onedpl/include/oneapi/dpl/pstl/glue_execution_defs.h:57:
onedpl/include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h:21:
onedpl/include/oneapi/dpl/pstl/parallel_backend.h:22:
onedpl/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h:666:17: error: definition with same mangled name '_ZTSN6oneapi3dpl20__par_backend_hetero25__parallel_find_or_kernelIJNS0_10__internal8__ranges13equal_wrapperINS0_9execution5__dpl17DefaultKernelNameEEEEEE' as another definition
[=](sycl::nd_item</*dim=*/1> __item_id) {
^
onedpl/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h:666:17: note: previous definition is here …
```

Make kernel names unique in some tests

---

documentation/CHANGES.rst

* Added 2021.2.0 release changes
* Fixed typo
* Added footnote for Radix sort
* Fixed link to oneDPL specification
* Added missed changes noticed by Dmitriy
* Added missed space
(cherry picked from commit 1dd8af11c56ae0c26e2532481d1413356a060cbf)

Update CHANGES file with 2021.2 release changes (#173)

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

Count phase requires block size which is a power of 2. We may get some other size, e.g. 85 when compiling for CPU that will result in wrong data after reduction at step 2.2 of the count phase.
Additionally added missing `forward` instructions and removed extra compilation of a kernel for scan phase.

Fix radix sort: guarantee that block size is a power of 2

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

Defer initial value assignment to allow exclusive_scan with overlapped input/output storage. When buffer-based storage is used the initial value currently overwrites the first value needed to compute the scan. Moving the write of the initial value after the scan is computed resolves the issue.
Signed-off-by: Timmie Smith <timmie.smith@intel.com>

Fix for exclusive scan with overlapped input/output

---

test/parallel_api/algorithm/alg.sorting/partial_sort.pass.cpp
test/parallel_api/algorithm/alg.sorting/sort.pass.cpp
test/support/test_config.h

partial_sort: 
- Added a case with no predicate
sort/stable_sort: 
- Enabled the case with no predicate on the host side
- Removed `_PSTL_TEST_RADIX_SORT` and `_PSTL_TEST_MERGE_SORT` and added alternative macros. Improved diagnostics.

Improve testing coverage of sorting algorithms

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

* Use broadcast instead of reduce in reorder phase.

Radix sort: improve performance by not calling reduce group algorithm

---

test/xpu_api/numerics/numeric.ops/numeric.ops.gcd/xpu_gcd.pass.cpp
test/xpu_api/numerics/numeric.ops/numeric.ops.lcm/xpu_lcm.pass.cpp

1. Remove unused header file
2. Reuse sycl::queue deviceQueue
Signed-off-by: Haonan Yang <haonan.yang@intel.com>

Refactor gcd and lcm tests

---

test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp

The `test_with_usm` function of the algorithm extension tests were not deallocating memory allocated in the function.  Correcting this and removing changing `cl::sycl` to `sycl` in the tests to match SYCL 2020 support.

Adding memory deallocation calls to algorithm extension USM tests.

---

documentation/release_notes.rst

* Update release_notes.rst
* Fix format
* Fix format
* Fix format for utility ranges
* Add note about transform_iterator and fix format
* Add note about error propagation fix
Co-authored-by: Pablo Reble <pablo@reble.org>
* Add review feedback
* Fix exclusive_scan comment.
* Define debug mode through options
* Fix typos
* Address review comments
Remove 'RNG functionality' from respective line, shorten fix execution note, fix format
* Add subheader in Known Issues section
* Add review feedback
Co-authored-by: Pablo Reble <pablo@reble.org>
Co-authored-by: Timmie Smith <timmie.smith@intel.com>
(cherry picked from commit 5a3fdc8fbe6ca8d30a80f92944dd8a5566a2ffd2)

Release Notes update for 2021.3 (#200)

---

test/parallel_api/numeric/numeric.ops/scan.pass.cpp
test/parallel_api/numeric/numeric.ops/transform_scan.pass.cpp
test/support/test_config.h
test/support/utils.h

1. Fixed issues where scan algorithms with host policies worked incorrectly using gcc10
2. Enable testing matrices for dpcpp policies. `Matrix` is default constructible now

Fixed issues with scan algorithms using GCC10 (host policies) and dpcpp policies

---

jenkinsfiles/Windows_Check.groovy

http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/OneDPL_CI%2FWindows_Check/detail/Windows_Check/949/pipeline/

Jenkins CI: drop CMAKE_TOOLCHAIN_FILE option for Visual Studio

---

cmake/windows-dpcpp-toolchain.cmake

Sometimes we may need to use different compiler binary with this toolchain.

CMake: don't overwrite compiler in toolchain

---

test/parallel_api/iterator/iterators.pass.cpp

1) Added test for zip iterator's constructor with variadic arguments.
2) Erased duplicate test for counting_iterator's operator[].

Code coverage improvement for zip iterator

---

include/oneapi/dpl/pstl/onedpl_config.h
include/oneapi/dpl/pstl/tuple_impl.h
include/oneapi/dpl/pstl/utils.h
test/parallel_api/iterator/zip_iterator.pass.cpp

To make structured binding work properly tuple-like type require:
- ``std::tuple_size<T>`` to be well-formed, where ``T`` is the tuple-like type
- ``std::tuple_element<i, T>`` to be well-formed, where ``T`` is the tuple-like type and ``i`` is a non-type template parameter representing the index
- Either ``t.get<i>`` or ``get<i>(t)`` to be well-formed, where ``t`` is tuple-like object  and ``i`` is a non-type template parameter representing the index

Add structured binding support for zip_iterator::value_type

---

.github/workflows/ci.yml
jenkinsfiles/UB18_Check.groovy

We want to move some CPU configurations to GitHub Actions because Jenkins CI is often unstable. This will allow us to test at least some of the configurations in case of issues with machines from Jenkins CI runners pool.

CI: enable testing via GitHub Actions

---

include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
test/support/utils_sycl.h

[dpc++][ranges] + usage of make_device_policy<__new_name> for __pattern_walk_n.
It fixes "the same mangled name issue" for same range-based algorithms

[dpc++][ranges] + usage of make_device_policy<__new_name> for __pattern_walk_n

---

make/Makefile.common
make/clang.inc
make/dpcpp.inc

Support  "-fopenmp-simd" in the "make" files for dpcpp, clang, icpx

Support  "-fopenmp-simd" in the "make" files for dpcpp, clang, icpx

---

documentation/library_guide/pstl/dpcpp_policies_usage.rst

It was found that we missed in the Library Guide that users can pass SYCL deduction tags and `sycl::no_init`.

[Doc] Added description for begin, end missing functionality

---

documentation/release_notes.rst

Release Notes update for 2021.4

---

test/CMakeLists.txt

(with separated timeout values for each configuration)
Signed-off-by: Anastasia Timonova <anastasia.timonova@intel.com>

[rng_tests]: Setup special timeout value for RNG template tests

---

CMakeLists.txt
cmake/scripts/generate_config.cmake
cmake/templates/oneDPLConfig.cmake.in

Signed-off-by: Veprev, Alexey <alexey.veprev@intel.com>
Completely inspired by @masterleinad (https://github.com/oneapi-src/oneDPL/pull/237), but with a bit different approach.
Installation results (`<prefix>` is just placeholder here):
```
> cmake -P cmake_install.cmake
-- Install configuration: ""
-- oneDPL 2021.4.0 configuration files were created in '<prefix>/lib/cmake/oneDPL'
-- Installing: <prefix>/include
-- Installing: <prefix>/include/oneapi
-- Installing: <prefix>/include/oneapi/dpl
-- Installing: <prefix>/include/oneapi/dpl/algorithm
-- Installing: <prefix>/include/oneapi/dpl/array
-- Installing: <prefix>/include/oneapi/dpl/async
-- Installing: <prefix>/include/oneapi/dpl/cmath
-- Installing: <prefix>/include/oneapi/dpl/complex
-- Installing: <prefix>/include/oneapi/dpl/cstddef …
```

CMake: add install instructions

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

- made shift aligned with SIMD size on GPU devices
- removed unnecessary atomic load
- rewrote loop for better code generation (seems it helps graphics compiler to vectorize code better)

Improve performance of find_or pattern

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
include/oneapi/dpl/pstl/onedpl_config.h
test/general/buffer_wrapper.pass.cpp
test/support/utils_sycl.h

This fixes definition of SYCL_2020_NOINIT_MACRO, which has been introduced in  #286.
We must use ```3```, because ```__LIBSYCL_MINOR_VERSION``` was ```2``` before adding of ```no_init```. 
- ```noinit``` has been deprecated and ```no_init``` has been introduced in https://github.com/intel/llvm/commit/ad46b641972b90da748768678daa7fae4dcc1b78 (May 14th).
- ```__LIBSYCL_MINOR_VERSION``` has been set to ```2``` in https://github.com/intel/llvm/commit/6a49170027fba61cea649ffdd299ed095b5e3d75 (April 13th)
- ```__LIBSYCL_MINOR_VERSION``` has been set to ```3``` in https://github.com/intel/llvm/commit/962909fe9e78bd597594d67c5c5be7eacf8fb10a (July 8th)
PS: ```__LIBSYCL_MINOR_VERSION``` is set as ```SYCL_MINOR_VERSION``` during installation of the compiler: …

Fix definition of SYCL_2020_NOINIT_MACRO

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

"Re-opened" https://github.com/oneapi-src/oneDPL/pull/263
(was closed by a mistake)

[dpc++][sycl] + usage of sycl::get_kernel_bundle, sycl::use_kernel_bundle (known as PR263)

---

.github/workflows/ci.yml

CI: use conda instead of apt to install additional packages on Linux

---

documentation/library_guide/tested_standard_cpp_api.rst
include/oneapi/dpl/algorithm
test/xpu_api/algorithms/alg.nonmodifying/alg.all_of/xpu_all_of.pass.cpp
test/xpu_api/algorithms/alg.nonmodifying/alg.any_of/xpu_any_of.pass.cpp
test/xpu_api/algorithms/alg.nonmodifying/alg.none_of/xpu_none_of.pass.cpp

These 3 algorithm are introduced in C++11, so we can inject them to oneapi::dpl namespace directly.
They are available in gcc 7.5.0

[oneDPL] Add serial all_of, any_of and none_of to oneapi::dpl

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

Changes:
- Make kernel names shorter for name generator case. Add aliases for readability.
- Add comments for optional kernel name and for kernel name composer
- Remove `DefaultKernelNameFPGA`

Make kernel names shorter for name generator case

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

Decided to return it back because we have two global policy objects and their default names should be independent.
The fix for `_HasDefaultName` still required.

Return fpga default kernel name back

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

#315 added a step of reduction on global memory. Reduction has been performing two steps since applying of the patch:
1. Reduction on global memory. Number of elements to reduce is set by __iters_per_work_item 
2. Reduction on local memory. Number of elements to reduce is set by __work_group_size 
This patch fixes hanging when both __iters_per_work_item and __work_group_size are 1.

Fix hanging of reduction pattern

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

The instantiation of scan pattern may differ just with one Callable type and that would give two different instantiations of the function. On the other hand, the name for the kernel might be the same because it doesn't take into account all the passed types. Thus, compiler tries to generate two different kernels with the same name.
That patch makes kernel name take into account all the passed types.

Fix kernel redefinition in scan

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
test/support/utils_sycl.h

This fixes issue: 
```bash
warning: 'INTEL' is deprecated: use 'ext::intel' instead
```
Since the namespace was deprecated after the latest release, that change cannot be detected by __LIBSYCL_VERSION macro for now. 50400 is set tentatively.
50300 is effective since: https://github.com/intel/llvm/commit/962909fe9e78bd597594d67c5c5be7eacf8fb10a (July 8)
deprecation was done in https://github.com/intel/llvm/commit/d703f578fcf7e8fb4716846bdd115add128a345b (July 17)
Waiting for update of https://github.com/intel/llvm/blob/sycl/sycl/CMakeLists.txt#L16
Upd.
Version macro is not going to be updated in the compiler soon, that is why let's use 50300. That will remove deprecation warnings, though it will make oneDPL code invalid for the compiler snapshots between …

Fix deprecation warnings for extensions namespace

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

Undo usage of sycl::group_barrier by following reasons:
1) sycl::group_barrier() implementation is not ready in the SYCL library.
2) sycl::group_barrier and sycl::item::group_barrier are not quite equivalent. In the future we have to revise SYCL parallel patterns which use a group_barrier.

[dpc++][sycl] undo usage of SYCL2020 feature sycl::group_barrier

---

make/Makefile.common

+ usage of SYCL_DEVICE_FILTER instead of deprecated SYCL_DEVICE_TYPE

+ usage of SYCL_DEVICE_FILTER

---

README.md

Adding oneAPI logo to README to make it consistent with other oneAPI open source projects.

Add oneAPI logo to README

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h

[oneDPL][sycl] + more robust implementation of __max_sub_group_size and removed usage of the deprecated sycl::vector_class.
Now the function just return 0 instead of throwing "out_of_bound" exception.

[oneDPL][sycl] removed usage of the deprecated sycl::vector_class

---

before_you_begin.html
extension_api.html
genindex.html
index.html
notices_disclaimers.html
pstl/dpcpp_policies_usage.html
pstl/macros.html
pstl_main.html
random.html
search.html
tested_standard_cpp_api.html

This is the first step in setting up doc usage data collection from github pages
see output: https://outoftardis.github.io/oneDPL/
I'll work with @dcbenito on updating the configs to generate this automatically but we need this change in order to make a request to the WAP team and get an id for the analytics scripts.

Add a link to Intel cookies

---

include/oneapi/dpl/execution
include/oneapi/dpl/internal/async_impl/async_utils.h
include/oneapi/dpl/internal/function.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/hetero/utils_hetero.h
include/oneapi/dpl/pstl/iterator_defs.h
include/oneapi/dpl/pstl/ranges_defs.h
include/oneapi/dpl/pstl/utils_ranges.h
include/oneapi/dpl/ranges
test/general/header_order_ranges_0.pass.cpp
test/general/header_order_ranges_1.pass.cpp

A fix for header inclusion order (`<ranges> / <execution>`)
Also, a couple of tests to cover that situation was added.

[oneDPL][ranges][sycl] A fix for header inclusion order in case of ranges

---

.github/scripts/allowed_words.txt
.github/scripts/codespell.sh

Some repetitive errors moved to a separate file. Specific errors remain in the IGNORE_COMMAND variable.

CI: improve codespell check

---

documentation/release_notes.rst

Added the description of ranges::reverse algorithm limitation, firstly discovered in oneDPL 2021.4 release. 

Update for Release Notes 2021.5

---

test/parallel_api/numeric/numeric.ops/transform_reduce.pass.cpp

Signed-off-by: Sobolev, Dmitriy <dmitriy.sobolev@intel.com>

Avoid testing non device copyable types with DPC++ backend

---

include/oneapi/dpl/pstl/utils.h
test/parallel_api/algorithm/alg.merge/inplace_merge.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.partitions/partition.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.partitions/stable_partition.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.reverse/reverse.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.reverse/reverse_copy.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/rotate.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/shift_left_right.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/nth_element.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.heap.operations/is_heap.pass.cpp
test/parallel_api/algorithm/alg.sorting/partial_sort.pass.cpp
test/parallel_api/algorithm/alg.sorting/sort.pass.cpp
test/support/iterator_utils.h

Please find the description of the purpose of the patch here https://github.com/oneapi-src/oneDPL/issues/104

Replacing iterator tag checks with is_base_of semantics

---

documentation/library_guide/api_for_dpcpp_kernels/tested_standard_cpp_api.rst

Updated tested_standard_cpp_api with VS22 support.

Adding Visual Studio 2022 Support

---

include/oneapi/dpl/pstl/onedpl_config.h
include/oneapi/dpl/pstl/parallel_backend.h

The bug root cause: enabling TBB backend (via `ONEDPL_USE_TBB_BACKEND`) and disabling OpenMP backend (both explicitly ) in compiler command line causes disabling parallel policies because the decision about the policies is made by the latest macro in the code (in our case one that enables OpenMP backend).
If the macro that enables OpenMP backend (`ONEDPL_USE_OPENMP_BACKEND`) is defined then the implementation re-establishes the value of the macro `_ONEDPL_USE_PAR_POLICIES` to the value of `ONEDPL_USE_OPENMP_BACKEND` despite if TBB backend was already enabled or not.
Thus, the following macros in command line: 
```cpp
-DONEDPL_USE_TBB_BACKEND=1 -DONEDPL_USE_OPENMP_BACKEND=0
```
causes parallel policies to be disabled.
Keeping in mind that the possible states of `ONEDPL_USE_TBB_BACKEND` and …

Choosing parallel backend fix

---

include/oneapi/dpl/pstl/onedpl_config.h
include/oneapi/dpl/pstl/parallel_backend.h

The bug root cause: enabling TBB backend (via ONEDPL_USE_TBB_BACKEND) and disabling OpenMP backend (both explicitly ) in compiler command line causes disabling parallel policies because the decision about the policies is made by the latest macro in the code (in our case one that enables OpenMP backend).
If the macro that enables OpenMP backend (ONEDPL_USE_OPENMP_BACKEND) is defined then the implementation re-establishes the value of the macro _ONEDPL_USE_PAR_POLICIES to the value of ONEDPL_USE_OPENMP_BACKEND despite if TBB backend was already enabled or not.
Thus, the following macros in command line: -DONEDPL_USE_TBB_BACKEND=1 -DONEDPL_USE_OPENMP_BACKEND=0
causes parallel policies to be disabled.
The idea of fix is to define TBB and OpenMP backend related internal macros separately and …

Choosing parallel backend fix (#414)

---

test/parallel_api/numeric/numeric.ops/transform_reduce.pass.cpp

This change is inspired by https://github.com/oneapi-src/oneDPL/pull/409#discussion_r746035100
Signed-off-by: Sobolev, Dmitriy <dmitriy.sobolev@intel.com>

Make MyClass trivially copyable to test with DPC++ policies

---

CMakeLists.txt

DPC++ compiler defines `_OPENMP` macro when `-fopenmp-simd` (not `-fopenmp`) is specified. This leads to linkage errors due to incorrect setting of the macros values that control the selection of the backend.

CMake: set ONEDPL_USE_OPENMP_BACKEND=0 explicitly for serial backend

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

Compilation of the kernel prevents out of resources issue, which may occur due to usage of collective algorithms even if local memory is not explicitly requested

Fix CL_OUT_OF_RESOURCES occurring in local scan stage of radix sort

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
test/parallel_api/iterator/iterators.pass.cpp

> Header dependency changes
Some C++ Standard Library headers have been changed to no longer include other headers that they do need to depend on. As such, C++ programs that used standard library components without including the right headers will no longer compile.
The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 11: 
"limits" (for std::numeric_limits) (ect.)
See more [here](https://gcc.gnu.org/gcc-11/porting_to.html) .
Due to these changes in GCC 11, functional test iterators.pass are failing now on Fedora34.

Add inclusion of some files due to header dependency changes in GCC 11

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
test/support/utils_sycl.h

[dpc++] A hot fix for OneDPL, usage of accessor::get_pointer; + take into account "offset", according to SYCL 2020 spec.
Eventually,  just a couple of places in OneDPL code had to be corrected. In the rest places an accessor doesn't have offset.

[dpc++] A hot fix for OneDPL, usage of accessor::get_pointer -  take into account "offset"

---

include/oneapi/dpl/internal/reduce_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

Add support for USM device memory for reduce_by_segment algorithm:
- stop working with input data on the host because we can't rely that the it is always accessible (can be allocated on the device).

Add support for USM device memory for reduce_by_segment algorithm

---

include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h

Fixed crash in exclusive_scan_by_segment algorithm for the case when we use algo with USM device memory and count of items equal to 1. Now in this case we don't copy data on a host from USM device memory in exclusive_scan_by_segment_impl function and call hetero algo implementation.

Fix error in exclusive_scan_by_segment algorithm for USM device memory

---

.github/workflows/ci.yml

Current version of OpenCL loader requires a new registry key and setting PATH variable to folder with CPU driver.
Also, CPU driver requires specifying a special TBB_DLL_PATH variable with path to folder with TBB binaries.

CI: add some stuff for OpenCL loader on Windows

---

test/support/iterator_utils.h

The trait causes the following issue with VS 2019 and c++20:
```c++
In file included from test\parallel_api\algorithm\alg.nonmodifying\for_each.pass.cpp:18:
In file included from include\oneapi/dpl/execution:23:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\execution:15:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\algorithm:11:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xmemory:16:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xutility(436,85): error: 'element_type' is a protected member of …
```

Remove extra element_type trait from ForwardIterator

---

test/support/sycl_alloc_utils.h

This fixes compilation issues with Intel oneAPI DPC++/C++ Compiler 2021.1.2
The compiler started supporting queue::copy for USM since this patch: https://github.com/intel/llvm/pull/3897 (Jun 28, 2021).
Additionally, line endings have been changed from CRLF to LF that is aligned with different files when the repository is cloned in Linux-like systems.

Restore backward compatibility with the older compiler (tests only)

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

This fixes compilation issues with Intel oneAPI DPC++/C++ Compiler 2021.1.2

Restore backward compatibility with the older compiler (library only)

---

.github/workflows/ci.yml
include/oneapi/dpl/pstl/glue_algorithm_impl.h

Sometimes it is useful to have diff of clang-format as artifact to apply it through `git apply` (requested by @rarutyun)

CI: save artifacts for clang-format

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
test/support/utils_sycl.h

global_buffer became deprecated since https://github.com/intel/llvm/commit/987427af6a521182ddc1b0e40d84078787af5a2f patch, 
This is deprecated in SYCL 2020 (https://www.khronos.org/registry/SYCL/specs/sycl-2020/pdf/sycl-2020.pdf (rev 4), page 158). as well as sycl::access::target namespace.
There are related deprecations for host_buffer, local, but I suggest fixing them in separate patches in order not to complicate this one.

Fix warning: 'global_buffer' is deprecated

---

documentation/CHANGES.rst
documentation/release_notes.rst

Added missed verbatim symbols to keep consistent format for algorithms mentioning. 

Fix format in release notes and changes files

---

.github/workflows/ci.yml
CMakeLists.txt
cmake/README.md
jenkinsfiles/RHEL_Check.groovy
jenkinsfiles/UB18_Check.groovy
jenkinsfiles/UB20_Check.groovy
jenkinsfiles/Windows_Check.groovy
test/CMakeLists.txt

Signed-off-by: Veprev, Alexey <alexey.veprev@intel.com>
This PR is inspired by #463.
It implements the following:
1. Disables tests configuration if oneDPL is subproject;
2. Removes test targets from `all` target: now tests are not built by default with just `make`, you need to explicitly run `make build-onedpl-tests`
Additional change: targets for tests in subfolders are renamed: `build-onedpl-<subfolder>-tests`
More details are added into cmake/README.md
CI correction were applied, you can see examples there.
@rarutyun @akukanov please take a look.
@alexey-katranov I'd consider the similar approach for oneTBB, but with additional user option TBB_TEST that is already in place.
For oneDPL I don't think the explicit option is useful.

CMake: disable tests by default

---

include/oneapi/dpl/functional
include/oneapi/dpl/type_traits

Additionally, lines in `functional` and `type_traits` have been reordered for better readability.

Do not use is_literal_type with c++20

---

include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
test/parallel_api/ranges/reduce_by_key_ranges_sycl.pass.cpp
test/support/utils_sycl.h

This fixes an issue with uniqueness of kernel names in Range-based APIs.  
Some Range-bases APIs used to rely on a custom way to generate unique kernel names (look at `__new_kernel_name` function).
The generated kernel names used to be treated as externally provided in the lower layer (`_HasDefaultName` recognizes customizations of kernel names made in the library when using `make_wrapped_policy` in contrast to `__new_kernel_name`). That led to issues with uniqueness of kernel names, because we assume externally provided names are unique even if we do not include types of arguments into a kernel name. You can find a code snippet leading to the error in #507. 
Signed-off-by: Sobolev, Dmitriy <dmitriy.sobolev@intel.com>

Fix kernel naming for Range-based APIs

---

documentation/library_guide/_templates/layout.html

I missed an endblock tag. This PR fixes that.

Updated layout.html with correct syntax

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

Fix "narrowing to type 'bool'" for clang (and dpcpp) compilers.
"error: constexpr if condition evaluates to 2, which cannot be narrowed to type 'bool'  [-Wc++11-narrowing]"

[oneDPL] + fix "error: constexpr if condition evaluates to 2, which cannot be narrowed to type 'bool'  [-Wc++11-narrowing]

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

[oneDPL] multiple definition hot fix:
`void  __wait_event(sycl::event __e) => inline void __wait_event(sycl::event __e)`
A variant with 'constexpr ' is not applicable here.

[oneDPL] multiple definition hot fix, __wait_event(..) usage

---

test/parallel_api/ranges/reduce_by_key_ranges_sycl.pass.cpp
test/support/iterator_utils.h

Fixed error in ForwardIterator because of which ForwardIterator does not satisfy input_iterator requirements in C++20

Fix compile error: ForwardIterator does not satisfy input_iterator requirements in C++20

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

[oneDPL] undo usage of one-element sycl::buffer for return value for reduce and scan patterns (perf reasons)

[oneDPL] undo usage of one-element sycl::buffer for return value for reduce and scan patterns

---

test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/support/test_config.h

Fixed inclusive_scan_by_segment.pass failure on HOST device, icpc compiler with wrong effect error

Fix inclusive_scan_by_segment.pass failure on HOST device, icpc compiler with wrong effect error

---

test/parallel_api/algorithm/alg.modifying.operations/alg.reverse/reverse.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.reverse/reverse_copy.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/swap_ranges.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.set.operations/set.pass.cpp
test/support/utils_invoke.h

Some devices do not support fp16 (sycl::half) and fp64 (double) types. Let's skip such cases on these devices. 
The patch requires support of [Optional kernel features](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:optional-kernel-features) by a compiler. DPC++ does not fully support it yet, thus passing `-fsycl-device-code-split=per_kernel` during compilation is needed as a workaround.

Skip testing fp16/fp64 types if not supported by a device

---

examples/histogram/src/main.cpp
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h

[oneDPL][examples] + fix a error in histogram example. A wrong size of passed sequence.
"The sum of accessRange and accessOffset should not exceed the range of buffer."

[oneDPL][examples] + fix a error in histogram example

---

include/oneapi/dpl/internal/binary_search_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h

Fixed errors in upper_bound, lower_bound, binary_search algorithms: unable to call these algorithms with empty source data.

Check empty input data in binary search functions

---

include/oneapi/dpl/pstl/iterator_impl.h
test/parallel_api/iterator/zip_iterator.pass.cpp

The following use case identified is hand-migrated Thrust code.  The original application has functions that return tuples that are passed directly to `make_zip_iterator`.  Adding the `make_zip_iterator` interface that accepts a `std::tuple` of iterators to support this. Without it the tuple would have to be unpacked and elements passed to `make_zip_iterator` resulting in overly verbose code.

Support zip_iterator construction from tuple of iterators

---

documentation/library_guide/parallel_api/iterators.rst

The struct used as an index map for `permutation_iterator` must define a const member `operator[]`, not `operator()`. Closes #578.

Correct permutation_iterator example's index map function.

---

test/parallel_api/numeric/numeric.ops/in_place_scan.pass.cpp
test/support/scan_serial_impl.h

[oneDPL][test] + in_place_scan test fixes.
1) + usage of inclusive_scan_serial, exclusive_scan_serial within  in_place_scan.pass.cpp
2) + fixes for "in place" semantic for  inclusive_scan_serial, exclusive_scan_serial (used for the test support only)

[oneDPL][test] + in_place_scan test fixes

---

test/parallel_api/numeric/numeric.ops/in_place_scan.pass.cpp

A fix for 
https://github.com/oneapi-src/oneDPL/runs/7561089789?check_suite_focus=true
```
/usr/include/c++/9/pstl/parallel_backend_tbb.h: In lambda function:
/usr/include/c++/9/pstl/parallel_backend_tbb.h:596:24: error: ‘tbb::task’ has not been declared
596 |             using tbb::task;
|                        ^~~~
/usr/include/c++/9/pstl/parallel_backend_tbb.h:597:13: error: ‘task’ has not been declared
597 |             task::spawn_root_and_wait(*new (task::allocate_root())
|             ^~~~
/usr/include/c++/9/pstl/parallel_backend_tbb.h:597:45: error: ‘task’ was not declared in this scope; did you mean ‘tbb::detail::d1::task’?
597 |             task::spawn_root_and_wait(*new (task::allocate_root())
|                                             ^~~~
| …
```

[oneDPL][test] compilation fixes for in_place_scan test

---

examples/random/src/main.cpp
test/xpu_api/random/conformance_tests/common_for_conformance_tests.hpp
test/xpu_api/random/interface_tests/distributions_methods.pass.cpp
test/xpu_api/random/interface_tests/engines_methods.pass.cpp

Tests:
- get_cl_code is removed
- queue wait and throw reordered
Examples:
- sycl::buffer/accessor API updated

[RNG] [Tests] Remove outdated get_cl_code & clean-up

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h

Wrap sycl::buffer_allocator into __dpl_sycl::__buffer_allocator alias.
Implementation of __dpl_sycl::__buffer_allocator depends from __LIBSYCL_VERSION:
if __LIBSYCL_VERSION >= 50707 then
**template <typename _DataT>
using __buffer_allocator =s ycl::buffer_allocator<_DataT>;**
else
**template <typename _DataT>
using __buffer_allocator =s ycl::buffer_allocator;**

Wrap sycl::buffer_allocator into __dpl_sycl::__buffer_allocator

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
test/parallel_api/algorithm/alg.sorting/sort.pass.cpp

To trigger this bug, you can call `oneapi::dpl::stable_sort`  twice with the same policy and same numerical type.  One of those two times should use `std::greater<void>()`, and the other time with no compare operator or with `std::less<void>()`.  The same bug appears with `oneapi::dpl::partial_sort_copy`.  A test has been added to test/parallel_api/algorithm/alg.sorting/sort.pass.cpp to show this.
Without this patch, this would result in the following compiler error:
`error: definition with same mangled name`
This is because radix sort is enabled for both ascending and descending sort for numerical types, but previously the compare operator state has not been included in the kernel name generators.  This results in two different kernels being generated with the same name, as the …

Bugfix for clashing kernel name generation with radix sort (ascending + descending)

---

documentation/library_guide/api_for_sycl_kernels/tested_standard_cpp_api.rst

Removed std::unary_function from list of tested functions.
This function was removed from our code in
[oneDPL][tests] + Remove support of C++11 and C++14 from oneDPL #642

[oneDPL] + remove std::unary_function from list of tested functions

---

.github/workflows/ci.yml

Removal of C++11 testing from CI after its support has been removed from product in https://github.com/oneapi-src/oneDPL/commit/5a5b9534bd3446f0fb6a7f10d0499c2a2a6a4332

Remove C++11 testing from CI

---

include/oneapi/dpl/internal/random_impl/discard_block_engine.h

Changing type of internal parameter from int to size_t. 
Note: changes break ABI backward compatibility.

[oneDPL][RNG] Changing type of internal parameter of discard_block_engine

---

test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment_perm_it.pass.cpp
test/parallel_api/numeric/numeric.ops/in_place_scan.pass.cpp

Fixed some same mangled name in tests:
- test/parallel_api/numeric/numeric.ops/in_place_scan.pass.cpp
- test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment_perm_it.pass.cpp

[oneDPL][tests] + fix same mangled name in tests

---

test/xpu_api/numerics/complex.number/complex.literals/literals.pass.cpp
test/xpu_api/numerics/complex.number/complex.literals/literals1.pass.cpp
test/xpu_api/numerics/complex.number/complex.literals/literals2.pass.cpp

This change made to fix compile error
'__num' requires 128 bit size 'long double' type support, but target 'spir64-unknown-unknown' does not support it"
The root cause of this error in use complex literal "i" in next string of code:
dpl::complex c1 = 3.0i;
As described at https://en.cppreference.com/w/cpp/numeric/complex/operator%22%22i
complex literal "l" used for long double type: we have compile error in case of compile for device.

[tests] Fix complex tests compile-time error with "i", "if" literals

---

test/xpu_api/numerics/complex.number/complex.ops/stream_input.pass.cpp
test/xpu_api/numerics/complex.number/complex.ops/stream_output.pass.cpp

In this PR we fix compile error in tests of std::complex: no member named 'task' in namespace 'tbb'
This error occurred in cases when we have wrong order of includes and start use of old version of oneTBB library from GCC standard library of old versions.

[tests] fix order of include files in tests of complex

---

test/support/test_complex.h
test/xpu_api/numerics/complex.number/cmplx.over/pow.pass.cpp

In this PR we fix make the next things:
1) fix compile error: variable 'fnc1' cannot be implicitly captured in a lambda with no capture-default specified
2) add ability to send into test defines arguments with comma(s)

[tests] fix invalid lambda call in test of std::complex

---

include/oneapi/dpl/pstl/utils_ranges.h
test/parallel_api/ranges/guard_view.pass.cpp
test/parallel_api/ranges/zip_view.pass.cpp

The guard_view and zip_view bracket operator was previously using signed int32 for the type of the index.  
The fix changes this index to be a template argument which is in line with other views in this file.  
I've added some tests to cover the overflow case for signed int32 for zip_view and guard_view.  They fail without the changes, and pass after the changes.
This PR impacts https://github.com/oneapi-src/oneDPL/pull/608 ,  guard_view's bracket operator is used in the by_segment routines and this bug impacts correctness of those algorithms as they are written.

bugfix for guard_view and zip_view bracket operator 

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

This PR rewrites the reorder kernel of radix sort to select between three different implementations of computing the peer prefix. A peer prefix is the number of work-items in the same sub-group with smaller ID whose input element has the same state. The three implementations are:
- The original implementation that performs a sub-group scan followed by a sub-group broadcast
- An implementation that uses the `sycl::group_ballot` extension and a popcount
- An implementation similar to the `sycl::group_ballot` version that uses `atomic_ref`'s `fetch_or` method for platforms where the `group_ballot` extension is not available.
Preliminary results show that both new versions perform better than the current implementation in a microbenchmark.
This PR is joint work with @julianmi.

Rewrite radix sort's reorder kernel to use different peer prefix algorithms

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/iterator_impl.h
include/oneapi/dpl/pstl/utils_ranges.h
test/parallel_api/iterator/iterators.pass.cpp
test/parallel_api/iterator/permutation_iterator.pass.cpp

[oneDPL] permutation_iterator and permutation_view improvements
1. Added support usage case like in Boost (https://www.boost.org/doc/libs/1_38_0/libs/iterator/doc/permutation_iterator.html)
2. Aded support C++ functor as an index map  for  permutation_iterator (https://oneapi-src.github.io/oneDPL/parallel_api/iterators.html). 
3. Added support C++ functor as an index map  for  permutation_view
4. The test coverage was extended as well.
5. Added example for permutation_iterator from our documentation as test.

[oneDPL] Added support C++ functor/lambda  for permutation_iterator 

---

make/Makefile.common
make/dpcpp.inc
test/CMakeLists.txt
test/support/test_complex.h

Prepare different Kernels in tests of std::complex - with and without double to have ability
to use cmake option (compiler option) -DCMAKE_CXX_FLAGS="-fsycl-device-code-split=per_kernel"
for dpcpp compiler.
In this case we may run tests of std::complex on devices without double type support without run-time errors.

Prepare two different Kernels in tests of std::complex - with and without double type usage

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
test/support/sycl_alloc_utils.h
test/support/utils_sycl.h

Rename __LIBSYCL_VERSION macro

---

include/oneapi/dpl/pstl/ranges/nanorange.hpp

[oneDPL] Range library conflict std names fix (class match_results).
NanoRange library has recommendation how to fix it - "define the symbol NANORANGE_NO_STD_FORWARD_DECLARATIONS":
```
// Avoid dragging in the large <set> and <unordered_set> headers
// This is technically undefined behaviour: define the symbol
// NANORANGE_NO_STD_FORWARD_DECLARATIONS
// to enforce standard-compliant mode
NANO_BEGIN_NAMESPACE_STD
template <typename, typename>
class basic_string_view;
template <typename, typename, typename>
class set;
template <typename, typename, typename>
class multiset;
template <typename, typename, typename, typename>
class unordered_set;
template <typename, typename, typename, typename>
class unordered_multiset;
template <typename, typename>
class match_results;
NANO_END_NAMESPACE_STD …
```

[oneDPL] Range library conflict std names fix (class match_results)

---

make/Makefile.common
make/dpcpp.inc
test/CMakeLists.txt
test/support/test_complex.h

There are some issues that have arisen after applying PR #691:
- Multiple `-fsycl-device-code-split=per_kernel` options
- This option is not essential; however, it is used when compiling all the tests by default
- Now we enable `-fsycl-device-code-split=per_kernel` when a compiler supports `-fsycl` regardless of the support of `-fsycl-device-code-split` option. That produces errors when using clang 11 and newer (it has `-fsycl`, but does not have `-fsycl-device-code-split`)
Let's revert these changes for now.
Example of a command when using clang++ 14 (Ubuntu 22.04):
```bash
cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=release -DCMAKE_CXX_COMPILER=clang++ <path/to>/oneDPL && make for_each.pass VERBOSE=1
>> cd /tmp/b/test && /usr/bin/clang++ -DTBB_USE_GLIBCXX_VERSION=70300 …
```

Revert Cmake/Make changes done in PR #691

---

include/oneapi/dpl/pstl/experimental/internal/reduction_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
test/parallel_api/algorithm/alg.nonmodifying/for_each.pass.cpp
test/parallel_api/experimental/for_loop.pass.cpp
test/parallel_api/experimental/for_loop_induction.pass.cpp
test/parallel_api/experimental/for_loop_reduction.pass.cpp
test/parallel_api/memory/specialized.algorithms/uninitialized_copy_move.pass.cpp
test/support/utils_sequence.h

Something changed in the codespell github action check, and it started complaining about some misspellings in comments and hard to understand variable names as of 11/30/2022 9am EST.  This PR should resolve all those complaints, and includes some formatting suggested by clang-format on those affected files.  
This commit should not change anything functionally, but it should get the codespell check passing again.

codespell suggestions and formatting

---

.github/workflows/ci.yml

Fixing clang-format check to run on ubuntu 20, so we still have access to clang-format-6.0.

Clang format github runner running on ubuntu 20

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

oneDPL has to provide kernel names even for "unnamed lambda" case in certain conditions.
Add type template parameter in addition to generated kernel name to be able to set human readable kernel name explicitly.

Add human readable kernel names for "unnamed lambda" case

---

include/oneapi/dpl/pstl/experimental/internal/reduction_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
test/parallel_api/algorithm/alg.nonmodifying/for_each.pass.cpp
test/parallel_api/experimental/for_loop.pass.cpp
test/parallel_api/experimental/for_loop_induction.pass.cpp
test/parallel_api/experimental/for_loop_reduction.pass.cpp
test/parallel_api/memory/specialized.algorithms/uninitialized_copy_move.pass.cpp
test/support/utils_sequence.h

Resolving new codespell suggestions from checks.  
This should only be a variable name and comment spelling change, and should not change any functionality.
Removed any extra formatting changes which aren't in the lines touched.

Codespell suggestions 

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

[oneDPL] radix sort change: 'remove' one kernel - global scan for histogram bins. Also a temporary buffer size is reduced by "radix_state" elements.

[onedpl] Radix sort change: 'remove' one kernel - global scan for histogram bins

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

In this PR we __dpl_sycl::__atomic_ref as alias for modern dpcpp compiler:
```
template <typename _AtomicType, sycl::access::address_space _Space>
#if _ONEDPL_SYCL2023_ATOMIC_REF_PRESENT
using __atomic_ref = sycl::atomic_ref<_AtomicType, sycl::memory_order::relaxed, sycl::memory_scope::work_group, _Space>;
#else
struct __atomic_ref : sycl::atomic<_AtomicType, _Space>
{
explicit __atomic_ref(_AtomicType& ref)
: sycl::atomic<_AtomicType, _Space>(sycl::multi_ptr<_AtomicType, _Space>(&ref)){};
};
#endif // _ONEDPL_SYCL2023_ATOMIC_REF_PRESENT
```

__dpl_sycl::__atomic_ref improvements

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h

In this PR we fix get_info<sycl::info::kernel_device_specific::max_sub_group_size> deprecated warning for DPC++ compiler:
now required to use get_info<sycl::info::kernel_device_specific::work_group_size>(const sycl::device&) without second param.
Fixed DPC++ compiler warnings:
```
In file included from /include/oneapi/dpl/algorithm:27:
In file included from /include/oneapi/dpl/pstl/glue_algorithm_defs.h:22:
In file included from /include/oneapi/dpl/pstl/hetero/dpcpp/../../execution_defs.h:237:
/include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h:390:27: warning: 'get_info<sycl::info::kernel_device_specific::max_sub_group_size>' is deprecated: Use the overload without the second parameter [-Wdeprecated-declarations]
__kernel.template …
```

[oneDPL] Fix get_info<sycl::info::kernel_device_specific::max_sub_group_size> deprecated warning

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

Some changes in this patch are just renaming, but there are also more interesting ones:
- Simplified (and likely faster) implementation of "bit floor" (renamed __get_rounded_down_power2) function via sycl::clz;
- Simplified (and likely faster) implementation of __get_bucket via pre-computing radix offset which is now passed via function parameters instead of the iteration number;
I think these changes cannot negatively impact performance, but let me know if you think otherwise and performance measurements are needed.

Radix sort implementation improvements

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

Yet another attempt to simplify (and maybe speed up a little) the radix sort implementation. This time, I reworked the type and bit manipulation utilities that prepare values for radix counting (i.e. the "ordered" family in the current implementation).
The idea was to make it less "orthogonal" and combine masking for signed ints and floats with the inversion for descending sort. And I only use one level of generalization (via function overloads) instead of three in the current implementation - so I hope it will also be simpler to understand. As a bonus comes a reasonable and potentially reusable implementation of C++ 20 `bit_cast<>`.
I kept the old code under `#if 0` just to simplify reviewing; will remove it later, once you take a look.
@dmitriy-sobolev @MikeDvorskiy @adamfidel …

Radix sort: simplify bit manipulations

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

These modifications change the loop conditions to combine both out-of-segment and out-of-data-range conditions, computed separately for each work item. This removes several internal checks for out-of-range and simplifies the code quite a lot, but makes the loop boundaries non-uniform. Nevertheless, internal testing shows that performance is slightly (single-digit percent) better with this patch.

Radix sort: loop modifications

---

.github/workflows/ci.yml

cl.cfg is modified to specify installation location of Intel® oneAPI Threading Building Blocks according to the note from https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-dpc-c-compiler-release-notes-2022.html:
> However, in other scenarios, OpenCL CPU RT will fail to load TBB since there is no TBB registry key installed and the TBB file in the configuration file is not set by default.... At the bottom of the file, there is a field named “CL_CONFIG_TBB_DLL_PATH,” to which you can add your TBB DLL path. For example: CL_CONFIG_TBB_DLL_PATH = c:\your_TBB_install_path

CI: make oneTBB available when testing on Windows

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

`__dpl_bit_cast`, `__dpl_bit_floor`, `__ceiling_div` moved from the radix sort implementation to the general SYCL utilities and improved/fixed (including the fix for compilation errors in C++20 mode).
`explicit_wait_if` and its sole use in radix sort are removed; it seems to be a workaround for some issues 2+ years back (in the code since GitLab times), and it is not used anywhere else. If someone remembers what it is about please comment how to check if it is still needed.
The implementation of `__future` is simplified a bit via combining condition-dependent waits and getting the value into a single overloaded routine. It's less orthogonal but these utilities are not used anywhere else, so I do not see much value in orthogonality which is not really used.

Improve the SYCL backend utility functions

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

In this PR we fix deprecated sycl::access::target::local enum value usage:
```
enum class target {
// ...
local __SYCL2020_DEPRECATED("use `local_accessor` instead") = 2016,
// ...
};
```
Instead this enum value we start using of ```sycl::local_accessor``` class.
For additional information about class ```sycl::local_accessor``` please see
https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_interface_for_local_accessors

Fix deprecated sycl::access::target::local enum value usage

---

include/oneapi/dpl/internal/async_impl/async_impl_hetero.h
include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h

Splitting #725 in to multiple PRs.
This PR replaces the internal helper functions oneapi::dpl::__internal::__invoke_if, oneapi::dpl::__internal::__invoke_if_not and oneapi::dpl::__internal::__invoke_if_else with if constexpr now that oneDPL is free to use C++17 constructs.

Replace instances of __invoke_if/__invoke_if_not (#725 part 1)

---

include/oneapi/dpl/pstl/utils.h

After #746 and #747, these helper functions are no longer used.

Remove unused __invoke_if utils

---

test/xpu_api/numerics/c.math/cmath.pass.cpp
test/xpu_api/numerics/complex.number/cases.h
test/xpu_api/numerics/complex.number/cmplx.over/arg.pass.cpp
test/xpu_api/numerics/complex.number/cmplx.over/norm.pass.cpp
test/xpu_api/numerics/complex.number/cmplx.over/pow.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/assignment_complex.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/assignment_scalar.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/divide_equal_complex.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/minus_equal_complex.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/minus_equal_scalar.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/plus_equal_complex.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/plus_equal_scalar.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/times_equal_complex.pass.cpp
test/xpu_api/numerics/complex.number/complex.member.ops/times_equal_scalar.pass.cpp
test/xpu_api/numerics/complex.number/complex.members/real_imag.pass.cpp
test/xpu_api/numerics/complex.number/complex.ops/complex_divide_complex.pass.cpp
test/xpu_api/numerics/complex.number/complex.ops/scalar_divide_complex.pass.cpp
test/xpu_api/numerics/complex.number/complex.ops/unary_minus.pass.cpp
test/xpu_api/numerics/complex.number/complex.ops/unary_plus.pass.cpp
test/xpu_api/numerics/complex.number/complex.special/double_float_explicit.pass.cpp
test/xpu_api/numerics/complex.number/complex.transcendentals/pow_scalar_complex.pass.cpp
test/xpu_api/numerics/complex.number/complex.transcendentals/sqrt.pass.cpp
test/xpu_api/numerics/complex.number/complex.value.ops/imag1.pass.cpp
test/xpu_api/numerics/complex.number/complex.value.ops/real1.pass.cpp

In this PR we fix the following problem:
- avoid runtime-error (exception) when we run tests of ```::std::complex<T>``` on device without ```double``` type support.
To fox this problem in tests we change usage of constants like ```1.5``` and etc. which has ```double``` type:
- we change ```1.5``` -> ```1.5f``` and etc.
- some peace's of tests moved under ```IF_DOUBLE_SUPPORT``` condition check.

Avoid double type in tests of std::complex<T>

---

test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp

In this PR we fix warning in test transform_binary.pass.cpp :
```
/oneDPL/test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp:52:85: warning: floating-point comparison is always true; constant cannot be represented exactly in type 'float' [-Wliteral-range]
EXPECT_TRUE((expected > actual ? expected - actual : actual - expected) < 1e-7,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~
/oneDPL/test/support/utils.h:59:67: note: expanded from macro 'EXPECT_TRUE'
#define EXPECT_TRUE(condition, message) ::TestUtils::expect(true, condition, __FILE__, __LINE__, message)
^~~~~~~~~
/oneDPL/test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp:74:9: note: in instantiation of function template specialization …
```

Fix warning in transform_binary.pass.cpp

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h

In this PR we fix case for remove_copy algorithm and other when output buffer size is less then source buffer size.
In this case we had assertion at [include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h](https://github.com/oneapi-src/oneDPL/blob/main/include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h), line 493:
```
assert(__offset + __n <= __size);
```
Example for reproduce this assert:
```
dpct::device_ext& dev_ct1 = dpct::get_current_device();
sycl::queue& q_ct1 = dev_ct1.default_queue(); // device iterator
const int N = 6;
int A[N] = {-2, 0, -1, 0, 1, 2};
int B[N - 2];
int ans[N - 2] = {-2, -1, 1, 2};
dpct::device_vector<int> V(A, A + N);
dpct::device_vector<int> result(B, B + N - 2);
oneapi::dpl::remove_copy(oneapi::dpl::execution::make_device_policy(q_ct1), V.begin(), …
```

Fix buffer size calculation in algorithm_impl_hetero.h for hetero iterator

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h

A fix for following error
```
include\oneapi/dpl/internal/../pstl/iterator_impl.h(428,37): error: no matching constructor for initialization of 'oneapi::dpl::__internal::sycl_iterator<sycl::access::mode::read_write, int>'
transform_iterator(_Iter __it = _Iter(), _UnaryFunc __unary_func = _UnaryFunc())
^
include\concepts(106,8): note: in instantiation of default function argument expression for 'transform_iterator<oneapi::dpl::__internal::sycl_iterator<sycl::access::mode::read_write, int>, (lambda at test\parallel_api\iterator\transform_iterator.pass.cpp:86:27)>' required here
&& __is_constructible(_Ty, _ArgTys...);
^
include\concepts(106,8): note: while substituting template arguments into constraint expression here
&& __is_constructible(_Ty, _ArgTys...); …
```

[oneDPL] + a default constructor for sycl_iterator

---

test/general/test_policies.pass.cpp

In this PR we fix compile error in test test/general/test_policies.pass.cpp :
```error: no matching function for call to 'make_device_policy'```
The next call in the file [test/general/test_policies.pass.cpp](https://github.com/oneapi-src/oneDPL/blob/main/test/general/test_policies.pass.cpp#L71)
```
test_policy_instance(make_device_policy<class Kernel_12>(TestUtils::default_selector));
```
is incompatible with SYCL 2020 library version because the constructor of sycl::queue now is **explicit** (please see paragraph ["4.6.5.1. Queue interface"](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_queue_interface) for details) :
```
template <typename DeviceSelector,
typename =
detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>>
explicit queue(const …
```

Fix error in make_device_policy call

---

test/support/iterator_utils.h
test/support/test_iterators.h

The implementation of `ForwardIterator` in `test/support/iterator_utils.h` defines `operator->()`  to returns an `Iterator` rather than a its wrapped Iterator's `pointer`.  This causes issues with the Microsoft STL c++20 implementation of `std::reverse_iterator(ForwardIterator)` in the `noexcept` section of `operator->()`.  It forces the return of the `ForwardIterator::operator->()` to be implicitly convertible to its `ForwardIterator::pointer`, which was not the case until this change.
The point of this `ForwardIterator` class is to restrict the iterator in question to a LegacyForwardIterator.  Therefore, it can be assumed that the wrapped `Iterator` satisfies LegacyForwardIterator, and has `operator->()` available, or it is a pointer itself.
This resolves a compilation error in tests …

ForwardIterator operator->() fix

---

test/support/iterator_utils.h

As mentioned in the comments of https://github.com/oneapi-src/oneDPL/pull/763#discussion_r1090450525, this implementation is more correct than `::std::addressof`, which will always return a raw pointer.  If a smart pointer or some other complex type was defined to `pointer` for the incoming iterator, there would be a type mismatch between the return type of `operator->()` and the value returned in the previous implementation.

ForwardIterator operator-> with pointer specialization

---

test/parallel_api/experimental/for_loop_induction.pass.cpp

In this PR we fix usage of moved object in test/parallel_api/experimental/for_loop_induction.pass.cpp

Fix usage of moved local variable in tests

---

CMakeLists.txt

oneDPL removed support of C++11 and C++14 since 2022.0.0 release, and these changes help to avoid issues related to using older standards when oneDPL is integrated via CMake.
There are 2 ways to integrate oneDPL via CMake:
1. As source code: https://github.com/oneapi-src/oneDPL/tree/main/cmake#using-onedpl-source-files
2. As a package: https://github.com/oneapi-src/oneDPL/tree/main/cmake#using-onedpl-package
This PR adds a requirement for using C++17 as a minimum standard version for the option (1). 
This change was inspired by #739, which adds this requirement for the option (2).
`target_compile_features(oneDPL INTERFACE cxx_std_17)` will force c++17 as a minimum standard version for targets using oneDPL. If a user requests C++11, then C++17 will be silently used. Using newer standards …

CMake: require C++17 when using oneDPL from source files

---

test/support/test_iterators.h

Similar to #768, this resolves a potential issue with the set of test iterator adapters and aligns their `pointer` type and return value from the `operator->()`.  We call the wrapped iterator's `operator->()`, and specialize at compile time for pointers.
This PR also simplifies an unused feature of `input_iterator` to specify a template argument separate from its wrapped iterator type, specifically for use in `::std::iterator_traits`.  This was unused and was out of line with the rest of the test iterator adapters in this file, so I removed it.  (This can be returned if we don't want to make this change.)

Test iterators operator-> fix

---

test/parallel_api/algorithm/alg.sorting/alg.min.max/max_init_list.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.min.max/min_init_list.pass.cpp
test/xpu_api/algorithms/alg.nonmodifying/alg.find/xpu_find.pass.cpp

Temporary testing workaround to avoid currently unsupported calls to vector algorithms from inside sycl kernels when calling `find()` or initializer list overloads of `min()` and `max()` on Windows at runtime.
Define must be set prior to include of the standard library headers. There is no natural unified location, given the need to precede the standard library headers.  It seems best to add the workaround in each test individually.  This also provides more apparent documentation of the known limitation.

Testing workaround to avoid unsupported calls in kernel

---

documentation/library_guide/parallel_api/range_based_api.rst

united shared memory -> unified shared memory

Fix wording in the library guide

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

The patch fixes the error "no template named 'bit_cast' in namespace 'sycl'; did you mean 'sycl::detail::bit_cast'?" with older versions of libsycl which did not have the function in the sycl namespace.
I decided not to create a distinct preprocessor branch for these older versions, because that implementation is practically identical to the one at lines 66-74.

Change the condition for sycl::bit_cast to check the libsycl version

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

[oneDPL] radix sort: moved some type aliases to place of using ones.

[oneDPL] radix sort: moved some type aliases to place of using ones

---

cmake/templates/oneDPLConfig.cmake.in

Add the c++17 compile feature requirement to the oneDPL target so consumers also use c++17. This is still overridden by the CXX_STANDARD target property, so there still can be sharp edges for users.

Add C++17 requirement to installed oneDPL target

---

include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h

In this PR we fix an error in the comparison of input and output iterators which was introduced in https://github.com/oneapi-src/oneDPL/pull/761 :
in this comparison we receive compile error in DPC++ compiler (win) ```Error GE509BDA3 invalid operands to binary expression```

Fix error in iterator comparison

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

The implementation of reorder phase made in PR #716 has an issue of making the loop boundaries non-uniform within a workgroup/subgroup. This have made the use of group operations (in "peer contribution") incorrect, and caused test failures.
The patch makes the loop boundaries uniform, with the non-uniform residual processed separately after the loop. Also, a similar loop in the count phase is modified to use a similar approach for computing the loop boundary, though still leaves it non-uniform, as group operations are not used there.

Make the loop boundaries uniform for group operations

---

include/oneapi/dpl/execution

In this PR we fix warning C4515: 'execution': namespace uses itself
Please see https://github.com/oneapi-src/oneDPL/issues/759 for additional info.

Fix warning C4515: 'execution': namespace uses itself

---

include/oneapi/dpl/pstl/glue_algorithm_defs.h

In this algorithm we fix wrong comments in glue_algorithm_defs.h file.
This comments were introduced in PR https://github.com/oneapi-src/oneDPL/pull/561.
For details please see https://github.com/oneapi-src/oneDPL/issues/720

Fix comment in glue_algorithm_defs.h

---

test/general/buffer_wrapper.pass.cpp

In this PR we fix compile error from the issue https://github.com/oneapi-src/oneDPL/issues/788 :
```
test/general/buffer_wrapper.pass.cpp:37:26: error: no matching conversion for functional-style cast from 'sycl::buffer<unsigned int, dim, aligned_allocator<unsigned int>>' to 'sycl::host_accessor<const unsigned int, 1, sycl::access_mode::read>'
T* actual_data = sycl::host_accessor<T, 1, sycl::access_mode::read>(buf).get_pointer();
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This error were introduced in https://github.com/oneapi-src/oneDPL/pull/281

Fix errors in test buffer_wrapper.pass

---

test/support/test_complex.h

An identified issue on many systems has been segfaulting test cases when the CPU is selected as the device. I have reproduced this issue and identified the cause as the program exiting main prior to the submitted kernels finishing. There is no implicit wait in any of these kernels or an explicit wait within the test code. This PR adds a wait after kernel submission in `test/support/test_complex.h`. Adding this wait has resolved this issue on the systems I have reproduced the error on.

Ensure Complex Test Kernels Finish before Main Ends

---

CMakeLists.txt

In this PR we rename some internal variables in the ```CMakeLists.txt``` file.
The goal of this renaming - do not use prefix of oneDPL macros for names of internal variables in the file ```CMakeLists.txt```.
What were renamed:
- ```ONEDPL_USE_BACKEND_DPCPP``` -> ```SET_BACKEND_DPCPP```
- ```ONEDPL_USE_BACKEND_DPCPP_ONLY``` -> ```SET_BACKEND_DPCPP_ONLY```
- ```ONEDPL_USE_BACKEND_TBB``` -> ```SET_BACKEND_TBB```

Rename variables in CMakeLists.txt

---

CMakeLists.txt
include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
test/parallel_api/experimental/asynch.pass.cpp
test/parallel_api/iterator/transform_iterator.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/support/utils_test_base.h
test/xpu_api/random/interface_tests/engines_methods.pass.cpp

1. AoT: `spir64_gen-unknown-unknown-sycldevice` to `spir64_gen`, `-Xs` to `-Xsycl-target-backend`
2. get_access() host to get_host_access() APIs

Address SYCL 2020 deprecations

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h

This replaces `__kernel_name_generator` with `__kernel_name_provider` in the reduce patterns.

Use kernel_name_provider in Reduce Patterns

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

This PR replaces `__kernel_name_generator` with `__kernel_name_provider` in the single group scan algorithm.

Replace kernel_name_generator in single-group scan

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

The `_HasDefaultName` utility does not match kernel names that have multiple template parameters. This PR fixes the utility to check if any of the template parameters is the default name.
Co-authored with @rarutyun.

Correct usage of _HasDefaultName utility

---

CMakeLists.txt
cmake/templates/oneDPLConfig.cmake.in

cmake cannot properly detect c++17 with dpcpp and dpcpp-cl compiler drivers on Windows.
This results in the following issue:
```bash
CMake Error in test/CMakeLists.txt:
No known features for CXX compiler
"Clang "
version .
```
The changes from #822 fix that issue as well, but for some unknown (so far) reason, cmake cannot detect compiler features properly, e.g.:
```bash
-- The CXX compiler identification is IntelLLVM 2023.0.0 with MSVC-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Miniconda/Library/bin/dpcpp.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring oneDPL 2022.1.0
-- Performing Test _fsycl_option
-- Performing Test _fsycl_option - Failed
-- …
```

Do not require c++17 with dpcpp/dpcpp-cl on Windows

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

In this PR we fix mangled name which have place in ixpc compiler with options ```-fsycl``` and ```-fsycl-unnamed-lambda``` too :
```
In file included from include/oneapi/dpl/execution:61:
In file included from include/oneapi/dpl/pstl/algorithm_impl.h:31:
In file included from include/oneapi/dpl/pstl/parallel_backend.h:19:
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h:430:86: error: definition with same mangled name '_ZTSN6oneapi3dpl20__par_backend_hetero10__internal11__compositeINS1_31__scan_single_wg_dynamic_kernelIJEEEJLc95ELc90ELc84ELc83ELc78ELc54ELc111ELc110ELc101ELc97ELc112ELc105ELc51ELc100ELc112ELc108ELc50ELc48ELc95ELc95ELc112ELc97ELc114ELc95ELc98ELc97ELc99ELc107ELc101ELc110ELc100ELc95ELc104ELc101ELc116ELc101ELc114ELc111ELc51ELc49ELc95ELc95ELc115ELc99ELc97ELc110ELc95EL …
```

Fix mangled name

---

documentation/library_guide/api_for_sycl_kernels/random.rst
documentation/library_guide/api_for_sycl_kernels/tested_standard_cpp_api.rst
documentation/library_guide/introduction/onedpl_gsg.rst
documentation/library_guide/onedpl_gsg.rst
documentation/library_guide/parallel_api/execution_policies.rst

In this PR we make the next things:
- remove deprecated SYCL code from oneDPL documentation;
- unify order of included headers in documentations examples.

Remove deprecated code from oneDPL documentation

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h

This PR changes the single-group scan, sort and reduce algorithm to account for local device memory that may be used by the compiled kernel.
For scan and sort, we ensure that we only attempt to allocate up to half of the local memory provided by the device. For reduce, we double the local memory requirement.

Adjust local memory requirement for single-group scan, sort and reduce

---

test/general/buffer_wrapper.pass.cpp

An issue on certain systems is that the `buffer_wrapper.pass` test case hangs indefinitely. The cause of this issue has been identified as the presence of multiple host accessors with write access to the same underlying buffer. When the second host accessor is created, its constructor may hang waiting for the first to destruct which will never happen. Since we only perform read operations with these accessors, we can explicitly mark them as `sycl::read_only`. This change resolves the issue as the accessors no longer have the ability to modify the underlying buffer and the construction of subsequent accessors will no longer block.

Fix Hanging buffer_wrapper.pass Test

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

The 'Args' template parameter in the joint_exclusive_scan wrapper implementation used when SYCL 2020 collectives are not available is missing a leading underscore.

Adding missing underscore to template parameter name

---

include/oneapi/dpl/internal/async_impl/async_utils.h

My bad, forgot to change the use of `__is_convertible_to_event` after changing its definition from `bool_constant` to `bool`.

Fix a compilation error in async algorithms introduced by #811

---

cmake/README.md
cmake/scripts/generate_config.cmake
integration/pkgconfig/dpl.pc.in

This generates the right header path for the package config files when they are generated with `SKIP_HEADERS_SUBDIR` set to `TRUE`.
This is useful for creation of e.g., conda packages which do not have `windows` or `linux` subdirectories.

Fix header path in pkg-config files generated without OS subdir

---

.github/workflows/ci.yml

Using the latest actions versions is needed to fix deprecations, e.g.:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Specifying the latest version for python resulted in another warning:
> The `python-version` input is not set. The version of Python currently in `PATH` will be used.
That is why the latest stable (3.x) version …

CI: fix "Node.js 12 actions are deprecated" warnings

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

One of the issues that has been identified with the new reduce implementation are segfaulting tests on certain operating systems when compiled with the latest DPC++ compiler in release mode with C++17 and ran on the CPU. This issue has been identified as an illegal memory access that stems from the incorrect result of [this](https://github.com/oneapi-src/oneDPL/blob/661cc91707e39a4efde47c7a573eb40c71cc971f/include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h#L219) assignment.
Within `const ::std::int64_t __items_to_process = __n - (__iters_per_work_item * __global_id);`, `__n` and `__iters_per_work_item * __global_id` are both `std::size_t` datatypes. Despite assigning the result to a `std::int64_t` type, the result may wrap around to a large integer when `__iters_per_work_item * …

Fix Integer Wraparound in Single Group Reduce

---

include/oneapi/dpl/pstl/utils_ranges.h

[oneDPL] a hot fix for 'permutation_view_simple' pseudo range.
The oneDPL internal views ("pseudo" ranges or "simple" views) have limited semantic and don't have begin/end for most of them, just subscription operator and size/empty methods.
Everywhere the impl doesn't rely on begin/end. just on operator[]/size/empty methods.
But one place remains and a customer faced to compilation issue with 'permutation_view_simple':
`error: implicit instantiation of undefined template 'oneapi::dpl::__ranges::permutation_view_simple<oneapi::dpl::__ranges::guard_view<int *>, oneapi::dpl::__ranges::transform_view_simple<oneapi::dpl::__ranges::guard_view<int *>, (lambda at par_amg_setup.c:20:16)>>'`
We have got unexpected specialization being chosen based on SFINAE helper `struct …

[oneDPL] a hot fix for 'permutation_view_simple' pseudo range

---

.github/workflows/ci.yml

Change mixed approach for naming jobs to "name=value,name_1=value_1,...,name_n=value_n" for values which need keys for clarity. 
Name before the changes:
`ubuntu-20.04_g++_backend=tbb_device=HOST_cxx17_release`
Name after the changes:
`ubuntu-20.04,cmplr=g++,backend=tbb,device=HOST,std=17,build_type=release`
Upd. The most important properties are shown first due to 28-symbol limit of the view panel:
`HOST,bknd=tbb,cmplr=g++,ubuntu-20.04,std=c++17,cfg=release`
Previous '_' separator might have confused c++ developers. For example, ones may get surprised to find 'tbb_device'.

Make CI job names more readable

---

.github/workflows/ci.yml

Ubuntu 18.04 will not be supported after March. I have updated the 18.04 version of Ubuntu to latest, via the script. I tested the changes and they passed successfully.

Updated Ubuntu 18.04 to Ubuntu latest

---

include/oneapi/dpl/experimental/kernel_templates
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

I think this stuff should go into its own header, instead of `<algorithm>` etc.

Move ESIMD algorithms into a separate header

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h

The changes in #782 introduced different signatures for `__parallel_transform_reduce` between the device and FPGA versions. The previous `typename _Functor` parameter needs to be removed to successfully compile FPGA code.

Fix old reduce pattern signature on FPGAs

---

include/oneapi/dpl/internal/async_impl/glue_async_impl.h
include/oneapi/dpl/pstl/execution_defs.h
include/oneapi/dpl/pstl/glue_algorithm_ranges_defs.h
include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/utils_ranges.h
test/parallel_api/ranges/sort_ranges_sycl.pass.cpp

[oneDPL] + projection support for radix_sort pattern, ranges::sort API.
We use oneapi::dpl::__internal::__no_op, because std::identity is available from C++20.

[oneDPL] + projection support for radix_sort pattern, ranges::sort API

---

test/parallel_api/algorithm/alg.nonmodifying/equal.pass.cpp

Some platforms do not support the double type. The testing harness cannot recognize it as a part of a complex type. And thus, the related test cases are not skipped. 
This PR replaces a double type in a complex type. It allows fixing the error:
```
Build program log for 'Intel(R) Iris(R) Xe Graphics
...
error: Double type is not supported on this platform.
in file: equal.pass.cpp:88
```

Fix equal.pass on platforms non-supporting double type

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

The patch refactors the SIMD utility functions for load, store, gather, and scatter:
* Removes `enable_if` SFINAE, instead using specific parameter types
* Aligns the API semantics (parameter order, types, and names)
* For `gather`, also fixes the result type to differ from offsets, and moves items-to-bytes conversion to the caller (consistent to `scatter`)
Also it removes unneeded `inline` specifiers and adds missed standard headers.

Improve utility functions

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

1) Using custom deleter in __reduce_future::__my_res shared pointer
2) Fix some compile errors
3) Using move semantic in params of the __reduce_future constructor

Using custom deleter in __reduce_future::__my_res shared pointer

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

This patch improves the throughput of the group reductions with unknown identities. These are used in many algorithms with specialized or used-defined operators or data types including the `min_element()`, `max_element()`, `minmax_element()`, `is_partitioned()`, and `lexicographical_compare()` algorithms.
The main changes are the switch from a while loop to a for loop and the removal of the `__global_idx < __n` check which is covered by the `__global_idx + __k < __n`.
This change preserves the same memory ordering and allows for non-commutative algorithms. While the memory access patterns could be improved by using a decreasing stride instead of the used increasing stride, this would require commutative algorithms.

Improve Performance of Group Reductions with Unknown Identities

---

include/oneapi/dpl/pstl/onedpl_config.h
test/support/test_config.h

Adding checks for the presence of sycl headers prior to enabling sycl backend.  
This is required when compilers support `-fsycl` option and define `SYCL_LANGUAGE_VERSION`, without making SYCL implementation available in practice.

Add check for sycl header before enabling sycl backend

---

test/CMakeLists.txt

In this PR we setup ```_ITERATOR_DEBUG_LEVEL``` to 0 on Windows for tests.
The goal of this change - to avoid compile error like the next one :
```
In file included from test\xpu_api\numerics\numeric.ops\reduce\xpu_reduce.pass.cpp:17:
In file included from include\oneapi/dpl/numeric:21:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\numeric:11:
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xutility(868,5): error: SYCL kernel cannot call a variadic function
_STL_VERIFY(_First <= _Last, "transposed pointer range");
^
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\yvals.h(190,13): note: expanded from macro '_STL_VERIFY' …
```

Setup _ITERATOR_DEBUG_LEVEL to 0 on Windows for tests

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/utils_ranges.h
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp

Summary
---
One type of predicate that is used for in reduce by segment is a flag predicate, where the start of each segment is marked with a 1.  
The reduce_by_segment range implementation does not work for such a predicate.  The reduce_by_segment range implementation has a pair of issues with such a predicate.  
1. It does not preserve the ordering of the predicate comparisons.  Internally, it calls `binary_pred(i+1, i)`, where such a predicate requires the predicate is always called in order `binary_pred(i, i+1)`.  _Note this is the predicate to determine segments, not the binary reduction operation._
2. It does not copy the first key from each segment to the output, but the last key from each segment.  The implementation is a two round reduction_by_segment limiting segments to the …

Reduce_by_segment range implementation with flag predicate

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
test/parallel_api/algorithm/alg.sorting/sort.pass.cpp

The PR #859 accidentally introduced a change that required the comparison functor to provide a const `operator()`. This PR relaxes that requirement by changing the introduced lambda to be `mutable`.

Allow sort to use non-const comparison functor

---

include/oneapi/dpl/pstl/utils_ranges.h

This adds the missing `value_type` to `replicate_start_view_simple` that became a requirement with changed introduced in #703.

Adding value_type to replicate_start_view_simple

---

include/oneapi/dpl/pstl/utils.h

Modify `utils.h` to only check the feature test macro for `<bit>`, instead of also looking at the C++ version.
This was causing a compilation error in the most recent version of intel/llvm compiling with libstdc++ 9.

Modify to only test feature macro for `<bit>`

---

test/CMakeLists.txt

The goal of this PR is to avoid compile errors when we use checked iterators from MS STL library inside Kernel's code.
Previously we have compile errors in this situation like this:
```
In file included from test\xpu_api\numerics\numeric.ops\reduce\xpu_reduce.pass.cpp:17:
In file included from include\oneapi/dpl/numeric:21:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\numeric:11:
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xutility(868,5): error: SYCL kernel cannot call a variadic function
_STL_VERIFY(_First <= _Last, "transposed pointer range");
^
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\yvals.h(190,13): note: expanded …
```

Disable checked iterators on Windows for tests which required onedpl backend

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h

A couple of useful improvements from the work-in-progress branch; in particular, the sorting identity value for filling "useless" SIMD lanes at the end of the data.

Add a template variable for sorting identity; improve __get_bucket

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

Key changes: Use the sort identity for filling in extra vector lanes, and fix the scatter mask when writing the results back. Also there are some cosmetic improvements, and the test is updated.

[KT] Extend one workgroup implementation to sort signed integers & floats

---

documentation/CHANGES.rst
documentation/library_guide/introduction.rst
documentation/library_guide/macros.rst
documentation/library_guide/onedpl_gsg.rst
documentation/library_guide/parallel_api/execution_policies.rst
documentation/release_notes.rst

Updated all URLs with the old schema software.intel.com and updated some URLs that were resulting in a 404.

Update software.intel.com URLs

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

In this PR we declare common template params as constexpr in test for esimd radix sort;
- remove const uint32_t sweep_threads as unused;

Declare common template params as constexpr

---

include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h

Use of an object after it was forwarded or moved is incorrect, and is reported as an issue by static analysis tools.

Do not forward or move variables that are used later

---

CMakeLists.txt
cmake/oneDPLWindowsIntelLLVMConfig.cmake

CMakeLists relies on `INTEL_LLVM_COMPILER` and `INTEL_LLVM_COMPILER_VERSION` variables. Currently, they are not defined unless `ONEDPL_TEST_WIN_ICX_FIXES` is on.
A side effect of the change is that when `ONEDPL_TEST_WIN_ICX_FIXES` is on and this `CMakeLists` is used, these variables are set again inside `oneDPLWindowsIntelLLVMConfig.cmake` and have the same values. This does not change CMake behavior.
I additionally corrected a message for `ONEDPL_USE_AOT_COMPILATION`, because AOT compilation does not depend on OCLOC compiler (only) since #794.

Define missed variables in CMakeLists

---

include/oneapi/dpl/pstl/utils.h
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp

Address another potential issue found by static code analysis: intermediate computations are done in 32 bit while the result is then assigned to 64-bit variables

Ensure absence of overflow due to unintentional use of 32-bit arithmetic

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

What's done:
- fixed compile error for onesweep radix sort for non uint32_t types in the file [esimd_radix_sort_onesweep.h](https://github.com/oneapi-src/oneDPL/pull/947/files#diff-e1ae92ade037e076287bd65fc13b927416746cfda57f50e38ac3161f9dcde285)
```auto p_output = sycl::malloc_device<uint32_t>(__n, __exec.queue());```
-> ```auto p_output = sycl::malloc_device<KeyT>(__n, __exec.queue());```
- added support of all types into onesweep like as ```::std::is_integral_v<KeyT>```
- changed initial value from '''-1''' to ```utils::__sort_identity<KeyT, IsAscending>)```
- renamed some params in ```VectorStore``` functions: ```src``` -> ```dest```
- added test on onesweep sort for ```int``` type on USM shared/device memory

[KT] Add int support for onesweep radix sort

---

include/oneapi/dpl/pstl/utils_ranges.h

Currently, take_view_simple can only create a view up to the first `n - 1` elements of the range. We are extending this to support creating a view over all `n` elements which is consistent with the behavior of `std::ranges::take_view` in C++20.
This PR was identified by and fixes a bug in `reduce_by_segment` where the modified assertion fails when each segment is of size `1`.

Support creating a view over an entire range with take_view_simple

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
test/support/utils_sycl.h

In SYCL 2020, device selectors were changed to use a simpler API that utilized callables to rank devices as integers. It provided sensible defaults to replace the old selectors (e.g., `gpu_selector`) with a new version (e.g., `gpu_selector_v`). In oneDPL, we changed most of the selectors but we did not change the FPGA ones.
This PR replaces the old FPGA selectors with SYCL 2020 compliant versions.
I obtained the LIBSYCL version by finding the commit which deprecated the old FPGA selector https://github.com/intel/llvm/commit/0417651672159f821ba58eeb4b744d46661f867a and noting that the library version at that commit was 6.1.0.

Replace deprecated FPGA selector

---

CMakeLists.txt
cmake/oneDPLWindowsIntelLLVMConfig.cmake
cmake/templates/oneDPLConfig.cmake.in

Increasing minimum required CMake version:
- Windows: 3.20
- Required for baseline CMake support for `icx`, `icx-cl` to allow workarounds to work 
- Linux: 3.11
- Required for CMake support of `icpc` with required C++17 feature 
Adding in minimum CMake requirements for oneDPL via package inclusion (previously none).

Updating CMake minimum required versions

---

test/support/test_macros.h
test/xpu_api/language.support/support.limits/limits/infinity.pass.cpp
test/xpu_api/language.support/support.limits/limits/lowest.pass.cpp
test/xpu_api/language.support/support.limits/limits/max1.pass.cpp
test/xpu_api/language.support/support.limits/limits/quiet_NaN.pass.cpp

For the C++20 `char8_t` type, we only check for presence of the `char8_t` feature macro in our `std::numeric_limits` tests. However, it is necessary to also check for the presence of library support for `char8_t` to ensure that the `std::numeric_limits` specializations are implemented.

Add checks for char8_t library support in numeric limits tests

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

No implementation changes appear necessary, except for onesweep to use the order as designed.
In the test, I enable the possibility to test everything in descending order, off by default. It's similar to other template parameters - WG size, etc. We will need to find out how to test for different parameter values without сombinatorial explosion.

[KT] Support for descending sort order

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h

Fix template params in utils::__order_preserving_cast calls:
- using ``IsAscending``` instead of ```true```

[KT] Fix template params in utils::__order_preserving_cast calls

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

This patch refactors the reduce pattern by:
- Fixed numbers of `__iters_per_work_item` are used independent of the device. This unifies the similar `transform_reduce_known` and `transform_reduce_unknown` structs.
- The sequential kernel was removed since it does not provide significant performance improvements.
- The performance of mid-sized arrays is improved by reducing the `__iters_per_work_item` for the second kernel to the lowest value needed. This better balances the work across work items. If each work item has less than one element to work on, the work group size is further reduced if possible. This lowers the complexity of the work group reduction.
- Improved documentation and naming.

Improve reduce pattern performance with mid-sized inputs

---

test/parallel_api/algorithm/alg.sorting/sort.pass.cpp

In this PR we fix mangled Kernel names in tests:
- error was found at ```test_os=rhel8_compiler=dpcpp_backend=dpcpp_device_type=CPU_std=c++17_cfg=release_unnamed_lambda=OFF_compile_kernel=ON```
- ```cmake -DCMAKE_CXX_COMPILER=dpcpp -DCMAKE_CXX_STANDARD=17 -DONEDPL_BACKEND=dpcpp -DONEDPL_DEVICE_TYPE=CPU '-DCMAKE_CXX_FLAGS=-DTEST_LONG_RUN=1 ' -DCMAKE_BUILD_TYPE=release -DONEDPL_USE_UNNAMED_LAMBDA=OFF .```
Error: ```../include/sycl/handler.hpp:249:7: error: definition with same mangled name '_ZTSN4sycl3_V16detail19__pf_kernel_wrapperIN6oneapi3dpl20__par_backend_hetero18__sort_leaf_kernelIJN9TestUtils18unique_kernel_nameI12test_sort_opIhELm1EEEEEEEE' as another definition```

Fix mangled Kernel names in tests

---

include/oneapi/dpl/pstl/onedpl_config.h
test/support/test_config.h

Adding commit b6ea2df988fd0f5f4ea02b9abc38b42f181a9a11 from #906 into dynamic_selection branch:
Adding checks for the presence of sycl headers prior to enabling sycl backend.
This is required when compilers support -fsycl option and define SYCL_LANGUAGE_VERSION, without making SYCL implementation available in practice.

Adding sycl header check

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

In this PR we add support of ```int16_t``` and ```uint16_t``` into esimd radix sort.
For that we made change in ```one_wg_kernel``` function:
- we replace block of code
```
#pragma unroll
for (uint32_t s = 0; s<PROCESS_SIZE; s+=64){
keys.template select<64, 1>(s) = lsc_slm_block_load<KeyT, 64>(slm_reorder_this_thread+s*sizeof(KeyT));
}
```
to
```
keys = utils::BlockLoad<KeyT, PROCESS_SIZE>(slm_reorder_this_thread);
```
to avoid compile error:
```
../include/sycl/ext/intel/experimental/esimd/memory.hpp:381:3: error: static assertion failed due to requirement '_DS == lsc_data_size::u32 || _DS == lsc_data_size::u64': Transposed load is supported only for data size u32 or u64
```

Implement & test esimd radix sort for int16_t and uint16_t

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h

This PR addresses a clash in kernel names for `__reduce_mid_main_kernel` introduced in #907. We currently use the same value for `__iters_per_work_item1`, which leads to the same name. This can be observed wen compiling with `ONEDPL_USE_UNNAMED_LAMBDA=OFF`.
This fix adds both `__iters_per_work_item` parameters to the kernel name provider to come up with unique names. It further prevents potential issues in the future in case we want to vary `__iters_per_work_item1` for different kernel invocations.

Fix repeated kernel names for__reduce_mid_main_kernel

---

test/parallel_api/ranges/zip_view.pass.cpp

This PR fixes a bug in zip_view.pass.exe on Windows.  
`iota_view` bases its' value type on the first argument,  making an iota with `0L` on Windows results in a 32 signed integer type, which overflows during the test when using the large numbers (designed to test overflow of 32 bit signed types).  This is resolved by explicitly creating a 64 bit integer in the iota creation.

Fix for zip_view test on Windows

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
test/parallel_api/algorithm/alg.sorting/sort.pass.cpp

Our radix sort implementation has been observed to produce incorrect results when performing a descending sort of `int16_t` numbers containing negative values.
The bitwise complement operation adheres to integral promotion rules. In `__order_preserving_cast` of our radix sort, we require a mask of the form 011..11 for the descending case. In order to ensure this, we need the right shift operator to pad with zeros which is only guaranteed when shifting unsigned types. We must add an additional cast to ensure that we are right-shifting an 
unsigned type. This change corrects the observed sorting bug.

Correct radix sort's order preserving cast for descending sort

---

CMakeLists.txt
cmake/templates/oneDPLConfig.cmake.in

Modernize the inclusion of OpenMP in oneDPL's CMake with FindOpenMP, which has the functionality we need as of CMake 3.10 which is less than our required version.
https://cmake.org/cmake/help/latest/module/FindOpenMP.html
This makes #958 unnecessary, and replaces the need for any legacy workaround involving `CMAKE_REQUIRED_LIBRARIES`.
This would also address #960.

Modernize OpenMP CMake inclusion

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

The kernel names for `copy_if` were missing static parameters (e.g., work-group size) and thus multiple kernels were being generated with the same name when compiled with `-fno-sycl-unnamed-lambda`. This PR adds relevant parameters to the kernel names to fix the duplicate naming errors.

Fix duplicate kernel names in copy_if

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_cooperative.h

In this PR we fix syncronization error in cooperative impl of esimd radix sort.
This error have place for 64-bit data types.

[KT] Fix sync error in cooperative impl of esimd radix sort

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

This is a bugfix for #955, which lead to the wrong block size being computed in sycl `radix_sort`.

Fix block size computation bug in sycl radix_sort

---

documentation/library_guide/introduction/onedpl_gsg.rst

It seems that PR #692 and #932 did not update the copy of `documentation/library_guide/introduction/onedpl_gsg.rst`.  This adds the changes from those PRs to this file to synchronize the two instances of `onedpl_gsg.rst`.
The changes include updates to URLs and style guide updates.

[Documentation] Synchronizing both instances of onedpl_gsg.rst

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

Additionally, update TODO comments and enable more test cases with onesweep algorithm.

[KT] Modify process size to fix onesweep with sycl::buffer

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

Additional changes: 
- Thin out types to test due to long compilation time
- Get rid of 'k' suffix in the names of some constants
Unfortunately, the testing has shown that onesweep does not work with 8-bit types.

[KT] Test 8-bit types

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
test/parallel_api/experimental/radix_sort_esimd_histogram.pass.cpp

Additional changes:
- Add a test for the histogram kernel. It can be removed when the kernel is proven to be working with other parameters changed, e.g. `RADIX_BITS`, `WORK_GROUPS` and `WORK_GROUP_SIZE`.
- Rename variables in histogram kernel for better readability.
- Replace `slm_block_load` with `utils::BlockLoad` due to `slm_block_load` limitation (`N * sizeof(Tx) must be 1, 2, 4 or 8 owords long` i.e. it cannot be safely used to load more than 8 * 16 = 128 bytes or 32 `uint32_t` elements).
Currently, the test fails to correctly calculate a histogram for `double` type elements, but it is fixed in #1005.

[KT] Enable support of 64-bit types in histogram kernel

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
test/parallel_api/experimental/radix_sort_esimd.pass.cpp

In this PR we define by default PROCESS_SIZE for ```onesweep``` impl in esimd radix sort as:
- ```384``` for all types with size <= 4 bytes;
- ```192``` for all types with size == 8 bytes;
- enable all types in esimd radix sort test: ```double``` will be included in separate PR.

[KT] Enable all types (excepting double) in esimd radix sort test

---

test/parallel_api/experimental/radix_sort_esimd.pass.cpp

In this PR we using of ```TEST_LONG_RUN``` define in esimd radix sort test test instead of our previous define ```TEST_ALL_INPUTS```

[KT] Using of TEST_LONG_RUN define in test

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_cooperative.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h

In this PR we exclude twice memory allocations on device in onesweep and cooperatiove implementations of esimd radix sort.

[KT] Memory allocation improvements

---

include/oneapi/dpl/internal/scan_by_segment_impl.h

`__diff_type` and `__key_type` in `__sycl_scan_by_segment_impl::operator()` are unused. I've removed them.
Please merge and include in RC because these `using`-s fail [distributed-ranges](https://github.com/oneapi-src/distributed-ranges) project compilation as we treat warnings as errors.
See below `icpx` compilation error messages
```
In file included from /.../include/oneapi/dpl/execution:36:
In file included from /.../include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h:26:
/.../include/oneapi/dpl/internal/scan_by_segment_impl.h:120:15: error: unused type alias '__diff_type' [-Werror,-Wunused-local-typedef]
using __diff_type = oneapi::dpl::__internal::__difference_t<_Range1>;
^
/.../include/oneapi/dpl/internal/scan_by_segment_impl.h:121:15: error: unused type alias '__key_type' …
```

[oneDPL] removed unused types from __sycl_scan_by_segment_impl

---

include/oneapi/dpl/internal/async_impl/glue_async_impl.h
test/parallel_api/experimental/asynch.pass.cpp

`reduce_async` function with `binary_op` parameter was ignoring the parameter and always used `std::plus`.
I exposed the issue by a test and made a fix.
Please merge this bugfix and include in next RC, as the issue fails distributed-ranges project code (see `inclusive_scan` implemented in https://github.com/oneapi-src/distributed-ranges/pull/349)

[oneDPL][async] fixed bug with reduce_async ignoring __binary_op parameter

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

A macro _ONEDPL_RADIX_WORKLOAD_TUNING enables following workload tunning:
//To achieve better performance number of segments and block size are variated depend on data size (32bits):
//1. 32K...512K  - number of segments is increased up to 8 times
//2. 512K...2M   - number of segments is increased up up 4 times
//3. 2M...16M... - work-group size (count phase) is increased up to 128

[oneDPL] radix sort: workload optimization

---

include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/reduce_by_segment_impl.h
include/oneapi/dpl/internal/scan_by_segment_impl.h

Static analysis tools run since #862 and #608 were merged have identified more cases where variables were forwarded and then used later in the code.

Do not forward or move variables that are used later in the code

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h

In this PR we implement work with accessors in ```oneapi::dpl::experimental::esimd::impl::utils::scatter``` and ```oneapi::dpl::experimental::esimd::impl::utils::gather``` functions for 8-byte data types.

[KT] Support work with accessors in scatter and gather functions for 8-byte data types

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h

In this PR we fix compile error in ```BlockLoad``` function for different sizes in ```N``` template param and ```sizeof<T>``` values.
The source compile error happens in this function for ```T``` as ```char``` type and ```int N``` as ```96``` value.
The source compile error was:
```
include/sycl/ext/intel/experimental/esimd/common.hpp:116:3: error: static assertion failed due to requirement '24 == 1 || 24 == 2 || 24 == 3 || 24 == 4 || 24 == 8 || 24 == 16 || 24 == 32 || 24 == 64': Unsupported vector size
static_assert(VS == 1 || VS == 2 || VS == 3 || VS == 4 || VS == 8 ||
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/sycl/ext/intel/experimental/esimd/memory.hpp:563:11: note: in instantiation of function template specialization …
```

[KT] Fix BlockLoad compile errors for different sizes N

---

.github/workflows/ci.yml

This PR fixes most possible cases when CI provides "green" status despite of finishing with errors. This is a continuation of #886. 
Example:
This happens because of default behaviour of `shell: cmd`, which is described in https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

[CI] Fix execution status of Windows CI jobs

---

integration/modulefiles/dpl

Such restructuring is expected in other oneAPI components; this change is done for alignment. 
There are improvements compared to the unchanged script: 
- simplified structure, 
- description of the library, 
- set `CMAKE_PREFIX_PATH` (for cmake) and `PKG_CONFIG_PATH` (for pkg-config).

[Integration] Update modulefile structure

---

include/oneapi/dpl/internal/dynamic_selection_impl/concurrent_queue.h
test/support/concurrent_queue.h

Used a std::deque instead of std::queue.

[Dynamic Selection] Make internal implementation of concurrent queue generic

---

integration/env/vars.sh

Cherry pick of #954 to the dynamic selection branch to add CMake files into the CMake searchable path after sourcing `vars.sh`.

[Dynamic Selection] Cherry-pick of "Adding to CMAKE_PREFIX_PATH in vars.sh (#954)"

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
test/CMakeLists.txt
test/kt/CMakeLists.txt
test/kt/esimd_radix_sort.cpp

Improve the test system: test different DataPerWorkItem and WorkGroupSize
Additionally, names of some internal template parameters have been aligned with the public ones.

[KT] Pass template parameters to the implementations

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h

In this PR we create and use common defines in esimd radix sort :
- ```constexpr int DATA_PER_STEP = 16;``` - use it instead of const ```16``` in code;
- ```namespace __dpl_esimd_ns = sycl::ext::intel::esimd;``` - use it instead of namespace names  ```__ESIMD_NS``` an ```sycl::ext::intel::esimd``` in code;
- ```namespace __dpl_esimd_ens = sycl::ext::intel::experimental::esimd;``` - use it instead of namespace names  ```__ESIMD_ENS``` an ```sycl::ext::intel::experimental::esimd``` in code;

[KT] Create and use common defines in esimd radix sort

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
test/kt/CMakeLists.txt
test/kt/esimd_radix_sort.cpp

Pin histogram kernel configuration, because it is not as versatile as onesweep kernel.  This is needed to support more WorkGroupSize options.

[KT] Extend supported WorkGroupSize

---

include/oneapi/dpl/internal/dynamic_selection.h
include/oneapi/dpl/internal/dynamic_selection_impl/policy_traits.h
include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy_impl.h
include/oneapi/dpl/internal/dynamic_selection_impl/static_policy_impl.h
include/oneapi/dpl/internal/dynamic_selection_impl/sycl_scheduler.h
test/support/inline_scheduler.h
test/support/test_ds_utils.h

1.Type traits defined by policies 
2. Type traits defined by scheduler
3. Added a policy traits class
4. Made changes to use policy_traits<Policy>::trait_name where its needed
5. PR does not add the submission_group_type class, since it makes sense to add it after #1039 is merged.

[Dynamic Selection] Introducing policy traits

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h

In this PR we made next things:
- remove some unused local variables;
- remove some non modified zero-initialized local variables;
- declare not changed local variables and class members as ```const```;
- replaces ```lsc_gather``` calls to ```utils::gather```;
- replace ```lsc_block_store``` calls to ```utils::BlockStore```;

[KT] Esimd radix sort code cleanup

---

include/oneapi/dpl/internal/dynamic_selection.h
include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy_impl.h
include/oneapi/dpl/internal/dynamic_selection_impl/static_policy_impl.h
include/oneapi/dpl/internal/dynamic_selection_impl/sycl_scheduler.h
test/support/test_ds_utils.h

Removing free functions for set_universe and get_universe size
The set_universe function in sycl_scheduler, round_robin_policy and static policy still exists and needs to be replaced in future PRs

Removing free functions for set_universe and get_universe size

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h

In this PR we control correctness of steps in 'for' loops in compile-time by ```static_assert``` instructions.

[KT] Control correctness of steps in 'for' loops in compile-time

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h

In this PR we make refactoring of ```radix_sort_onesweep_slm_reorder_kernel::UpdateGroupRank``` functions:
- remove some duplicated code before the ```for``` loop;
- expand ```for``` loop  range.

[KT] UpdateGroupRank refactoring in esimd radix sort

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h

In this PR we remove extra namespace names, because we are already inside required namespace:
- ```oneapi::dpl::experimental::kt::esimd::impl::``` -> ```impl::```

[KT] Remove extra namespace names

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h

In this PR we made next changes:
- rename: ```BlockLoad(uint32_t slm_offset)``` to ```BlockLoadSlm(uint32_t slm_offset)```;
- rename: ```BlockStore(uint32_t slm_offset, __dpl_esimd_ns::simd<T, N> data)``` to ```BlockStoreSlm(uint32_t slm_offset, __dpl_esimd_ns::simd<T, N> data)```
- in ```BlockStore``` insert additional static_assert to check dest size ```N```;
- change ```enable_if``` condition in ```BlockStore``` function;
- rename: ```lsc_op_block_size_rounding``` to ```lsc_slm_block_size_rounding```;
-

[KT] Improvement of BlockStore functions

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h

In this PR we improve memory management in esimd radix sort (onesweep):
- we will call ```sycl::free``` function from separate Kernel in which we create special ```host_task``` and call ```sycl::free```.
**Pro**:
- we make really asynchronous esimd ```radix_sort``` implementation without ```wait()``` calls inside.
**Contra**:
- we will have memory leak in exceptional case.

[KT] Async free memory

---

include/oneapi/dpl/internal/dynamic_selection.h
include/oneapi/dpl/internal/dynamic_selection_impl/dynamic_load_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h
test/parallel_api/dynamic_selection/sycl/test_dynamic_load_policy_sycl.pass.cpp
test/parallel_api/dynamic_selection/test_dynamic_load_policy_inline.pass.cpp
test/support/inline_backend.h
test/support/test_ds_utils.h
test/support/test_dynamic_load_utils.h
test/support/test_dynamic_selection_utils.h

1. Added a host task in the sycl_backend
2. Added the dynamic load policy
3. Added tests for dynamic_load_policy_sycl (Note : the test for group submission may fail just because of the nature of host task and dynamic_load_policy)
4. Added tests for dynamic_load_policy_inline
5. Added test/support/test_dynamic_load_utils.h for a comprehensive testing, the older files test/support/test_dl_utils.h exists to run round_robin and fixed_policy tests and should be removed

[Dynamic Selection] Dynamic Load policy with host_task and tests

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

[onedpl] Merge Path algorithm for oneDPL merge algorithm (SYCL backend).
This is a new implementation of the oneDPL merge algorithm  (merging two sorted ranges) based on new approach known as Merge Path parallel merging. It gives a significant speed up comparing to the current oneDPL implementation.
The main idea  - each work-item is searching for the start points in range 1 and range 2. After each work-item does M steps of sequential merging, where M = (N1+N2) / p, where  p -  number of threads. So, we have got well balanced parallel merging.

[onedpl] Merge Path algorithm for oneDPL merge algorithm (SYCL backend)

---

documentation/library_guide/introduction.rst

The experimental ranges support in oneDPL includes code that throws exceptions.  In order to avoid compilation errors on Windows users must add '/EHsc' to their compile line for each translation unit.

Adding note about required option for Windows compilation

---

include/oneapi/dpl/internal/reduce_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

`get_pointer` methods for buffer and local accessors recently became deprecated according to SYCL 2020 specification revision 8. 
You can find the information about the deprecation in [sycl-2020.pdf](https://github.com/oneapi-src/oneDPL/files/12422386/sycl-2020.pdf) (revision 8 is not published, this file has been generated from the latest sources on https://github.com/KhronosGroup/SYCL-Docs/tree/SYCL-2020/master). See Table 51 (Member functions of the accessor class) and Table 72 (Member functions of the local_accessor class). 
These APIs are already deprecated in the compiler in favor of `get_mult_ptr` (https://github.com/intel/llvm/pull/10174). This results in a warning, e.g:
> parallel_backend_sycl.h:634:32: warning: 'get_pointer' is deprecated: local_accessor::get_pointer() is …

Fix warning: 'get_pointer' is deprecated

---

include/oneapi/dpl/pstl/onedpl_config.h
include/oneapi/dpl/pstl/parallel_backend.h

The PR has the following intention:
- Separate logic of finding available parallel backends from logic of their selection.
- Stop compilation if a user selected a not available backend.
Additional changes:
- Availability of OpenMP backend now is verified by both compiler support (via `_OPENMP` support as before) and heaving `<omp.h>` header. Having compiler support indicated by `_OPENMP` is not enough, because the headers may be missing. They, for example, are provided separately on Ubuntu 20.04 as a part of `libomp-dev` package.
- Availability of SYCL backend now is also verified by both compiler (as before) support and having `sycl.hpp` header. 
The PR was inspired by PR #524 and by this [discussion](https://github.com/oneapi-src/oneDPL/pull/524#discussion_r831326254).

Check availability of parallel backends

---

include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
test/parallel_api/dynamic_selection/sycl/test_auto_tune_policy_sycl.pass.cpp
test/parallel_api/dynamic_selection/test_auto_tune_policy_inline.pass.cpp

Do not consider first timing in auto-tune so that any JIT compilation overhead is ignored in decisions.

[Dynamic Selection] Auto-tune ignores 1st timing

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

Switching to a ternary conditional operator in the reduce function of `min_element` as introduced in #1026 results in slowdowns on PVC. This reverts the change to the lambda.

Revert ternary conditional operator in min_element introduced in #1026

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h

[oneDPL] radix sort: one work group optimization: move counters to SLM for 4K..16K.
When SLM is not enough for counters + temporary buffer, we keep SLM just for the counters, for the values - a buffer in the global memory.

[oneDPL] radix sort: one work group optimization: counters to SM

---

include/oneapi/dpl/internal/dynamic_selection.h
include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/fixed_resource_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/policy_traits.h
include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy.h

1. std::decay<T>::type to std::decay_t<T>
2. Fixed definition of submit to not use policy's function directly
3. Checking use of forwards in submit and submit_and_wait
4. move internal namespace classes into auto_tune_policy as private types
5. change auto_tune to use steady_clock

[Dynamic Selection] Addressing comments for dynamic_selection.h and auto_tune

---

include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
test/parallel_api/dynamic_selection/sycl/test_auto_tune_policy_sycl.pass.cpp
test/parallel_api/dynamic_selection/sycl/test_dynamic_load_policy_sycl.pass.cpp

1. Added guards back to auto_tune policy
2. Added exceptions to auto-tune and dynamic_load sycl tests in case the sycl::queue cannot be created

[Dynamic Selection] Added exceptions to tests

---

test/parallel_api/dynamic_selection/sycl/test_fixed_resource_policy_sycl.pass.cpp
test/parallel_api/dynamic_selection/sycl/test_round_robin_policy_sycl.pass.cpp

To make sure the tests pass even if the gpu_queue is absent

Removed offset of 2

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/numeric_impl.h
include/oneapi/dpl/pstl/unseq_backend_simd.h

In this PR we fix some places where ```std::plus<T>``` used ```without std::plus<void>```

Fix places where std::plus<T> used without std::plus<void>

---

include/oneapi/dpl/dynamic_selection
include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/dynamic_load_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/fixed_resource_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h
include/oneapi/dpl/internal/dynamic_selection_traits.h

For the std includes, like agreed on we include all the std headers at all levels irrespective of whether they might be in parent files or not.

fixing includes

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/onedpl_config.h

This patch aims at reducing the required transfer times in the family of reduce algorithms for copying the result back to the host.
The current mainline version uses a single value buffer that is wrapped in a future-like object. This patch introduces a future-like class for reduction results based on USM host memory. This eliminates the L0 call to `zeCommandListAppendMemoryCopy` and directly transfers the result instead. This improves the transfer times significantly with great runtime benefits for smaller input arrays.

Switch to USM Host Memory for Reduction Result

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h

This PR fixes a duplicate kernel name bug that arose with the recent changes to the one workgroup sort implementation. We now have three unique kernel types based on available SLM that each require a name: a case where we use an SLM buffer and SLM counter, no SLM buffer and SLM counter, and no SLM used at all. The current implementation only provides two kernel names which results in a compile error when compiled without unnamed lambdas enabled. This fix adds a new kernel name for the case where we have no SLM buffer and an SLM counter.

[oneDPL] Radix sort one wg: Add unique kernel name for case that partially uses global memory

---

include/oneapi/dpl/internal/reduce_by_segment_impl.h
include/oneapi/dpl/internal/scan_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

The generated kernel name should include `ExecutionPolicy` template parameter among others to avoid the conflict.
It turns out, all other (besides fixed) places take `ExecutionPolicy` into account implicitly via Callable type.
Example of "capturing" the policy via Callable type: `using _Functor = unseq_backend::walk_n<_ExecutionPolicy, _BinaryOperation2>;`
When the `ExecutionPolicy` is not taken into account the example of different instantiations of the function the produces the same kernel name is with `device_policy` and with `const device_policy`
The fix is temporary, due to time constraints. Need to think if we can redesign the backend to never accept the policy by forwarding reference

Fix generated kernel name to consider ExecutionPolicy

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h

Introduced in https://github.com/oneapi-src/oneDPL/pull/1057

[KT] Fix an error in the async free memory in esimd radix sort

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
test/parallel_api/algorithm/alg.merge/merge.pass.cpp

[oneDPL] + a fix for the oneDPL merge (merge Path).
There was a kind of mess with ranges order to be merged, r1 and r2. 
A "merge" matrix was define for r2 and r1, but real merging for r1 and r2.
Actually a "merge" matrix has been "transposed" for the fix.

[oneDPL] + a fix for the oneDPL merge (merge Path)

---

examples/random/src/main.cpp

More details about specification and compiler changes which led to this PR are in #1094 description.

[Examples] Fix warning: 'get_pointer' is deprecated

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h
include/oneapi/dpl/experimental/kt/kernel_param.h

oneDPL code uses snake_case for variables (even for constexpr ones), function names; PascalCase for types. 
The names are preserved for ESIMD function wrappers to be aligned with ESIMD.

[KT] Align names with the rest oneDPL code

---

test/xpu_api/random/device_tests/common_for_device_tests.h
test/xpu_api/random/statistics_tests/bernoulli_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/exponential_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/extreme_value_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/geometric_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/lognormal_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/normal_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/uniform_int_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/uniform_real_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/weibull_distribution_test.pass.cpp
test/xpu_api/random/template_tests/discard_block_std_template_test.pass.cpp
test/xpu_api/random/template_tests/linear_congruential_std_template_test.pass.cpp
test/xpu_api/random/template_tests/subtract_with_carry_std_template_test.pass.cpp

#1094 updated oneDPL headers to remove usage of the get_pointer methods for buffer and accessors. This PR updates the random number generator tests to remove use of the accessor get_pointer method.

Updating RNG tests to fix warning of deprecated get_pointer interface.

---

test/support/utils_invoke.h
test/support/utils_sycl.h

C++ specification says:
> If an inline function or variable (since C++17) with external linkage is defined differently in different translation units, the behavior is undefined.
`get_test_queue()` uses `my_queue`, which is linked internally and thus has different addresses in each TU.

[Tests] Fix UB in the tests (may happen with multiple TUs)

---

include/oneapi/dpl/pstl/ranges/nanorange.hpp

I guess, this issue was introduced at some early stage of adaptation of `nanorange.cpp`. It is absent in the original repository.

Fix clang-format issue in nanorange

---

test/xpu_api/random/device_tests/common_for_device_tests.h
test/xpu_api/random/statistics_tests/bernoulli_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/exponential_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/extreme_value_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/geometric_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/lognormal_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/normal_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/uniform_int_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/uniform_real_distribution_test.pass.cpp
test/xpu_api/random/statistics_tests/weibull_distribution_test.pass.cpp
test/xpu_api/random/template_tests/discard_block_std_template_test.pass.cpp
test/xpu_api/random/template_tests/linear_congruential_std_template_test.pass.cpp
test/xpu_api/random/template_tests/subtract_with_carry_std_template_test.pass.cpp

Example of an error:
```
oneDPL/test/xpu_api/random/statistics_tests/weibull_distribution_test.pass.cpp:76:21: error: no matching member function for call to 'store'
...
bin/compiler/../../include/sycl/types.hpp:1033:8: note: candidate template ignored: could not match 'multi_ptr<DataT, Space, DecorateAddress>' (aka 'multi_ptr<float, Space, DecorateAddress>') against 'pointer' (aka 'float *')
```
`__dpl_sycl::__get_accessor_ptr` returns a raw pointer, but `sycl::vec::store` uses `sycl::multi_ptr`. Raw pointer cannot be implicitly converted to `sycl::multi_ptr`. 
Also,  `__dpl_sycl::__get_accessor_ptr` is an internal oneDPL API and should not be used in the tests.
The PR has been verified with:
- Intel(R) oneAPI DPC++/C++ Compiler 2022.2.1
- Intel(R) oneAPI DPC++/C++ Compiler 2023.2.0 …

[Tests] Fix xpu_api/random tests

---

test/parallel_api/dynamic_selection/sycl/test_auto_tune_policy_sycl.pass.cpp

Reduce the number of iterations and skip the offload completely for the "fast" case.

[Dynamic Selection] reduce time spent in auto_tune test for SYCL

---

src/CMakeLists.txt

Flags that were not added:
* `-ipo` caused link-time issues on `icpx` because some required library not found in the compiler package. Investigation required.
* `-fsanitize=cfi` causes a warning that the option is ignored as unsupported for SPIRV.
* `-pie` causes a warning that the argument is unused
No performance degradations detected

[pstl-offload] Add SDL flags into libpstloffload build

---

include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
include/oneapi/dpl/pstl/numeric_impl.h
include/oneapi/dpl/pstl/unseq_backend_simd.h
include/oneapi/dpl/pstl/utils.h

On compilers in which we enable the `__simd_scan` codepath (such as `icpc 2021.8`), our `scan.pass` test cases have been failing for `unseq` and `unseq_par` host policies. In particular, the specific cases that test in-place scans fail. This is due to the following restriction in the [OpenMP specification:](https://www.openmp.org/spec-html/5.0/openmpsu45.html)
```
"Intra-iteration dependences from a statement in the structured block preceding a scan directive to a statement in the 
structured block following a scan directive must not exist, except for dependences for the list items specified in an 
inclusive or exclusive clause."
```
When an in-place scan is performed, the `__first` and `__result` iterators in [__simd_scan](https://github.com/oneapi-src/oneDPL/blob/0b57a685568ea1ccfab50ad2 …

Add check for in-place scan before invoking __simd_scan

---

include/oneapi/dpl/pstl/glue_memory_impl.h

This is a fix after #1182 PR to make these changes valid for a version where PSTL is used (upstream). It follows https://github.com/oneapi-src/oneDPL/pull/1182#discussion_r1329945495 advice.

Use PSTL-prefixed macro along with ONEDPL one

---

.github/workflows/ci.yml
include/oneapi/dpl/pstl/utils_ranges.h

This PR fixes the clang-format to compare against the actual `git merge-base` or "nearest common ancestor", rather than the current head of the target branch when the PR was created (`github.event.pull_request.base.sha`).
I've branched this commit off 2d943a309  (about 10 commits behind current HEAD).  There are clang-formatting issues with commits which have since been merged into main which would dirty this PR's report without this fix, but instead the clang-format check passes.
To prove that the clang-format check still accurately detects real formatting issues with the PR, please look at the following CI action link:
https://github.com/oneapi-src/oneDPL/actions/runs/6306998877/job/17122994749?pr=1205
I injected an intentional error into `utils_ranges.h`, and have since reverted it.

Clang format merge-base fix

---

.github/workflows/ci.yml
.gitignore

This PR fixes the clang-format github action to handle both `pull_request` event and `push` event appropriately, as either can trigger this workflow.  
When one is the trigger, the other's variables are the empty string.  For a `push` event, `github.event.pull_request.[head,base].sha` are the empty string, resulting in an error from the `git merge-base` call unless we branch and set that event up accordingly.
Without this PR, a passing clang-format CI for the pull request will fail the clang-format CI when run after merge (as the merge triggers a `push` event).
Also added in this change is that clang-format checks will only only be processed for `pull_request` and `push` events.  Currently these are the only workflows enabled by this test, but if any other events are added, they will omit …

clang-format fix for github push actions (post merge to main)

---

.github/workflows/ci.yml

Yet another fix for clang format post-merge.  This now gets the syntax for the `push` event commit hashes correct.
It also cleans up the code a little.
Here is the documentation:
https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
This lists the structure of the event objects for `pull_request` and `push`, and supports the identifiers used here.
The link below supports the syntax to allow the code cleanup.  Specifically "Note: empty string returns 0." and their example for ternary below.
https://docs.github.com/en/actions/learn-github-actions/expressions#operators

clang-format fix for push event

---

test/parallel_api/dynamic_selection/sycl/test_internal_sycl_scheduler.pass.cpp

The test `test_internal_sycl_scheduler.pass` fails to compile with the nightly intel/llvm compiler because the `TEST_DYNAMIC_SELECTION_AVAILABLE` macro evaluates to false, but some of the test cases are defined outside of the if guard.
This PR moves the affected tests within the if macro.

Fix compile error in test_internal_sycl_scheduler.pass with nightly compiler

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

In this PR we fix `dpl` namespace name to `oneapi::dpl` to be consistent with other places in the code.

Fix `dpl` namespace name to `oneapi::dpl`

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

As discussed at https://github.com/oneapi-src/oneDPL/pull/1197#discussion_r1348717655
this `class __buffer_impl` based on USM memory is not required anymore as unused in oneDPL code and has been deleted in this PR:
```C++
// impl for USM pointer
template <typename _ExecutionPolicy, typename _T, typename _BValueT>
class __buffer_impl<_ExecutionPolicy, _T, _BValueT*>
{
// ...
};
```
Also in this PR we simplify the definitions of `__internal::__buffer_impl` and `__buffer` [alias template](https://en.cppreference.com/w/cpp/language/type_alias):
```C++
// impl for sycl::buffer<...>
template <typename _ExecutionPolicy, typename _T>
class __buffer_impl
{
private:
using _Container = sycl::buffer<_T>;
using __container_t = typename __local_buffer<_Container>::type;
// ....
};
template <typename …
```

Remove usm based `class __buffer_impl'

---

.github/workflows/ci.yml

This PR changes the clang-format check to only run on `pull_request` events (commits to an active pull request or creation of one).  The CI will skip the job for post-merge push events to main.
A couple previous PRs (#1207 #1211) attempted to fix the post-merge version of this clang-format job without success, after some operations were added in #1205 requiring specific git commit hashes which broke it post-merge.  With additional thought, it seems that this job is unnecessary in the context of the post-merge CI action.   In fact, the way it was written, before #1205 (and even before #715) it would just pass unconditionally post-merge because the diff would be empty.
The clang-format check is a tool to help us craft better PRs, so let us run it in that context, but not otherwise.

Remove clang-format check from post-merge action

---

include/oneapi/dpl/pstl/onedpl_config.h
include/oneapi/dpl/pstl/pstl_config.h

It's been verified that the issue (`icx: error: clang frontend command failed...`) does not reproduce with the most recent internal build for the upcoming release of Intel(R) oneAPI DPC++/C++ Compiler.

Limit _PSTL_ICPX_OMP_SIMD_DESTROY_WINDOWS_BROKEN

---

test/parallel_api/memory/specialized.algorithms/uninitialized_fill_destroy.pass.cpp

In `uninitialized_fill_destroy.pass.cpp`, we currently allocate memory into a smart pointer to manage its lifetime. However, there are two issues with this: since the memory is allocated with `new` it is already initialized when it is passed to the test function, and the test object's destructor will be called a second time after the `std::destroy` test before deallocation. This has crashes in this test on certain OSs (certain test configs with MacOS) and can be observed with address sanitizers elsewhere.
This fix manually allocates the memory with `malloc` so it is passed uninitialized to the test and manually deallocates it with `free`.

[oneDPL] [test] Fix heap use after free in uninitialized_fill_destroy.pass

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

Discussions with @SergeyKopienko and changes in #1197 brought up the ambiguity of the naming of the `__storage` struct that supports USM host memory or a buffer. This feature was added in #874. This PR proposes to rename `__storage` to `__usm_host_or_buffer_storage` to clarify what it entails. Consecutively, the used `__accessor` struct should be renamed to `__usm_host_or_buffer_accessor`. @SergeyKopienko proposed `__kernel_result_storage` as an alternative name to clarify its current use as a small return storage. We are open to other suggestions as well.

Clarify naming of USM host or buffer storage

---

include/oneapi/dpl/pstl/utils_ranges.h

[oneDPL][ranges] + a minor change for value_type definition.
Some standard views/genrators (example iota_view) doesn't have `value_type` type.
Our internal "views" are relied on that type of a base range. 
The patch fixes it by introducing another definition  (oneDPL internal) of "value_type".

[oneDPL][ranges] + a minor change for value_type definition

---

test/pstl_offload/headers/headers.standard/requires_header_presence/numbers.pass.cpp
test/xpu_api/iterators/predef.iterators/move.iterators/move.iter.ops/move.iter.op.incr/post_incr.pass.cpp
test/xpu_api/iterators/predef.iterators/move.iterators/move.iterator/types2.pass.cpp

Fix minor C++20 compilation issues in newly added `dpl::move_iterator` tests and one PSTL offload test:
* Rename `phi_v` to `phi` in `numbers.pass.cpp` because `phi_v` requires a template argument. Move the test into `requires_header_presence` directory to enable CMake check for C++20 header file before compiling.
* Change `post_incr.pass.cpp` because starting from C++20, post increment operator in `std::move_iterator` returns `void` for an iterator that is not forward iterator.
* Add definition of dereference operator for `DummyIt` in types test - since C++20 to satisfy constraints for `std::iter_rvalue_reference_t` that is used to determine `std::move_iterator::reference` type.

Fix C++20 compilation issues in tests

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/onedpl_config.h

This PR updates how `_ONEDPL_SYCL_INTEL_COMPILER` is not defined for the open source DPC++ compiler this means that for `has_known_identity` incorrectly evaluates to false in all cases.
I propose using the `SYCL_IMPLEMENTATION_INTEL` macro instead of `_ONEDPL_SYCL_INTEL_COMPILER` which is defined in the SYCL specification and is used by the open source compiler. This change is not for performance reasons but instead having the expected and correct code path used on opensource DPC++.

Use SYCL_IMPLEMENTATION_INTEL macro

---

include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h
test/kt/esimd_radix_sort.cpp

This PR aims to solve several problems:
- Support of more GPUs: current impl limits SLM to max available on Intel® Data Center GPU Max. The limit might be different on other GPUs.
- Performance: hardcoding the SLM allocation to the max amount limits occupancy. Especially with smaller `WorkGroupSize` template values. 
- Usage: issues with the use of more SLM than the max hardcoded amount are hard to debug. 
This is a draft until full testing passes. The current results are:
```
92% tests passed, 15 tests failed out of 193
The following tests FAILED:
344 - esimd_radix_sort_by_key (Subprocess aborted)
360 - esimd_radix_sort_char_dpwi256_wgs64 (Failed)
375 - esimd_radix_sort_char_dpwi512_wgs32 (Failed)
376 - esimd_radix_sort_char_dpwi512_wgs64 (Failed)
392 - …
```

[KT] Limit SLM allocation to the used amount

---

include/oneapi/dpl/pstl/execution_impl.h
include/oneapi/dpl/pstl/experimental/internal/for_loop_impl.h
include/oneapi/dpl/pstl/iterator_defs.h

- using `std::conditional_t` instead of `typename std::conditional<...>::type`;
- using `__is_random_access_iterator_v` instead of `__is_random_access_iterator<>::value`;
- using `::std::iterator_traits` instead of `oneapi::dpl::__internal::__iterator_traits`;
- remove `oneapi::dpl::__internal::__iterator_traits` as unused anymore;
- define and using `__is_forward_iterator_v` :
```C++
template <typename... _IteratorTypes>
inline constexpr bool __is_forward_iterator_v = __is_forward_iterator<_IteratorTypes...>::value;
```

Code improvements in tag dispatch prototype for current code base

---

include/oneapi/dpl/experimental/kernel_templates
include/oneapi/dpl/experimental/kt/gpu_radix_sort.h

This is the first PR for the pure SYCL onesweep radix_sort implementation.
I am adopting a similar PR strategy as `esimd-radix-sort`: incremental PRs into the feature branch `gpu-radix-sort`, followed by eventual merging into `main`.
This PR simply declares the `oneapi::dpl::experimental::kt::gpu::radix_sort` function signatures. It copies the equivalent declarations for `oneapi::dpl::experimental::kt::esimd::radix_sort`, though we omit `radix_sort_by_key` since this is not yet implemented.

Basic structure for kt::gpu::radix_sort

---

include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_utils.h

Inlining must be guaranteed according to [Static allocation of SLM using slm_init function](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_esimd/sycl_ext_intel_esimd.md#static-allocation-of-slm-using-slm_init-function):
> The call of slm_init must be placed in the beginning of the kernel. If slm_init is called in some function 'F' called from kernel, then inlining of 'F' to the kernel must be forced/guaranteed.
This will help to avoid this issue (usually happens with -O0/-O1/-g compile options):
> LLVM ERROR: GenXLowering failed for: <  
call void @llvm.genx.slm.init(i32 %globalOrPrivateLoad)>: SLM init call is supported only in kernels

[KT] Force inlining of ESIMD kernel callables 

---

documentation/library_guide/introduction.rst

Added 2 new long-term known limitations introduced in oneDPL 2022.3.
They are duplicated in oneDPL 2022.3 release notes for users notification.

[DOC] Add 2 new known limitations for oneDPL 2022.3 documentation

---

include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h

`ResetBinCounters` is removed. `RankSLM` does the same, but without using fence which is unnecessary as well.
`bins` are not changed, so the second calculation is not necessary.

[KT] Remove non-used operations from onesweep kernel

---

test/support/utils.h

Not every type is printable. This reverts the change done in `esimd_radix_sort`.

[KT] Revert test change

---

include/oneapi/dpl/pstl/iterator_defs.h
include/oneapi/dpl/pstl/utils.h

In this PR we remove implementations of `struct __make_void_type` and `__void_type` from oneDPL code
and replace it' usage to [std::void_t](https://en.cppreference.com/w/cpp/types/void_t) (since C++17)

Replace `__void_type` to `std::void_t` as supported since C++17

---

include/oneapi/dpl/pstl/tuple_impl.h
include/oneapi/dpl/pstl/utils.h

In this PR we remove implementations of `struct __conjunction` from oneDPL code
and replace it' usage to [std::conjunction](https://en.cppreference.com/w/cpp/types/conjunction) (since C++17)
Looks like ourself implementation of `struct __conjunction` have required in oneDPL code when we supported C++11 and C++14 standards. But now our minimal supported standard is C++17.

Replace `struct __conjunction` to `std::conjunction` as supported since C++17

---

documentation/release_notes.rst

Add new known issue about std::reduce on GPU for 64-bit data types with std::multiplies operation

std::reduce new known limitation

---

test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp

Adding `TestUtils::get_test_queue()` for queue creation.

Fix queue creation for reduce_by_segment.pass

---

.github/workflows/ci.yml
include/oneapi/dpl/pstl/glue_algorithm_defs.h

This change cancels all existing workflows queued or actively running for the same PR, in favor of only testing the most recent commit.
People need to be aware that this is being changed.  As it stands there is no way to turn this off via a commit message.

Cancel existing workflows for PR when new commit is pushed

---

include/oneapi/dpl/experimental/kernel_templates
include/oneapi/dpl/experimental/kt/gpu_radix_sort.h
include/oneapi/dpl/experimental/kt/internal/gpu_radix_sort_dispatchers.h

This is the 2nd PR for the pure SYCL onesweep radix_sort implementation.
This PR builds on top of (and depends on) #1241, adding dispatcher declarations and `radix_sort` implementations.

Dispatcher decls for kt::gpu::radix_sort

---

include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/utils_ranges.h
test/kt/esimd_radix_sort_by_key.cpp

Also:
- The remaining onesweep kernel has been refactored to highlight steps of the algorithm.
- Unroll pragma has been replaced with the internal macro.
- Some typos have been corrected

[KT] Merge key and key-value onesweep kernels

---

test/support/test_config.h

This PR updates the test macro that excludes compilation of code that crashes the compiler during optimization in `reduce_by_segment.pass`.

Exclude reduce_by_segment test case that crashes compiler

---

test/xpu_api/utilities/function.objects/negators/binary_negate.pass.cpp
test/xpu_api/utilities/function.objects/negators/not1.pass.cpp
test/xpu_api/utilities/function.objects/negators/not2.pass.cpp
test/xpu_api/utilities/function.objects/negators/unary_negate.pass.cpp
test/xpu_api/utilities/function.objects/refwrap/weak_result.pass.cpp
test/xpu_api/utilities/meta/meta.trans/meta.trans.other/common_type.pass.cpp
test/xpu_api/utilities/meta/meta.trans/meta.trans.other/invoke_result.pass.cpp
test/xpu_api/utilities/meta/meta.trans/meta.trans.other/result_of11.pass.cpp
test/xpu_api/utilities/meta/meta.unary/meta.unary.prop/is_literal_type.pass.cpp

In this PR we fix tests from `test/xpu_api` with removed in C++20 functional: simple run these tests only for C++17.
All errors fixed in this PR were introduces into oneDPL tests during import new tests in last month.

Fix tests from `test/xpu_api` with removed in C++20 functional

---

test/CMakeLists.txt
test/support/test_config.h
test/xpu_api/containers/sequences/array/array.special/swap1.pass.cpp
test/xpu_api/containers/sequences/array/array.swap/swap.pass.cpp
test/xpu_api/iterators/predef.iterators/move.iterators/move.iter.ops/move.iter.op.incr/post_incr.pass.cpp
test/xpu_api/utilities/meta/meta.unary/meta.unary.prop/is_polymorphic.pass.cpp

In this PR we fix some new errors :
- switch off checked iterators under MSVC for folder 'iterators/iterator.primitives|test/xpu_api';
- add broken test macro for array swap in two tests;
- fixed test with 'C++20' concept usage;
- fixed an error with `class Final final {};` usage as Kernel name for all version of Intel® C++ Compiler before `2024.0`

Fix tests from `test/xpu_api`

---

test/xpu_api/utilities/meta/meta.trans/meta.trans.other/underlying_type.pass.cpp

Error was found in the test `test/xpu_api/utilities/meta/meta.trans/meta.trans.other/underlying_type.pass.cpp`
on configuration
``test_os=rhel8_compiler=icpxrelease_backend=dpcpp_device_type=CPU_std=c++17_cfg=release_unnamed_lambda=ON_compile_kernel=ON`
```C++
In file included from /test/xpu_api/utilities/meta/meta.trans/meta.trans.other/underlying_type.pass.cpp:18:
In file included from /include/oneapi/dpl/type_traits:20:
/../../../../include/c++/8/type_traits:2002:15: error: only enumeration types have underlying types
2002 |       typedef __underlying_type(_Tp) type;
|               ^
test/xpu_api/utilities/meta/meta.trans/meta.trans.other/has_type_member.h:27:48: note: in instantiation of template class 'std::underlying_type<void>' requested here
27 | struct has_type_member<T, …
```

Fix compile error in C++17 : only enumeration types have underlying types

---

test/kt/esimd_radix_sort.cpp
test/kt/esimd_radix_sort_by_key.cpp

`test_sycl_iterators` was replaced by `test_buffer` in `esimd_radix_sort_by_key` to tests both APIs: ranges and iterators (not only iterators).

[KT] Test API with sycl::buffer

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

This PR targets to refactor the USM host or buffer storage used as a return type for the reduction. This was introduced in #874. This simplifies the `__storage` and `__accessor` classes and moves them in the `__internal` namespace to align with other helpers. These changes are based on input and discussions with @SergeyKopienko.

Refactor USM host or buffer storage

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h

The goal of this PR - to avoid extra code in policy traits implementations and redefine `__is_hetero_execution_policy` trait as [disjunction](https://en.cppreference.com/w/cpp/types/disjunction) of `__is_device_execution_policy` and `__is_device_execution_policy` traits:
```C++
template <typename _T>
using __is_hetero_execution_policy =
::std::disjunction<
typename __is_device_execution_policy<_T>::type,
typename __is_fpga_execution_policy<_T>::type>;
```
Previously we had more complicated implementation of `__is_hetero_execution_policy` trait:
```C++
template <typename _T>
struct __is_hetero_execution_policy : ::std::false_type
{
};
template <typename... PolicyParams>
struct __is_hetero_execution_policy<execution::device_policy<PolicyParams...>> : ::std::true_type
{
};
template <unsigned …
```

Redefine of __is_hetero_execution_policy trait through __is_device_execution_policy and __is_fpga_execution_policy

---

test/xpu_api/utilities/function.objects/arithmetic.operations/minus_arithm_op.pass.cpp
test/xpu_api/utilities/utility/utility.swap/swap_utility.pass.cpp

In this PR we fix run-time errors in xpu_api tests: `Required aspect fp64 is not supported on the device`

Fix run-time errors in xpu_api tests

---

.github/workflows/ci.yml

**Summary**
`dpcpp_linux-64` `2024.0.0`, in contrast to `2023.2.0`, lacks some files which allow discovery of FPGA emulator device.
This PR switches testing of FPGA emulator from the latest compiler version (`2024.0.0`) to the previous (`2023.2.0`) where FPGA emulator is available.
**Notes**
I was able to fix the environment for the emulator on `dpcpp_linux-64` `2024.0.0` locally following these steps:
- copy `cl.cfg` as `cl.fpga_emu.cfg`
- set `OCL_ICD_FILENAMES` to point the location of `libintelocl_emu.so*` or write this location into `$CONDA_PREFIX/etc/OpenCL/vendors/intel-fpga_emu.icd`. 
But it does not work with the environment on a github-hosted runner. Let me know if it still requires investigation. Other possible option is to use other, OS specific package managers, e.g. APT.

[CI] Fix environment for FPGA emulator testing

---

include/oneapi/dpl/pstl/execution_impl.h

In this PR we remove `oneapi::dpl::__internal::__collector_t` as unused.
Previous definition of `__collector_t` were:
```C++
template <typename _ExecutionPolicy>
using __collector_t = typename __internal::__policy_traits<::std::decay_t<_ExecutionPolicy>>::__collector_type;
``` 
but `__collector_type` type is already absent in onDPL code too: [search results](https://github.com/search?q=repo%3Aoneapi-src%2FoneDPL%20__collector_type%20&type=code)
The type alias `__collector_t` is never used in oneDPL code: [search results](https://github.com/search?q=repo%3Aoneapi-src%2FoneDPL%20__collector_t%20&type=code)

Remove `__collector_t` as unused

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

This PR removes `#pragma unroll` from loops whose bounds are not known at compile time. With the 2024.0.0 compiler, the `merge` algorithm and `scan` family of algorithms now throw runtime warnings during JIT compilation stating that the unroll transformation cannot be performed:
```
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
```
After removing these unnecessary pragmas, the warnings go away.

Remove unroll pragmas on loops with dynamic bounds

---

include/oneapi/dpl/pstl/onedpl_config.h

This PR attempts to address #1294. Not sure if it's the best approach, but it should definitely catch all `clang` based compilers which support pragma unroll.
I haven't worked out a portable way to add a warning when undefined as per @jinz2014's suggestion on the issue.

Enable pragma unroll for open-source DPC++

---

test/support/test_config.h

Let's extend the macro for Intel(R) oneAPI DPC++/C++ Compiler 2024.0.1 (2024.0.1.20231122). This compiler is still not able to compile this test entirely.

[Tests] Update broken macro for reduce_by_segment test

---

include/oneapi/dpl/pstl/execution_defs.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/iterator_defs.h
include/oneapi/dpl/pstl/iterator_impl.h
include/oneapi/dpl/pstl/utils_ranges.h

1. Simplified temporary sycl::buffer support in case of host iterators (when it needs to copy data to a temp buffer and back). 
2. Removed lifetime extension for temporary  sycl::buffer, which used within some SYCL backend patterns. According to the SYCL spec, SYCL runtime manages lifetime of such buffer itself.
3. Permutation_iterator support fixes.
4. A mention about a limitation in the doc: https://github.com/oneapi-src/oneDPL/pull/1295/files
5. Compiler time error for some non-supported iterator types (according to the documentation)
6.  is_passed_directly and is_hetero traits refactoring
7. Usage of exclusive access sycl::buffer with pointer to host data and data size for better performance. (Instead of sycl::buffer with iterators constructor - slow perf because of element-wise copy)

[oneDPL][hetero] Simplifying of temporary sycl::buffer support

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment_perm_it.pass.cpp

1. The test coverages for a case with permutation_iterator(host_iterator, valid_iterator) was disabled, because it is not supported by oneDPL. Before it was UB, now - compile time error.
2. Compile time diagnostic improved for the mentioned case.

[oneDPL][test][perm_it] Some test cases were disabled, because it is not supported by oneDPL

---

src/CMakeLists.txt
src/pstl_offload.cpp

free() call is possible inside dlsym(). Because global free() is overloaded, this may lead to crash. The situation is detected via TLS flag and releasing of object from nested free() calls is delayed till obtaining system free() address.

[pstl-offload] Support free() call while obtaining system free() address

---

.github/workflows/ci.yml

The change is being made to bring the repo into compliance with the recommended best practice of enforcing the policy of least privilege.  See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions for the details.

Adding read-only permission to all jobs in the CI flow to ensure minimum required access

---

.github/workflows/ci.yml

libpstloffload and FPGA emulator are not available through Conda packages. This PR fixes it by using other installation methods:
- APT on Linux
- Offline installers on Windows
Side effects:
- Simpler environment setup (e.g. no registry manipulations, no manual env variables set up).
- Component links should be manually updated upon each component release (Windows only)

[CI] Fix CI by moving from Conda to other approaches

---

include/oneapi/dpl/pstl/utils_ranges.h
test/parallel_api/iterator/permutation_iterator.h
test/parallel_api/iterator/permutation_iterator.pass.cpp

Fix for implementation of `permutation_view_simple` to return from `operator[]` by reference rather than by value.
Adding test for fill to cover missed test case.
Fixing some rules for modifying source data in permutation iterator tests, **this was resulting in a number of skipped tests.**
Following with other tests in this permutation_iterator.pass, checking of result is skipped.  Another PR should provide the checks for permutation iterator to properly evaluate if the result is achieved appropriately, and should apply the same permutation safely on the host to check the result.
The bug we experience and are fixing in this PR is at compile time and it is resolved.

Bugfix for permutation_iterator operator[]

---

test/support/test_config.h
test/xpu_api/tuple/tuple.tuple/tuple.elem/tuple_get_const_rvalue.pass.cpp

In this PR we avoid GCC7 compiler error described at https://gcc.gnu.org/pipermail/gcc-help/2018-May/133865.html :
`std::get not returning const rvalue reference from const rvalue reference of tuple`

GCC7 std::get not returning const rvalue reference from const rvalue reference of tuple

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h

This PR returns legacy support for types having the `is_passed_directly` trait provided.
#1254 changed the way that this was implemented internally by instead enumerating the types which were passed directly with template specialization of `struct is_passed_directly`.  
While this is an implementation detail, it is a useful one which has been used in the compatibility headers to support `device_iterator` and `device_pointer`, and may be used in some user code. This returns the support for the `is_passed_directly` trait, to augment the new system.

Adding legacy support for is_passed_directly trait

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h

This PR adds a temporary fix to the min element lambda. It adds an assumption that the non-comm approach is taken for the SPIRV target path, regardless of the commutivity template parameter passed.

Temp fix to commutivity issue

---

test/xpu_api/tuple/tuple.tuple/tuple.elem/tuple_get_const_rvalue.pass.cpp

Additional fix for https://github.com/oneapi-src/oneDPL/pull/1333

GCC7 std::get not returning const rvalue reference from const rvalue reference of tuple - additional fix

---

include/oneapi/dpl/pstl/histogram_binhash_utils.h

The PR fixes errors like:
``histogram_binhash_utils.h:44:36: error: no member named 'numeric_limits' in namespace 'std'``

Add missing header

---

include/oneapi/dpl/internal/reduce_by_segment_impl.h

This PR addresses the following issue: https://github.com/oneapi-src/oneDPL/issues/1353.
Previously, we used the `known_identity` alias from the `__dpl_sycl` namespace in `reduce_by_segment`. I believe it is more correct to use the implementation in the `unseq_backend` namespace which wraps around the SYCL implementation with some additional logic.

Use known_identity checks from the unseq_backend namespace in reduce_by_segment

---

test/parallel_api/numeric/numeric.ops/histogram.pass.cpp

The tests as written were resulting in kernel name clashes with `-DONEDPL_USE_UNNAMED_LAMBDA=OFF`.  This is due to different types being used to call the histogram API with the same call number / kernel name.  
Kernel name generation assumes the the user is responsible for unique kernel names as input to oneDPL algorithms when `-DONEDPL_USE_UNNAMED_LAMBDA=OFF`.  To keep names reasonably sized, we do not embed ALL information about the kernel into the kernel name, just enough to distinguish between multiple kernels generated from the same external oneDPL API call.  Therefore, the fix is not to add type information to the kernel name, but rather to provide unique call numbers for each API call in the testing.

Testing Bugfix, histogram.pass, unique call number

---

include/oneapi/dpl/pstl/iterator_impl.h

In this PR we do the next things:
1) revert extra changes from fancy iterators implementations which were made in https://github.com/oneapi-src/oneDPL/tree/dev/dhoeflin/fix_zip_iterator_trivially_copyable (PR https://github.com/oneapi-src/oneDPL/pull/1371)
2) ~~declare constructors of `transform_iterator` with params as `explicit` for compatibility with another fancy iterator implementations.~~

Revert extra changes from fancy iterators impl

---

include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/dynamic_load_policy.h

[Dynamic Selection] Use ::std::lock guard instead of ::std::unique_lock in auto_tune and dynamic_load policy

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h

This PR addresses two bugfixes for histogram
1. FPGA handling for converting to device policy, bad rebase did not change with some refactoring to handling of policy (and correcting a universal reference to a const lvalue ref to be consistent with device policy)
2. Removing unnecessary `begin()` call for a local_accessor, which caused problems on icpx 2022.3.  We only need an accessor which supports bracket operators in the function we are calling, so we can just pass the `local_accessor` itself.
3. Removing unnecessary and problematic include of `async_impl_hetero.h`

Histogram bugfixes for FPGA and icpx 2022.3 

---

include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h
test/parallel_api/dynamic_selection/sycl/test_internal_sycl_scheduler.pass.cpp

Addressed comments in https://github.com/oneapi-src/oneDPL/pull/1085 directed for sycl_backend.h
Change order of execution_info::task_completion_t and execution_info::task_time_t

[Dynamic Selection] Addressed comments to sycl_backend

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h

Three fixes for permutation_iterator:
1. Legacy `is_hetero` trait #1380 (for the sake of time, closing that PR in favor of this one combined)
2. Fix for `is_passed_directly` legacy trait to be usable recursively
3. Restore "general case" with recursion with size of 1 for base iterator of a `permutation_iterator`

Three fixes for permutation_iterator

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/iterator_impl.h
test/parallel_api/iterator/iterators.pass.cpp
test/parallel_api/iterator/permutation_iterator.pass.cpp
test/parallel_api/iterator/transform_iterator.pass.cpp
test/parallel_api/iterator/zip_iterator.pass.cpp
test/support/utils_sycl.h

This PR contains two bugfixes, which both impact the handling of  `permutation_iterator<zip_iterator<usm_ptr,usm_ptr>,usm_ptr>` and similar types as input data to oneDPL APIs.  These bugs were originated in #1254.
1. Make the fancy iterators: `zip_iterator` and `zip_forward_iterator` trivially copyable, and therefore device copyable, along with tests to check this
2. Add forward declaration for `__require_access`, which is to be necessary for `_require_access_args` to find this overload.
During investigation of this error, we discovered that transform_iterator and therefore permutation_iterator were not officially SYCL 2020 device copyable (although the work in practice with icpx's implementation of SYCL as if they were device copyable).  An issue #1386 has been created to record this, …

Fix zip iterators to be device copyable, fix for require_access

---

test/parallel_api/iterator/permutation_iterator.h
test/parallel_api/iterator/permutation_iterator_parallel_find.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_for.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_merge.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_or.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_partial_sort.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_stable_sort.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_transform_reduce.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_transform_scan.pass.cpp
test/support/utils.h

This PR is being proposed as an alternative to #1370
According to the SYCL 2020 spec [Section 5.2 Naming of kernels](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:naming.kernels), "kernel names must be forward declarable at namespace scope".  
It seems that the tags we were using to signify test types for permutation iterator map methods, which are a group of structs inside a struct do not meet this criteria.  
Changing them to be base level structures with the outer name incorporated resolves this issue.
We also have a few kernel naming clashes for `permutation_iterator_parallel_for.pass` and `permutation_iterator_parallel_merge.pass`.  This was fixed with help from @SergeyKopienko and #1370, to add utility functions to wrap of kernel names for hetero …

[test] Fix for kernel names issues in permutation iterator tests

---

test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/transform_unary.pass.cpp

In this PR we fix compile errors in some tests for CMake option `ONEDPL_USE_UNNAMED_LAMBDA=OFF`

[test] Fix Kernel names in tests

---

test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/support/test_config.h

https://github.com/oneapi-src/oneDPL/pull/1360 introduced `ONEDPL_WORKAROUND_FOR_IGPU_64BIT_REDUCTION` which forces a different code path in `reduce_by_segment` to avoid a driver bug that causes incorrect results on certain hardware.
Currently, if this macro is not set, then `reduce_by_segment.pass` will fail with the DPCPP backend with 64-bit types on certain Intel GPUs. This PR excludes these tests when `ONEDPL_WORKAROUND_FOR_IGPU_64BIT_REDUCTION` is `0` or undefined to avoid these known failures.
The solution currently is implemented with a compile-time preprocessor check. However, when a driver fix is provided the long-term solution may involve a runtime check by checking the driver version of the `sycl::device`. I have marked this as a todo in the code.

[test] Introduce broken macro if workaround for reduce_by_segment is not used

---

documentation/library_guide/requirements.txt

Older Jinja versions are vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter. The issue has been resolved in Jinja 3.1.3. Updating our doc build to use the newer version and eliminate exposure to the issue.

Update jinja to eliminate xmlattr vulnerability.

---

src/CMakeLists.txt

The aim of this change is to enable dependency checking and cleanup over vars.sh.

[pstl-offload] Make vars generation stage for PSTL offload custom target

---

include/pstl_offload/internal/usm_memory_replacement.h
include/pstl_offload/internal/usm_memory_replacement_common.h
src/pstl_offload.cpp

Change `__get_original_msize`, `__get_original_aligned_alloc` and `__get_original_realloc` to do action instead of returning the function pointer. Changes are aligned with `__get_original_free` removal made previously.

[pstl-offload] Remove returning function pointer from __get_original_ functions

---

test/parallel_api/iterator/permutation_iterator_parallel_merge.pass.cpp

After permutation, input segments are not guaranteed to be sorted, resulting in errors or UB for merge call.
This PR sorts the input segments.

[test] permutation_iterator_parallel_merge fix, pre-sort permuted segments

---

test/parallel_api/iterator/permutation_iterator_parallel_merge.pass.cpp

Fix mangled name clash in added sort calls to permutation_iterator_parallel_merge tests.

[tests] Fix name clash in permutation_iterator tests

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
test/parallel_api/numeric/numeric.ops/histogram.pass.cpp

FPGAs do not support 64 bit atomics.  The histogram pattern uses atomics of the value type of the output sequence.  
Adding static assertion for FPGAs to only allow sequences with a value type of 32bit or less.
Adjusting the tests to match.
Its rare that a 64 bit output type should be necessary for histogram.  Input sequences would only start to need 64 bit output with sizes greater than 4Billion (and that would only overflow if all elements map to a single bin).

Disallowing histogram with 64 bit output on FPGA

---

documentation/library_guide/parallel_api/execution_policies.rst

Updated three links that changed when the FPGA Optimization Guide was renamed/redirected to the FPGA Handbook.

Update FPGA Guide Links

---

test/general/buffer_wrapper.pass.cpp
test/general/lambda_naming.pass.cpp
test/parallel_api/experimental/asynch-scan.pass.cpp
test/support/sycl_alloc_utils.h
test/support/utils_sycl.h
test/support/utils_sycl_defs.h

Decouple oneDPL implementation and tests and remove dependencies on the internal API.
It might be useful when the tests are used with newer library headers. This can be treated as a backward compatibility testing. If there is no dependency on internal APIs from the library headers, then such testing is possible.

Replace internal API in the tests (__sycl_defs entities)

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h

This PR switches the order of the iterators when processing the base iterator range for reverse_iterators.
If we do not do this, the next layer of handling for the input iterator will have incorrect ordering, and it will fail the assertion that `__first < __last` for the base.
This is a regression as of #1254, where a specialization was added specifically for reverse_iterators (However prior to that PR, it reverse_iterators may have been handled in a inefficient way).

Bugfix for reverse_iterators as oneDPL input with device policy

---

documentation/library_guide/introduction.rst
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/scan.pass.cpp

Device backend does not require a value type to have a default constructor which provides an identity value. Let's remove that limitation for device policies.
Additionally, `reduce_by_segment` is based on the scan pattern, so this limitation applies to that algorithm for host policies.
Note:
Theoretically, the limitation should be imposed only on `unseq` and `par_unseq` policies. However, there is (at least one) instance of using a default constructor on non-vector path. Thus, the limitation can be relaxed after further investigation.
The PR also removes cases for `reduce_by_segment` for `std::multiplies` + host policies, and adds a trivial case for scan test with `std::multiplies` + device policies.
There are other potential solutions for `reduce_by_segment`:
- Make a wrapper in …

Fix type limitations for scan algorithms, add reduce_by_segment

---

test/support/sycl_alloc_utils.h

Fixing path for `utils_sycl_defs.h` include, It is a sibling, not part of child directory.

[tests] Fix path for utils_sycl_defs.h

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
test/parallel_api/algorithm/alg.sorting/sort.pass.cpp

The PR adds:
-  A conversion to an ordered bit representation to sort `sycl::half` with radix sort algorithm.
- A test case for `sycl::half` elements.

Sort sycl::half with radix sort

---

include/oneapi/dpl/pstl/algorithm_impl.h

Assertion happens in the `reverse.pass` test.
It's reproduced on any C++ compiler on Windows
for CMake line `-DCMAKE_CXX_COMPILER=dpcpp-cl -DCMAKE_BUILD_TYPE=debug -DONEDPL_BACKEND=serial`
The root cause is that we call `__brick_reverse` and `__brick_reverse_copy` for empty source data in the parallel implementations for serial backend.

Avoid `__brick_reverse` and `__brick_reverse_copy` calls for empty source data

---

include/oneapi/dpl/pstl/experimental/internal/for_loop.h
include/oneapi/dpl/pstl/experimental/internal/for_loop_impl.h
test/parallel_api/experimental/for_loop.pass.cpp
test/parallel_api/experimental/for_loop_induction.pass.cpp
test/parallel_api/experimental/for_loop_reduction.pass.cpp

Th goal of this PR - to exclude ability of works `for_loop` staff with hetero policies,
because we haven't hetero implementation for `for_loop` staff.
**ATTENTION**: after this fix our users will have compile errors if they are using `for_loop` staff with hetero policies.

Disable `for_loop` staff for hetero policies

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

The existing unified USM or buffer storage used in the family of reduce algorithms uses the default constructor of SYCL accessors. This is a SYCL 2020 feature that was implemented here: https://github.com/intel/llvm/pull/7815. This limits the supported DPCPP compilers to 2023.1 and newer. This PR extends the compiler support by using a SYCL accessor with the `get_multi_ptr` routine on older (2023.0 and older) compilers instead of the `__usm_host_or_buffer_accessor` class. The `_ONEDPL_SYCL_USM_HOST_PRESENT` macro is further renamed to `_ONEDPL_SYCL_UNIFIED_USM_BUFFER_PRESENT` to highlight whether the compiler supports the unified USM and buffer implementation.
This issue was detected by @AidanBeltonS during the testing of https://github.com/oneapi-src/oneDPL/pull/1354. The proposed fix …

Extend compiler support for the unified USM and buffer storage

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

In this PR we fix compile errors in two ranges tests:
- `remove_if_ranges_sycl.pass`;
- `unique_ranges_sycl.pass`.
How we fixing this errors: by adding `__ranges` namespace before range pattern calls in the code.
The errors:
```C++
oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h:471:12: error: no viable conversion from returned value of type 'oneapi::dpl::__internal::__pstl_equal' to function return type 'oneapi::dpl::__internal::__difference_t<all_view<int, sycl::access::mode::read_write, sycl::access::target::global_buffer, sycl::access::placeholder::true_t>>' (aka 'long')
471 |     return res;
|            ^~~
oneapi/dpl/pstl/glue_algorithm_ranges_impl.h:369:47: note: in instantiation of function template specialization 'oneapi::dpl::__internal::__ranges::__pattern_unique<oneapi:: …
```

Fix compile errors in `ranges` tests

---

include/oneapi/dpl/pstl/algorithm_fwd.h
include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/execution_impl.h

Fixed some review comments from @danhoeflinger :
1) `_ForwardIterator` template params type with `__parallel_tag<_IsVector>` renamed to `_RandomAccessIterator`
2) `_RandomAccessIterator` template params type with `__parallel_forward_tag` renamed to `_ForwardIterator`
This change has been made to align these template param type names with `__parallel_policy_tag_selector_t` implementation:
```C++
template <class _IsVector, class... _IteratorTypes>
using __parallel_policy_tag_selector_t = ::std::conditional_t<
__internal::__is_random_access_iterator_v<_IteratorTypes...>, __parallel_tag<_IsVector>,
::std::conditional_t<__is_forward_iterator_v<_IteratorTypes...>, __parallel_forward_tag, __serial_tag<_IsVector>>>;
```

Fix review comments for tag dispatching

---

include/oneapi/dpl/pstl/algorithm_fwd.h
include/oneapi/dpl/pstl/algorithm_impl.h

The pattern is used by uninitialized_fill, which uses placement new to created objects, and new may throw a length_error exception.  Issue was reported by static analysis tools.

Removing noexcept to resolve issue reported by static analysis.

---

test/parallel_api/dynamic_selection/sycl/test_auto_tune_policy_sycl.pass.cpp
test/parallel_api/dynamic_selection/sycl/test_dynamic_load_policy_sycl.pass.cpp
test/support/utils_sycl.h

Tests with default device as FPGA_EMU have a runtime error of - terminate called after throwing an instance of 'sycl::_V1::runtime_error'.
Skipping since we do not use default device in our tests.

[Dynamic Selection] Skipping auto_tune and dynamic load tests when device=FPGA_EMU

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h

In some algorithm patterns there are calls of more then one SYCL backend patterns. As far as SYCL backend patterns are asynchronous, we have to make synch between the them. It might be set SYCL dependencies or "wait" of the first pattern at least.
"Setting SYCL dependencies" is more preferable and right approach. But, currently, SYCL backend API doesn't have possibility to pass the any dependencies. It should be re-designed in the  future... But now we can apply simple fix  - to wait of the first SYCL backend pattern call.

[oneDPL] A fix - added missed synchronization between two SYCL patterns.

---

include/oneapi/dpl/pstl/glue_memory_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h

In this PR we fix linker error when we have more then one translation unit for one project:
```C++
error LNK2005: "class oneapi::dpl::execution::v1::parallel_policy const & __cdecl oneapi::dpl::get_unvectorized_policy(class oneapi::dpl::execution::v1::parallel_unsequenced_policy const &)" (?get_unvectorized_policy@dpl@oneapi@@YAAEBVparallel_policy@v1@execution@12@AEBVparallel_unsequenced_policy@4512@@Z) already defined in hello-1-5be217.obj
```
The problem is that our functions `get_unvectorized_policy` are not `inline`.

Fix linker error LNK2005 for tag dispatching staff

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

This PR modifies how values are passed between `transform_reduce` and `reduce_over_group`. As opposed to moving data into local memory, syncing the work_group, then unloading we just move the value into a register and return it.
This allows us to save local memory loads and stores, and a barrier. We have seen improved performance on both Nvidia and Intel GPUs from this PR.

Pass value and remove barrier between transform_reduce and reduce_over_group

---

test/parallel_api/ranges/transform2_ranges_factory_sycl.pass.cpp

[oneDPL][ranges] + hot fix for a test (experimental ranges)
There was an ambiguity for `dpl::experimental::ranges::transform` and `dpl::transform` (using namespace dpl::experimental::ranges)

[oneDPL][ranges] + hot fix for a test (experimental ranges)

---

test/parallel_api/iterator/permutation_iterator.h

This PR should fix the `permutation_iterator` tests with `transform_iterator` as index.  In practice, without this PR, errors only appear on Windows platforms, however it may not be limited to windows.
The SYCL spec requires that template arguments (captures) to lambda functions submitted as sycl kernels must be included in the kernel name and must be "forward declarable at namespace scope".
https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:interfaces.kernels.as.lambdas
When we use a functor in a `transform_iterator` which is then used as index for a `permutation_iterator`, the type of the resulting range must be forward declarable at namespace scope as it is used in the reduce kernel as an input capture to the lambda sycl kernel.   When we define the functor …

[tests] Fix for permutation_iterator tests with transform_iterator index

---

include/oneapi/dpl/pstl/omp/util.h
include/oneapi/dpl/pstl/parallel_backend_serial.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h
include/oneapi/dpl/pstl/parallel_backend_utils.h

The goal of this PR - to reduce the amount of duplicated code in our host backends implementations.
In this PR we implement and use the common implementation of host backends buffer, specialized by different memory allocators.
Previously we had three different implementations of hosts backends buffer: they were absolutely the same but have used different memory allocators.

Common implementation of hosts backends buffer

---

include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/memory_impl.h
include/oneapi/dpl/pstl/parallel_backend_utils.h
test/parallel_api/algorithm/alg.sorting/alg.set.operations/set_common.h

Bug Description
---
As implemented before this PR, `set_intersection` using `oneapi::dpl::execution::par` has a bug which results in incorrect semantics for some situations.  
For performance reasons, in some situations, we would prefer to reverse the order of arguments in the parallel loop for input iterators.  However, this results in copying from the second set of iterators which is against semantics found here:
https://en.cppreference.com/w/cpp/algorithm/set_intersection
..."elements will be copied from [first1, last1) to the output range, preserving order."  
In cases where the comparator does not compare ALL of the input type, this can be very important.  For instance, a comparator for a key value pair which only considers the key.  
Fix Summary
---
This PR fixes this bug by passing …

Bugfix for set_intersection copying from second iterator range

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

Algorithms using `transform_reduce` (`std::reduce`, `std::max_element`, etc) return a single value result. They also, except for the smallest cases, require intermediate scratch memory on the device to hold partial results.
For L0 backend, it's faster to have a 1-element USM host allocation and to write the final reduction result directly to that.
For Nvidia, host USM is expensive, and it's faster instead to have a single USM device allocation for both the **result** and the **intermediate scratch**.
This PR combines the two approaches into a struct `__usm_host_or_unified_storage`, based on the previous `__usm_host_or_buffer_storage`. When host USM is supported and the backend is L0, this struct holds two memory allocations (device USM for intermediate scratch, and host USM for final …

Redefine transform_reduce's scratch & result mem

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

This PR addresses several issues found in #1354:
1. `ONEDPL_SYCL_USM_HOST_PRESENT` was renamed to `_ONEDPL_SYCL_UNIFIED_USM_BUFFER_PRESENT` in #1410
2. Empty scratch space allocation is unguarded when using USM host memory. This leads to runtime issues or `bad_alloc`.
3. The guards to support older compilers (#1410) are missing.
4. `__get_usm_host_or_buffer_accessor_ptr` should be used based on @MikeDvorskiy's comment here: https://github.com/oneapi-src/oneDPL/pull/1410#discussion_r1504499285
This includes the changes to address the first issue proposed by @mmichel11 in #1502.

Fix issues in USM result and scratch memory (PR #1354)

---

documentation/library_guide/introduction.rst
documentation/library_guide/parallel_api/pass_data_algorithms.rst

`std::vector<bool>` has an optimization to a bitfield rather than individual booleans.  For host policies, this will simply not work for parallel algorithms (without some extra processing step / copy, which will kill performance).
On `icpx` and with device policies it works:
- With the default allocator, `std::vector<bool>::iterator` works as input to algorithms using a device policy, but only because of the copy to initialize the `sycl::buffer`. 
- With `usm_allocator`, `std::vector<bool>::iterator` also works, but only because it is treated as if it were a host_iterator, and copied into a `sycl::buffer`.  After #1438, this should still work by treating it as a host_iterator and copying to a `sycl::buffer`, because the implementation does not distinguish iterator types based on …

[Doc] Adding note for std::vector<bool>

---

.github/workflows/ci.yml
test/parallel_api/algorithm/alg.sorting/sort.pass.cpp

This PR should prevent the post-merge CI from getting cancelled.
-
Recently, I've had a couple post-merge CI runs cancelled due to other merges. 
This should not happen, and we tried to protect against this when writing the CI cancel change in #1271 .
It seems what we had did not work  (see this example: https://github.com/oneapi-src/oneDPL/actions/runs/8707524513)
Following the guide [here](https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-on-specific-branches), I'm loosening the check from an (in-)equality to a (not) contains.  From the example above, it seems that more may be embedded in the `github.ref` than I realized.

[CI] Fix for main CI getting cancelled post-merge

---

include/oneapi/dpl/internal/common_config.h

There is an issue while STL headers before `<oneapi/dpl/execution>` on GCC9 and GCC10 with modern oneTBB versions:
```
#include <cstddef>
#include <oneapi/dpl/execution>
int main() { ... }
```
Any STL header includes the file `bits/c++config.h` that defines macros `__PSTL_USE_PAR_POLICIES` and `__PSTL_PAR_BACKEND_TBB`. Since STL headers goes before `oneDPL/common_config.h`, these macros would be defined to `1` because oneTBB is present but the version is not checked.
If we want to include `<execution>` safely in `<oneapi/dpl/execution>`, these macros should be unset in common config.

Fix common config for including STL headers before oneDPL on GCC9 and GCC10

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

#1495 added move statements which are not needed since the result of `__unary_op` is already an [prvalue](https://en.cppreference.com/w/cpp/language/value_category#prvalue).
See original comment by @SergeyKopienko: https://github.com/oneapi-src/oneDPL/pull/1511#discussion_r1569022127

Remove unnecessary move statements added in #1495

---

test/parallel_api/algorithm/alg.sorting/alg.set.operations/set_common.h
test/parallel_api/iterator/permutation_iterator_parallel_for.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_merge.pass.cpp
test/support/utils.h

Fixes set intersection kernel names.
Removes some unnecessary parts from a utility for generating new kernel names
Bug introduced in #983

[Tests] Fix for set_intersection kernel names

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h

[oneDPL][hetero] + a blocking behavior fix for some algo patterns (sync API)
According to 4.7.2.3. Buffer synchronization rules, rule number (1), a destructor of such buffer does not need to block. So, RAII instance of such buffer doesn't guarantee implicit wait. The PR fixes the behavior for oneDPL sync API.
(https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:buf-sync-rules)

[oneDPL][hetero] A blocking behavior fix for some algo patterns (sync API)

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

Adding some missing includes.
* `<functional>`  for `std::plus`
* `<utility>` for `std::make_pair`, `std::forward`
* `<limits>` for `std::numerical_limits`
* `<cmath>` for `std::log2`  <-- this is the one which had an error report in some environment / code

Adding missing includes `parallel_backend_sycl.h`

---

include/oneapi/dpl/internal/binary_search_impl.h
include/oneapi/dpl/internal/function.h
include/oneapi/dpl/pstl/utils.h

This PR introduces some additional tuning for the vectorized search algorithms (binary_search, lower_bound, and upper_bound) where a series of searches across a provided set of search keys are performed on a single input buffer.
The improvements are explained below:
1. In the current implementations, `__pstl_lower_bound`  / `__pstl_upper_bound` have been passed a 64-bit size type to compute indicies in its binary search. For inputs with a large number of search keys, this is a bottleneck in performance and rooflines have shown that this kernel is bound by 64-bit arithmetic. This PR introduces a 2-kernel solution where a 32-bit unsigned type is used for index calculation if there are less than ``2^32`` search keys with a fallback to 64-bit offset calculation otherwise. This results in a …

Tune vectorized binary_search, lower_bound, and upper_bound algorithms

---

test/parallel_api/iterator/permutation_iterator_parallel_find.pass.cpp

In `permutation_iterator_parallel_find.pass`, we need to copy a value from the host to the device. Currently, we do this by passing a host pointer to the device but this is problematic since the host pointer is not device accessible and results in segfaults on the device.
I have resolved this by passing an iterator to a single element `std::vector` to the `copy` call so the copy to host memory is properly handled.

[test] Fix dpl::copy call where we attempt to access host memory on the device

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
test/general/implementation_details/device_copyable.pass.cpp

Fix for device copyability for oneDPL's internal tuple for non-trivially copyable element types which are device copyable. (like std::tuple)

Fix device_copyable for internal tuple with non trivially copyable elements

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h

Iterator inputs to parallel APIs with a device policy which have a const-qualified value type are experiencing build errors on with MSVC or GCC standard library implementation because of static assertions in the class definition for std::vector.  
Our check for USM allocated vector iterators checks all input iterators, and within the check, instantiates a `std::vector` with a value type which matches the input iterator's value type. Prior to this PR, we do not protect against "ill formed" vector instantiations, like const-qualified, reference, or function types.  When the value type of the input iterator are any of these, the build hits `std::vector` [static assertions ](https://github.com/microsoft/STL/blob/0515a05b394596de92d08cb0f352614479a2a883/stl/inc/xmemory#L898C1-L903C80) while …

Fix for iterators with const-qualified value type

---

documentation/library_guide/kernel_templates/esimd/radix_sort.rst
documentation/library_guide/kernel_templates/esimd_main.rst
include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
include/oneapi/dpl/experimental/kt/internal/esimd_defs.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_utils.h
test/kt/esimd_radix_sort.cpp
test/kt/esimd_radix_sort_by_key.cpp
test/kt/esimd_radix_sort_by_key_out_of_place.cpp
test/kt/esimd_radix_sort_out_of_place.cpp

The PR moves `esimd` namespace into `gpu` umbrella namespace as a more narrow target for GPU device type. 
The original namespace is now deprecated.

[KT] Move esimd functionality into gpu namespace

---

test/parallel_api/iterator/input_data_sweep_usm_allocator.pass.cpp
test/support/utils.h

A bad rebase before merging #1429  resulted in the removal of some TestUtils meant to avoid using internal namespace details within the tests.  
The lack of these helpers results in a failing `input_data_sweep_usm_allocator.pass`.  This PR restores the structs, allowing the test to build and run.

[Tests] Missing TestUtils helper restored 

---

test/parallel_api/dynamic_selection/sycl/test_auto_tune_policy_sycl.pass.cpp

1) Fix USM shared memory leaks in test
2) Create unique Kernel names in `h.single_task([](){});` calls.

Fix USM memory leaks and create unique task names

---

test/general/implementation_details/device_copyable.pass.cpp

Resolves incorrect header inclusion for sycl.hpp.  
This PR uses our local `util_sycl_defs.h` in place of `sycl.hpp` to ensure we have access to sycl device_copyable checks.

[Tests] Fix header include for device_copyable.pass

---

include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h
include/oneapi/dpl/internal/dynamic_selection_traits.h
test/support/inline_backend.h

In this PR we fix format of report method:
- describe second param as `report_duration` to avoid potential errors with measure units for this param value;
- change required traits according to previous change.

Fix the format of report method - using `report_duration` in second param

---

test/support/test_config.h

We can only count on undefined macros to be treated as `0` within `#if` checks.  Within `tuple_get_const_rvalue.pass`, this macro is used as an expression to determine if the test was skipped or not, and this fails when `_GLIBCXX_RELEASE` is undefined.
Here is the usage 
https://github.com/oneapi-src/oneDPL/blob/3d762ceb57721b6fd6059086ccc757e2d2466f08/test/xpu_api/tuple/tuple.tuple/tuple.elem/tuple_get_const_rvalue.pass.cpp#L60
This changes the macro to work both in `#if` and also as an expression, allowing the test to build.
C++ Standard 16.1.4 describes when 0 is used in replacement of undefined identifiers.  (but is only relevant within `#if` checks).

[Tests] Fix broken macro so it can be used as expression

---

test/support/test_config.h

In this PR we remove unused defines from the file `test/support/test_config.h` :
- `_PSTL_CLANG_TEST_BIG_OBJ_DEBUG_32_BROKEN`.

Remove unused defines from test/support/test_config.h

---

include/oneapi/dpl/pstl/onedpl_config.h
include/oneapi/dpl/pstl/utils.h

In this PR we void compile error in `std::bit_floor` MS STL implementation :
`error: SYCL kernel cannot use a non-const global variable`
- they using "extern" variable `__isa_available` in the code, which is not acceptable for use in Kernel code.
The purpose of `__isa_available` variable usage described at
https://devblogs.microsoft.com/cppblog/avx-512-auto-vectorization-in-msvc/
The compile error log:
```C++
bin\dpcpp-cl.exe  /nologo /TP -DPSTL_USE_DEBUG -DTBB_USE_DEBUG=1 -D_PSTL_TEST_SUCCESSFUL_KEYWORD=1 -D__TBB_NO_IMPLICIT_LINKAGE=1 -Itest -Iinclude -IC:\localdisk\tools\inteloneapi\latest\tbb\latest\include -DTEST_LONG_RUN=1 -fsycl /EHsc /Zi /Ob0 /Od /RTC1 -MDd /clang:-fno-fast-math /bigobj /Zc:__cplusplus /EHsc /Qopenmp-simd -fno-sycl-unnamed-lambda -Qstd:c++20 -QMD -QMT …
```

The implementation of `std::bit_floor` in MS STL does not meet requirements for SYCL device functions

---

test/support/test_config.h
test/xpu_api/tuple/tuple.tuple/tuple.elem/tuple_get_const_rvalue.pass.cpp

In this PR we fix broken test `tuple_get_const_rvalue.pass` under GCC 7.
In the file `test/support/test_config.h` we taking a look at `_GLIBCXX_RELEASE` state :
```C++
// GCC7 std::get doesn't return const rvalue reference from const rvalue reference of tuple
#if defined(_GLIBCXX_RELEASE)
#else
#endif
```
But in concrete case it's not enough, because not files from standard library has been included before and `_GLIBCXX_RELEASE` is undefined: so we have
`#   define _PSTL_TEST_GCC7_RVALUE_TUPLE_GET_BROKEN 0` 
as result.
In this case the test `test/xpu_api/tuple/tuple.tuple/tuple.elem/tuple_get_const_rvalue.pass.cpp` has compile errors due https://gcc.gnu.org/onlinedocs/gcc-7.5.0/cpp/Defined.html.

Fix broken test `tuple_get_const_rvalue.pass` under GCC 7

---

test/parallel_api/iterator/permutation_iterator_parallel_partial_sort.pass.cpp

Speedup the tests for permutation iterator partial sort by running the verification in parallel on the host (instead of a transfer back to the device), and most importantly cutting down the number of iterations run of the "partial" part of the sort.

[Tests] Speedup permutation iterator partial sort 

---

test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp

`reduce_by_segment.pass` has become a bottleneck in CI runtime and is taking excessively long compared to similar tests. I have made the following adjustments to speed it up:
- Previously for custom binary predicates and / or operators, we would first test the case with the default predicate and default operator (`std::plus<T>` and `std::equal_to<T>`) on the underlying data and then the default predicate and custom operator before testing with the custom predicate and custom operator. In my opinion, this is overtesting `std::equal_to` and `std::plus`. which is ultimately leading to long compilation and run times. I have replaced this to only test with the custom predicate and operator and use the default predicate / operator APIs if possible with a compile time check.
- We had several …

[test] Speed up the reduce_by_segment.pass test

---

include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h

In this PR we fix the initialization of `resample_time_` field due really it's defined as `uint64_t`.

Fix resample time initialization

---

include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/dynamic_load_policy.h

In this PR we doing the next steps:
- remove extra search on `time_by_index_` unordered map;
- doing possible actions without mutex.

Improvements of add_new_timing method

---

documentation/library_guide/parallel_api/pass_data_algorithms.rst

Separated out from #1438.  
Documentation changes to describe the details of usm allocators after that PR is merged.  
It also describes a more guaranteed way for proper handling of USM allocated data by directly obtaining USM pointers from a `std::vector`, as this does not rely on any implementation details of the C++ standard library implementation.

[Doc] Additional details for USM allocators with std::vector

---

test/xpu_api/containers/sequences/array/array.special/swap1.pass.cpp
test/xpu_api/containers/sequences/array/array.swap/swap.pass.cpp

Similar to #766, swap and swap1 tests have issues with precompiled vector algorithms being used, and require a workaround for use in SYCL kernels on windows.

[Tests] Adding windows vector alg workaround for swap

---

test/parallel_api/iterator/transform_iterator.pass.cpp

It doesn't make sense to check a std::vector::iterator allocated on the host for device_copyability.  
We don't want to copy this to the device anyway.  A smarter check is to check with a pointer to usm shared memory.
Generally, this check passes anyway, however in some configurations on windows, std::vector:iterator is non device_copyable, resulting in a trigger for this static assertion.

[Test] Replacing bad type to check for device_copyable

---

include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/numeric_impl.h
include/oneapi/dpl/pstl/utils.h

On some platforms, specifically Fedora 40 with GCC 14, the included `pstl_config.h` is such that the macros  `_PSTL_UDR_PRESENT` and `_PSTL_UDS_PRESENT` are present but defined as an empty macro. This is causing compilation errors.
In this PR, we work around the empty macros by first testing `_PSTL_UDR_PRESENT + 0`, which evaluates to `+0` (i.e., false) if the macro is undefined and the correct value if it is defined.

Change usage of _PSTL_UD[R/S]_PRESENT macros

---

test/support/test_complex.h
test/xpu_api/numerics/c.math/cmath.pass.cpp
test/xpu_api/numerics/complex.number/cmplx.over/imag.pass.cpp
test/xpu_api/numerics/complex.number/cmplx.over/real.pass.cpp

In this PR we fix exceptions `Required aspect fp64 is not supported on the device` in three tests:
- `test/xpu_api/numerics/complex.number/cmplx.over/imag.pass.cpp`;
- `test/xpu_api/numerics/complex.number/cmplx.over/real.pass.cpp`;
- `test/xpu_api/numerics/c.math/cmath.pass.cpp`.

Fix fp64 aspect error in tests

---

test/parallel_api/iterator/input_data_sweep_usm_allocator.pass.cpp
test/support/test_config.h

In the Intel LLVM compiler when building for FPGA, usm-allocated vector iterators fail to build when summed with an integer.  
This means that using usm-allocated vector iterators cannot be used in a `zip_iterator`, `transform_iterator` or `permutation_iterator` as a map and then dereferenced with the bracket operator.
This PR skips testing these input types for intel llvm compiler 2024.2 or earlier.
(This has been reported to the intel llvm compiler. Depending on when the fix is made, we may need to update the macro with the appropriate version)

[Tests] Avoid usm-allocated vector iterators wrapped in custom iterators for FPGA

---

documentation/library_guide/kernel_templates/esimd/radix_sort.rst

This PR updates the esimd radix sort documentation with the out of place overloads which were added in #1439.
It also cleans up some minor typos and fixes the namespace in the examples to match their new home after the move.
The memory requirements and performance considerations for out of place overloads should be equivalent to the in place overloads.  Out of place overloads run the same kernel code internally, it just provides different input and output sequences to the kernels to allow users to 
(1) preserve input sequence order
(2) fold in a copy to an output sequence

[Docs] Out of place esimd radix sort documentation update

---

.github/workflows/slack-pr.yaml

Post notification to onedpl channel in uxlfoundation slack space when a PR is labeled with RFC. To see a sample notification, look at #rc-test channel in uxlfoundation slack workspace. This is same as https://github.com/oneapi-src/oneMKL/pull/481, except the channel name and making the (missing) license consistent with ci.yml.
To be functional, the PR must be merged and someone with admin access to the repo must add SLACK_BOT_TOKEN secret. I can provide the token in DM.
Partially addresses https://github.com/orgs/uxlfoundation/projects/5?pane=issue&itemId=56606873
@vbm23 @timmiesmith

notification in slack for PR with RFC label

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

The current `minmax_element` implementation requires in-order processing since its binary operator assumes that the index of the first input is lower than that of the second input. This is a performance improvement since we can skip the case when both input values are equal. The in-order processing is guaranteed by following the non-commutative reduce pattern. We currently check the index order with assertions with lead to high overheads when compiled without `NDEBUG`. This may lead to test timeouts or user code looking to be hanging. I think the assertions are not needed since we enforce them in the in-order reduce pattern and we don't use them in the similar `min_element` algorithm.

Remove assertions in minmax_element binary operator

---

include/oneapi/dpl/pstl/algorithm_fwd.h

Fix `__pattern_partial_sort_copy` forward declaration :
- we forgot to declare `__pattern_partial_sort_copy` with `__parallel_tag` as the first param.
- 
Instead we had two declarations of the same `__pattern_partial_sort_copy` :
```C++
template <class _Tag, class _ExecutionPolicy, class _ForwardIterator, class _RandomAccessIterator, class _Compare>
_RandomAccessIterator
__pattern_partial_sort_copy(_Tag, _ExecutionPolicy&&, _ForwardIterator, _ForwardIterator, _RandomAccessIterator,
_RandomAccessIterator, _Compare) noexcept;
```
This issue has been introduced in the PR https://github.com/oneapi-src/oneDPL/pull/1239

Fix `__pattern_partial_sort_copy` forward declaration

---

test/general/sycl_iterator/sycl_iterator_find.pass.cpp
test/general/sycl_iterator/sycl_iterator_for.pass.cpp
test/general/sycl_iterator/sycl_iterator_reduce.pass.cpp
test/general/sycl_iterator/sycl_iterator_scan.pass.cpp
test/general/sycl_iterator/sycl_iterator_sort.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/binary.search/binary_search.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/lower.bound/lower_bound.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/upper.bound/upper_bound.pass.cpp
test/parallel_api/iterator/permutation_iterator_common.h
test/parallel_api/iterator/permutation_iterator_parallel_find.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_for.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_merge.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_or.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_partial_sort.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_stable_sort.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_transform_reduce.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_transform_scan.pass.cpp
test/parallel_api/iterator/transform_iterator.pass.cpp
test/parallel_api/iterator/zip_iterator.pass.cpp
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/scan_2.pass.cpp
test/support/utils_sycl.h
test/support/utils_test_base.h

Adds infrastructure to be able to shorten some commonly used test infrastructure by 
1) allowing scaling of the `max_n` (100000) and `small_n` (16)
2) allowing scaling of the step (3.14.15) multiplier 
This also corrects a potential error in the search_20 test of `sycl_iterator_find` which for some value of n, could return the incorrect result due to a unintentional extension of the searched for list by the nature of the input data.
A few tests were scaled in this PR to have fewer iterations with different sizes:
sycl_iterator_find
sycl_iterator_reduce
sycl_iterator_scan
sycl_iterator_sort
permutation_iterator_parallel_merge
permutation_iterator_parallel_stable_sort
Others were just given the opportunity for similar shortening.
These patterns should also be tested via their individual …

[Tests] Shorten sycl_iterator and permutation_iterator tests 

---

documentation/library_guide/kernel_templates/esimd/radix_sort.rst

Scan KT docs list iterators first, then ranges. Let's align the documentation.

[Doc] Swap buffer and pointer APIs to align with scan docs

---

include/oneapi/dpl/pstl/parallel_backend_tbb.h

[oneDPL][tbb] + memory leaks fix  (sort/stable sort, tbb backend)

[oneDPL][tbb] + memory leaks fix  (sort/stable sort, tbb backend)

---

make/Makefile

[oneDPL][make] + fix behavior (building exe file) in cases of non-dpcpp backends: -o<filename>.exe
Currently, oneDPL make file doesn't  build exe file (just compiles) in case of  non-dpcpp backends (tbb, omp, etc)
The PR introduces the change which  fixes that bug.

[oneDPL][make] + fix behavior (building exe file)  in cases of non-dpcpp backends

---

include/oneapi/dpl/experimental/kt/esimd_scan.h

This PR is targeting the ESIMD scan development branch.
This PR implements the reduce-then-scan approach in the ESIMD scan implementation reducing the ~4N global memory accesses to ~3N with a tradeoff of extra compute in the second kernel.
The following changes have been made:
-  `MAX_INPUTS_PER_BLOCK` has been adjusted to an empirically determined value. The prior value is based on what would be used in a single-pass implementation where we first load data into SLM and are limited by the SLM available per XE-core. We do not have this limit with the two-kernel implementation and processing `2^24` elements per block has yielded the best results in my experiments.
- `N` stores of partial prefix sums to global memory have been removed from the first kernel and an additional `prefix_sum` …

[KT] Implement reduce then scan optimization in ESIMD scan prototype

---

test/kt/CMakeLists.txt

`oneapi::dpl::experimental::kt::gpu::esimd_radix_sort*` currently supports only `workgroup_size` equal to `64`. There are no short-term plans to extend it with `32`. Let's remove `32` from testing.

[KT][Tests] Remove non-supported cases from testing (ESIMD sort)

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

In this error we fixing performance issue in the `__early_exit_find_or::operator()` :
- we should `break` `for`-loop after call `__found_local.store(1);`
This performance issue has been found during preparation of the PR https://github.com/oneapi-src/oneDPL/pull/1617

Performance improvements: insert `break` into `__early_exit_find_or`

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h

On certain accelerators, particularly NvGPUs with `sm_80` and `sm_90`, I have observed the following runtime exceptions in our single group radix sort:
```
terminate called after throwing an instance of 'sycl::_V1::nd_range_error'
what():  Exceeded the number of registers available on the hardware.
The number registers per work-group cannot exceed 65536 for this kernel on this device.
The kernel uses 144 registers per work-item for a total of 512 work-items per work-group.
-54 (PI_ERROR_INVALID_WORK_GROUP_SIZE) 
```
In the cases causing this crash, we attempt to use a sub-group size of 16 and pass an empty attribute to the kernel for compilation targets that we know do not have this support. The sub-group size of 16 gives a greater portion of register space to each work-item for use. The …

 Resolve register spills in dispatch of __subgroup_radix_sort

---

.github/workflows/ci.yml

The issue started happening after switching to oneAPI 2024.2. The root cause is currently unclear.
Upd. (June 21):
The issue is fixed by replacing: `intel-oneapi-runtime-dpcpp-sycl-fpga-emul` -> `intel-oneapi-compiler-fpga`.
I communicated with the maintainers of the packages and this is expected behaviour. FPGA emulator is not a part of oneAPI since 2024.2 and should be installed through `intel-oneapi-compiler-fpga`.

[CI] Fix FPGA emulator installation

---

README.md

This PR addresses https://github.com/uxlfoundation/open-source-working-group/issues/67 from the UXL Foundation and is part of the process of migrating oneDPL to the UXL Foundation.

Update README to introduce UXL identity and governance information.

---

include/oneapi/dpl/experimental/kt/two_pass_scan.h

This PR is targeted to the prototype branch for the reduce-then-scan implementation.
Previously, the implementation was reliant on work-group sizes being >= 1024 so that the number of sub-groups is divisible by the sub-group size. This PR generalizes the work-group size requirement and allows for the case where the number of sub-groups is not divisible by the sub-group size. There is a small performance penalty when this is the case.
Additionally, support has been added for performing sub-group scans when we do not have a full sub-group size of input via the `num_remaining` parameter and avoids the need to pad with identity elements.

[PROTOTYPE] Two-pass scan - Generalize work-group size support

---

README.md

This PR addresses the following items in the oneDPL migration to UXL Foundation governance:
https://github.com/uxlfoundation/open-source-working-group/issues/6
https://github.com/uxlfoundation/open-source-working-group/issues/11
https://github.com/uxlfoundation/open-source-working-group/issues/31

Add Slack information as a way to contact oneDPL developers.

---

include/oneapi/dpl/pstl/algorithm_fwd.h
include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/unseq_backend_simd.h

Scanning oneDPL code with a static analysis tool identified the two versions of a complex comparator in the SIMD unseq backend.  This PR removes the user-defined copy constructors since they are explicit versions of the default copy constructor to address the errors from the static analysis tool.
In addition the scans also identified two functions used in the implementation of uninitialized memory algorithms that were tagged with the noexcept keyword.  In the case of the uninitialized memory functors new may be called, in which case an exception could be thrown.

Addressing static analysis errors

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
test/kt/CMakeLists.txt

In this PR we implement break of for-loop inside `__early_exit_find_or` after first found element.
The approach from the PR https://github.com/oneapi-src/oneDPL/pull/1624 is applicable for the first/last element search.
This approach gives us a good performance boost.
Technically this `break` call implemented thought additional local variable with check inside of continue-condition in `for`-loop due performance results. 
Also in this PR, we analyze the result of `compare_exchange_strong()` call and break loop if the value of atomic has been changed correctly to avoid extra atomic value `load()` calls.

[Perf] Break loop in __early_exit_find_or after first found element

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

In this PR we using `fetch_min` / `fetch_max` in `__parallel_find_or` and it's stuff.
This approach give us additional performance boost:
- now we shouldn't try to setup atomic states inside `for`-based loops with additional checks.
This idea was proposed by @danhoeflinger.
Also in this PR we using `__dpl_ceiling_div` function where it's applicable in the code.

Using `fetch_min` / `fetch_max` in `__parallel_find_or` and in it's stuff

---

include/oneapi/dpl/experimental/kt/two_pass_scan.h
test/kt/two_pass_scan.cpp

This PR is targeted to the development branch for a new scan implementation.
I have done some evaluation of the scan implementation for the in-place case where the input and output buffers are the same. For inclusive scan, there are no issues with the current implementation. For exclusive scan, we have an issue in the multi-block case where we fetch the last element from the previous block's input to compute the current block's carry-in. In the in-place case, this input value would have been already overwritten with the exclusive scan value.
To fix this issue, the last input element in a block is written to temporary storage by the last sub-group's work item in the second kernel before the scan results are written and is then fetched by the next block. This operation does not add any …

[PROTOTYPE] Two-pass scan - Support in-place exclusive scans and update tests

---

documentation/library_guide/requirements.txt

https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies recommends explicitly pinning dependencies to reduce several security risks.
Line endings in the file were inconsistent so I converted them all to ASCII instead of a mix of CR and CRLF line endings.

Pinning dependencies per OSSF security practices and coverting to ASCII

---

test/support/utils_sycl.h

Previously `sycl::buffer` tests rans from `test1buffer`, `test2buffers`, `test3buffers` and from `test4buffers` functions for each type of `alloc_type` template param: for `sycl::usm::alloc::shared` and for `sycl::usm::alloc::device`.
It's look like as extra overhead which we should avoid to reduce CI test time.
Now `sycl::buffer` tests runs only for `alloc_type` template param equal to `sycl::usm::alloc::shared` (by default).

Avoid extra sycl::buffer tests

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h

In this PR we doing the next things:
1) Only declaration required as `make_wrapped_policy` template param
2) For aligning we declare these things always as `struct`.
The goal - to align these structures: their body isn't required.
And we have a lot of the same structures without body.
For example, 
```C++
template <typename Name>
class ExclusiveScan1;
template <typename Name>
class ExclusiveScan2;
```
and so far and so on.

Only declaration required as make_wrapped_policy template params

---

.github/workflows/ci.yml

MacOS 11 was removed from GitHub CI on June 28 according to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners. It has been replaced with MacOS 13.
Intel® C++ Compiler Classic Release was discontinued in the oneAPI 2024.0 release. It's been replaced with Clang++, which tends to be a default c++ compiler on MacOS.

[CI] Update MacOS version, move to Clang++ from ICPC

---

.github/workflows/ci.yml

Intel(R) oneTBB: 2021.12 -> 2021.13
Intel(R) oneAPI DPC++/C++ Compiler: 2024.1 -> 2024.2

[CI] Update links to download oneTBB and DPC++ compiler

---

.github/ISSUE_TEMPLATE/1_ask-a-question.md
.github/ISSUE_TEMPLATE/2_bug-or-performance-issue-report.md
.github/ISSUE_TEMPLATE/3_feature_request.md
.github/ISSUE_TEMPLATE/4_documentation_change.md

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax specifies that the keys for form fields use lowercase names.  This PR changes field names back to lowercase to resolve errors in deployment of the issue templates.

Revert capitalization of field names to resolve syntax errors in forms.

---

documentation/library_guide/kernel_templates/esimd/radix_sort.rst
documentation/library_guide/kernel_templates/esimd/radix_sort_by_key.rst
documentation/library_guide/kernel_templates/single_pass_scan.rst
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h

This follows the same approach as the scan KT and adheres the standard c++ algorithms convention regarding memory allocation issues, for example: "If the algorithm fails to allocate memory, [std::bad_alloc](https://en.cppreference.com/w/cpp/memory/new/bad_alloc) is thrown (see https://en.cppreference.com/w/cpp/algorithm/sort)

[KT] radix_sort: throw bad_alloc upon memory allocation issues

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

In this PR we remove local (in-group) atomic usage from `__parallel_find_or` implementation:
- `__found_local` now is local variable (for each item);
- barriers doesn't required anymore;
- we updates the state of `__found_local` within one group through `__dpl_sycl::__reduce_over_group` operation :
```C++
__found_local = __dpl_sycl::__reduce_over_group(__item_id.get_group(), __found_local,
typename _BrickTag::_LocalResultsReduceOp{});
```
where `_LocalResultsReduceOp` is :
- `__dpl_sycl::__minimum` (for the `__parallel_find_forward_tag`);
- `__dpl_sycl::__maximum` (for the `__parallel_find_backward_tag`);
- `__dpl_sycl::__bit_or` (for the `__parallel_or_tag`).
The new operation `__dpl_sycl::__bit_or` has been defined in the file [sycl_defs.h](https://github.com/oneapi-src/oneDPL/pull/1668/ …

Remove local (in-group) atomic usage from __parallel_find_or (V1)

---

.github/workflows/ci.yml

applied https://github.com/oneapi-src/oneDPL/pull/1479#discussion_r1670678370

using CPU instead of HOST in Distributed Ranges CI

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
test/general/fork.pass.cpp
test/support/utils_sycl.h

This patch is a follow-up to #1618 (with the commit history from there) with a somewhat modified approach. It is necessary to address #1631, one more issue caused by eager initialization of a SYCL queue in oneDPL headers. It still is supposed to address #1060.
The core idea is similar: to keep layout compatibility yet have lazy behavior, store SYCL queues inside a special `__queue_holder` class with the same size and alignment, and use the first `sizeof(uintptr_t)` bytes as a flag to detect if it holds a valid queue or - in case there are only zeros in these bytes - something else. To remind, 
> the rationale is that a SYCL queue is likely implemented as a shared_ptr (that's certainly the case for DPC++), which in turn typically holds several pointers to the actual object, a service block …

Resolve global policy issues in a backward-compatible manner, attempt 2

---

include/oneapi/dpl/experimental/kt/two_pass_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/utils.h
test/kt/two_pass_scan.cpp

This PR removes the identity requirement and the default constructor requirements from two_pass_scan to be more general so that it may cover more cases from mainline oneDPL.
It currently relies on a few strategies to do so:
1) Uses a lazy-constructing union in place of some value types. This allows us to avoid default construction, but allows variables to be scoped where we want them.  
2) delays creation of value type objects to interior scope, rather than reusing the same variable. 
3) Early exit for empty/ inactive workgroups, and properly avoiding empty / inactive subgroups for specific operations
** this seems to have the added benefit of performance improvement for small values of `n` **
4) Adapting the subgroup scan to make the `init_and_carry` parameter an optional input (as …

[PROTOTYPE] Removing identity and default construction requirement from two_pass_scan

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

In this PR, we implemented the early exit from search inside one sub-group in all sub-group items for find-based algorithms
(when we search for any matching data entry).
It's give us some significant performance boost.

Improvements of early exit for find-based algorithms (when we search for any matching data entry)

---

include/oneapi/dpl/experimental/kt/two_pass_scan.h

Our current check for if there is an init value assumes that `__no_init_value` will always provide a `__value_type` of `void`. As I've been integrating this code into the oneDPL SYCL backend, it seems that this is not always the case and the `__value_type` may be the actual input iterator's value type which leads to the wrong path being taken and compile time errors.
I have updated the check to determine if `InitType` is an instance of `__no_init_value`.

[PROTOTYPE] Fix check for __no_init_value when __no_init_value is used with a non-void value type

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

This PR based on idea of @danhoeflinger described at https://github.com/oneapi-src/oneDPL/pull/1689#discussion_r1672540484 from PR https://github.com/oneapi-src/oneDPL/pull/1689
In this PR, we implemented the early exit from search inside one sub-group in all sub-group items for find-based algorithms
(when we search for first/last matching data entry).
It's give us some significant performance boost.

Improvements of early exit for find-based algorithms (when we search for first/last matching data entry)

---

MAINTAINERS.md

The PR lists the lead maintainers for oneDPL and the areas for which they're primarily responsible.  Please suggest corrections to the areas as needed.
This addresses https://github.com/uxlfoundation/open-source-working-group/issues/11

Introducing list of maintainers and their lead areas.

---

cmake/oneDPLWindowsIntelLLVMApply.cmake

As discussed in :
https://github.com/oneapi-src/oneDPL/pull/1479#discussion_r1675897808
The comment for this cmake workaround was unclear, this PR should clarify things.

[CMake] Fix cmake workaround comment for clarity

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

We require the init type to be trivially copyable due to requirements imposed by `sycl::shift_group_[left|right]`. If this is not the case, then we must fallback to the legacy implementation.
By the point this check is added, `std::tuple` types will have already been repacked to `oneapi::dpl::__internal::tuple` allowing them to be trivially copyable.

[PROTOTYPE] Fallback to legacy scan implementation if underlying init type is not trivially copyable

---

include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

Summary
---
This PR changes the two pass algorithm to be more generalized for use with other scan-like algorithms like copy_if.
This PR adds copy_if as an example.  partition and unique patterns should follow easily.  Set algorithms have not been evaluated, but should also be possible.
Structural changes
---
The "bridge" between blocks now uses a saved carry-out value from the previous block (where it used to depend on the output of the previous block).  The output of the previous block only applies to transform_scan patterns, and not scan_copy algorithms.  It also required different logic for inclusive and exclusive scans.  The change to use the carry unifies this logic between inclusive and exclusive scans. 
The following operations have been defined to encode a generalized scan-like …

[PROTOTYPE] Generalized two pass algorithm and copy_if

---

include/oneapi/dpl/internal/random_impl/bernoulli_distribution.h
include/oneapi/dpl/internal/random_impl/cauchy_distribution.h
include/oneapi/dpl/internal/random_impl/discard_block_engine.h
include/oneapi/dpl/internal/random_impl/exponential_distribution.h
include/oneapi/dpl/internal/random_impl/extreme_value_distribution.h
include/oneapi/dpl/internal/random_impl/geometric_distribution.h
include/oneapi/dpl/internal/random_impl/linear_congruential_engine.h
include/oneapi/dpl/internal/random_impl/lognormal_distribution.h
include/oneapi/dpl/internal/random_impl/normal_distribution.h
include/oneapi/dpl/internal/random_impl/random_common.h
include/oneapi/dpl/internal/random_impl/subtract_with_carry_engine.h
include/oneapi/dpl/internal/random_impl/uniform_int_distribution.h
include/oneapi/dpl/internal/random_impl/uniform_real_distribution.h
include/oneapi/dpl/internal/random_impl/weibull_distribution.h
test/xpu_api/random/interface_tests/distributions_methods.pass.cpp
test/xpu_api/random/interface_tests/engines_methods.pass.cpp

There are the following requirements for operators <<, >> in C++ standard
- **for distributions**:
- **for engines**:
**Note:** llvm and gcc comply with the same requirements for distributions as for generators
Operator support was added for Bernoulli distribution and linear_congruential engine

[RNG] Adding operators ==, !=, << and >> for engines and distributions

---

README.md

https://github.com/uxlfoundation/open-source-working-group/issues/109 recommends oneDPL add its OSSF Scorecard badge. I'm also following the oneTBB approach of adding the license badge.

Add badges for license and OSSF Scorecard

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

We were throwing away the result and scratch container inside of the future in `__parallel_transform_scan` because we needed to return a future without storage. This was causing a use-after free error because the scratch storage was freed before it was used in the kernel.

[PROTOTYPE] Add unused temporary storage to single work-group scan to fix use-after free error

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

`zip_iterator.pass` runs into some compilation issues currently due to conversion issues between `std::tuple` and our internal tuple in cases in which they should be convertible but a compilation failure is still encountered. 
To fix this issue, we apply the same trick applied in the legacy `copy_if` implementation:  https://github.com/oneapi-src/oneDPL/blob/e3ebb58c1cc97261909c3bb3b47e4b3747be8dde/include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h#L618

[PROTOTYPE] Resolve conversion issues between internal tuple and std::tuple in zip_iterator.pass

---

include/oneapi/dpl/internal/distributed_ranges_impl/detail/sycl_utils.hpp

Replace a no-op `event` class only used in the multi-process execution model, which is not currently included.

Remove no-op event

---

.github/workflows/ci.yml
test/distributed_ranges/common/enumerate.cpp

This patch allows distributed ranges tests to be compiled with gcc-14. This is conflict fixed version of https://github.com/oneapi-src/oneDPL/pull/1697 PR from @BenBrock + removed workaround in CI

use internal version of enumerate in test to support gcc14

---

include/oneapi/dpl/pstl/algorithm_fwd.h
include/oneapi/dpl/pstl/algorithm_impl.h

Additional static analysis of oneDPL tests has identified other algorithms specified as 'noexcept' that may throw.  This PR extends similar work done in #1640.

Remove incorrect noexcept specifications from algorithms that may throw

---

.github/workflows/ci.yml

This PR proposes to upgrade the runners' versions to the latest OS to keep the CI running on current environments. This was noticed by @danhoeflinger in https://github.com/oneapi-src/oneDPL/pull/1479#discussion_r1670866048.
- Ubuntu 20.04 -> `ubuntu-latest` (currently 22.04)
- Windows Server 2019 -> `windows-latest` (currently 2022)
- macOS 13 -> `macos-latest` (currently 14)
It further upgrades the following GitHub actions:
- `actions/checkout`: warns about using deprecated Node.js 16
- `actions/setup-python`: warns about using deprecated Node.js 16
- `actions/upload-artifact`: warns about deprecation
I've also increased the build concurrency to 4 on Linux and Windows to match the core counts on the latest runners. This reduces the test times for these configurations.

Upgrade CI versions

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

This essentially implements this TODO:
> // TODO: move the whole loop to be a part of peer algorithms
This will allow adding one more peer algorithm which iterates over radix bits rather than radix states; or it will be easier to experiment at least.

Implement TODO: move the loop into peer algorithms

---

test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/support/utils.h

Previously, we used `std::complex` in the tests for `inclusive_scan_by_segment`, `exclusive_scan_by_segment`, and `reduce_by_segment` algorithms. The purpose of this was to test with some non-fundamental type. However, `std::complex` is technically not officially supported in SYCL kernels and failures in these tests over time have reflected the state of `std::complex` support as opposed to the actual correctness of the by_segment algorithms. We already have explicit tests for current `std::complex` in our testing suite, so I believe these should be fully separated from our parallel API tests. We also do not use `std::complex` throughout our other parallel API tests.
I've replaced these tests with tests over a custom 2D point type. Essentially, a similar option is performed as before but …

Replace usage of std::complex in by_segment tests

---

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h

Currently, we create our default  `sycl::queue` through providing `sycl::default_selector_v` to its constructor. Despite being apart of SYCL2020, this is problematic for some older compilers we still support and test with where this feature has not been implemented (e.g. icpx 2022.3):
```
error: no type named 'default_selector_v' in namespace 'sycl'; did you mean 'default_selector'?
static sycl::queue __q(sycl::default_selector_v);
```
The default constructor of `sycl::queue` guarantees that the default device will be selected, so relying on this resolves our issue.

Resolve compilation errors with sycl::queue default device selection for older icpx compilers

---

include/oneapi/dpl/internal/random_impl/discard_block_engine.h
include/oneapi/dpl/internal/random_impl/linear_congruential_engine.h
include/oneapi/dpl/internal/random_impl/subtract_with_carry_engine.h

Since `operator>>` takes the engine with template parameters for `subtract_with_carry_engine` and `discard_block_engine` classes we have multiple competing definitions in the same namespace when 2 or more of these engine types are instantiated.
Therefore, it's necessary to move the definition outside of the class, then it's only defined once, and add its declaration before the class definition.

[RNG] Fixed failures in ranlux_24_48_base and ranlux_24_48 tests of subtract_with_carry and discard_block engines

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

In this PR we prepare single work-group implementation of `__parallel_find_or` :
- they doesn't used `atomic`-based synchronization;
- they doesn't used `syc::buffer` for return result when USM-memory is available on device (we using `__result_and_scratch_storage` prepared by @julianmi earlier);
- kernel's compilation has been removed from `__parallel_find_or` and their staff.
This approach gives us a big performance boost for small data sizes.

Single WG implementation of `__parallel_find_or`

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
test/general/implementation_details/device_copyable.pass.cpp

Optimization for Unique.  Avoid branch at every dereference of the input range to specialize for the zeroth element. 
Ended up uglier than I expected to avoid an "empty" scan.  
We may be better off special casing the `n=1` case, which would allow us to get rid of a lot of the checks for positive `__active_subgroups`.
Draft to show for comment.  Need another pass for polish and formatting.  May want to rethink it a bit as well as mentioned above.

[PROTOTYPE] Optimization for unique

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

In this PR I propose the way how to avoid double dereference in Kernel code inside  function `__work_group_reduce_kernel` .
Double dereference has place here in Kernel's code in cases when we pass into this function simple `pointer` : we pass it by reference.
This problem also demonstrated in example, prepared by @julianmi : https://godbolt.org/z/rP7WbW94o
```C++
template <typename _Res>
void __kernel1(const _Res __res_acc){
//  mov rax, qword ptr [rbp - 8]
// mov dword ptr [rax], 0
*__res_acc = 0;
}
template <typename _Res>
void __kernel2(const _Res& __res_acc){
// mov rax, qword ptr [rbp - 8]
// mov rax, qword ptr [rax]
// mov dword ptr [rax], 1                  <<< EXTRA INSTRUCTION due we pass pointer by reference
*__res_acc = 1;
}
template <typename _Res>
void __kernel3(const _Res …
```

Fix double dereference in the function `__work_group_reduce_kernel`

---

.github/workflows/ci.yml

temprorarily disabled all tests except DR ones to speed up applying DR review comments
change to be reverted

limited CI

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
test/general/implementation_details/device_copyable.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/unique.pass.cpp
test/support/utils_device_copyable.h

Adds partition, unique families as well as the ranges API to use two pass scan.
There is some refactoring to the generalized helpers, to simplify sharing between families of scan-like algorithms using this.  
Otherwise, this just adds other entry points to use two pass scan.
This also standardizes / adds some zero element short circuits in the ranges API
Note:  for the ranges API, I try to hook in to the path to re-use what we have in the main APIs.  Specifically, this enables ranges API copy_if to be able to use single workgroup copy_if as well, where it was not previously exposed to that.
Tentative performance results for these families of algorithms are similar to what we have seen with copy_if.

[PROTOTYPE] partition, unique families and ranges API

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp

This PR cleans up the code and resolves a few outstanding TODOs:
- `int` loop variables have been changed to `std::uint32_t` to match oneDPL style.
- `__ndi.barrier()` has been replaced with `__dpl_sycl::__group_barrier(__ndi);`. The performance concern comments have been removed since this is a known, broader issue in oneDPL and we do not use many barriers.
- Some clang-format changes have been applied.
- Removed comment on SLM checks. SYCL requires 32 KB minimum SLM which is far higher than what we require in any circumstance.
- Only adjust `__inputs_per_sub_group / __inputs_per_item` on second to last block.
- Removed stray comment left in `exclusive_scan_by_segment.pass.cpp`

[PROTOTYPE] Cleanup reduce-then-scan code

---

include/oneapi/dpl/internal/reduce_by_segment_impl.h
include/oneapi/dpl/internal/scan_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

Several algorithms query the maximum supported work-group size with `__max_work_group_size`. Some devices such as the FPGA emulator might return arbitrary numbers. This can lead to issues with huge resource usage such as SLM or increased runtimes. E.g., resulting test timeouts were observed in https://github.com/oneapi-src/oneDPL/pull/1653.
This PR proposes to limit the value returned by `__max_work_group_size` to the highest correct limit of our tested production hardware architectures. 8192 is observed for `opencl:cpu`, discrete GPUs have typically 1024, and integrated GPUs 512.
This change also allows to provide a custom limit if desired by the caller. This is useful if a specific algorithm shows higher throughputs due to less used hardware resources or reduced communication costs when …

Limit the maximum work-group size

---

documentation/CHANGES.rst
documentation/library_guide/macros.rst
documentation/library_guide/parallel_api/execution_policies.rst
include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h

In this PR Declare predefined `dpcpp_default` and `dpcpp fpga` policies as `const`.
I hope it's may help to implement move-constructor and move-assignment in the PR https://github.com/oneapi-src/oneDPL/pull/1652 properly.
PR with the changes for oneDPL specification: https://github.com/uxlfoundation/oneAPI-spec/pull/554

Declare predefined `dpcpp_default` and `dpcpp fpga` policies as `const`

---

include/oneapi/dpl/internal/distributed_ranges_impl/detail/segments_tools.hpp
include/oneapi/dpl/internal/distributed_ranges_impl/detail/std_ranges_shim.hpp
test/distributed_ranges/include/common_tests.hpp

@BenBrock @lslusarczyk
In this patch I propose to support ranges-v3 in a different manner.
The "common" DR code in oneDPL would support redefinition of the `stdrng` namespace alias, as well as the `_ONEDPL_DR_STD_RANGES_NAMESPACE` macro (the patch also removes one extra leading underscore for that macro, to fit oneDPL naming rules).
Providing alternative definitions for ranges-v3 would be done in the "standalone" DR repository, like below:
```
// File: dr/detail/ranges_v3_shim.hpp
#pragma once
// In order to use ranges-v3 instead of C++20 ranges,
// #define _ONEDPL_DR_STD_RANGES_SHIM_HEADER <dr/detail/ranges_v3_shim.hpp>
// before including oneDPL DR headers
#include <range/v3/all.hpp>
namespace stdrng = ::ranges;
#define _ONEDPL_DR_STD_RANGES_NAMESPACE ranges
```
The macro …

Move the use of ranges-v3 to "standalone" DR

---

include/oneapi/dpl/internal/distributed_ranges_impl/sp/algorithms/exclusive_scan.hpp
include/oneapi/dpl/internal/distributed_ranges_impl/sp/algorithms/inclusive_scan.hpp
test/distributed_ranges/sp/CMakeLists.txt

This update is probably fine, but needs to be tested on PVC.  Currently having difficulty compiling due to lack of frontend compiler bug in Clang/lack of GCC-14, which includes [a workaround](https://github.com/gcc-mirror/gcc/commit/be34a8b538c0f04b11a428bd1a9340eb19dec13f).

Updates from Adam's comments

---

test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/support/test_config.h

This PR is put up in anticipation of the reduce-then-scan implementation being committed. It can currently be produced on `dev/shared/reduce_than_scan_impl`.
When using the new reduce-then-scan implementation, a correctness issue has been identified on Windows with `reduce_by_segment.pass.cpp`. The issue can only be produced with the current ordering of test cases (and I assume ordering in which kernels are compiled). After running the two flag predicate tests, the third `MatrixPoint` test return incorrect results. We run into this issue even if the flag predicate tests are not run and their kernels only compiled. Reordering the tests to run the `MatrixPoint` test prior to the flag predicate tests, or completely removing the flag predicate tests results in a pass.
We believe this issue …

Workaround Windows correctness issue in reduce_by_segment.pass

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/utils.h

One of the changes to the upcoming scan rework (#1762) is to move the helper union `__lazy_ctor_storage` out of the reduce header into the main utils header, as it will eventually be used in scan as well. 
This PR makes that movement, as well as adds a few helper methods to `__lazy_ctor_storage`.
---
This PR is a part of the following sequence of PRs meant to be merged in order:
#1769 Relocate __lazy_ctor_storage to utils header (This PR)
#1770 Use __result_and_scratch_storage within scan kernels
#1762 Add reduce_then_scan algorithm for transform scan family
#1763 Make Copy_if family of APIs use reduce_then_scan algorithm
#1764 Make Partition family of APIs use reduce_then_scan algorithm
#1765 Make Unique family of APIs use reduce_then_scan algorithm
This work is a collaboration between …

Relocate __lazy_ctor_storage to utils header

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

This PR adjust existing scan kernels to use `__result_and_scratch_storage` rather than a temporary buffer for both scratch space and for the return within the resulting future.
This is important because: 
1) It should be faster (as evidenced from previous work with reduce)
2) It serves as plumbing in preparation for the upcoming `reduce_then_scan` kernels which utilize this structure for temporary and return storage.  Since we have runtime branches selecting which algorithm to use (existing scan, single wg scan, single wg copy_if, and soon reduce_then_scan), these all need to have the same return future type.  This means they should all use `__result_and_scratch_storage` for their return (and therefore also any temporary storage).
Single WG scan does not have a return or temporary …

Use __result_and_scratch_storage within scan kernels

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

This patch extends `__result_and_scratch_storage` to support cases where no result space is required. This removes the overhead of allocating result storage even when it is unneeded such as in the dummy container introduced in #1770. The signature is kept intact to support the different scan kernels.
There is also some code cleanup and the usage in reduce is aligned with the recently merged scan. The container is also passed by reference to the reduce kernels to prevent copies.

Support scratch space without result space

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h

In this PR we fix double reference in `__device_reduce_kernel` param `__temp_acc`:
- we have only one call of `__device_reduce_kernel` and we pass into `__temp_acc` param simple pointer in all cases:
```C++
auto __temp_ptr =
__result_and_scratch_storage<_ExecutionPolicy2, _Tp>::__get_usm_or_buffer_accessor_ptr(
__temp_acc);
// ...
__device_reduce_kernel<_Tp>(..., __temp_ptr, ...);
```
where `__get_usm_or_buffer_accessor_ptr` is :
```C++
template <typename _Acc>
static auto
__get_usm_or_buffer_accessor_ptr(const _Acc& __acc, ::std::size_t __scratch_n = 0)
{
#if _ONEDPL_SYCL_UNIFIED_USM_BUFFER_PRESENT
return __acc.__get_pointer();
#else
return &__acc[__scratch_n];
#endif
}
```

Fix double reference in `__device_reduce_kernel` param

---

documentation/library_guide/kernel_templates/single_pass_scan.rst

After revisiting the code for the scan kernel template, we discovered that the algorithm is only synchronous in the non-single-work-group case. The documentation should be amended slightly to note of this discrepancy.

Update scan kernel template documentation to note single-work-group is asynchronous

---

test/parallel_api/algorithm/alg.nonmodifying/equal.pass.cpp

This PR skips the custom `UserType` test of `std::equal` for dpcpp backends.
This is done because `UserType` is not [device copyable](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec::device.copyable) (and shouldn't be explicitly specialized to be device copyable).  It has a custom copy assignment operator which is **not the same as a bitwise copy of the object**.  
Instead of changing this custom type to be device copyable, we instead skip this test to avoid conflicts with LLVM upstream.

[test] Skip std::unique UserType test for dpcpp backend

---

test/parallel_api/algorithm/alg.sorting/partial_sort_copy.pass.cpp

Making `Num<T>` device copyable.  
It obeys the rules as a type but was not specialized explicitly as device copyable.

[test] Marking Num device copyable for partial_sort_copy.pass

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h

Targeting to be included in #1762. This PR adjusts the block size to be bigger or smaller based on the input type.

Adjust block size for reduce-then-scan based on input type

---

test/support/test_config.h

Version 2025.0.0 of icpx will still has the issue when combined with MSVC STD implementation comparing std::optional, std::pair etc.
Updating the version broken macro to reflect this.

[test] Update broken macro for comparison

---

include/oneapi/dpl/experimental/kt/internal/esimd_defs.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_utils.h

Our ESIMD radix sort has two issues with newer compilers:
1. We unnecessarily use the `template` keyword prior to calling a function without a template argument list. This causes compilation failures with newer compilers. This has been fixed by removing `template` in this instance.
2. The `sycl::ext::intel::esimd::sw_barrier` enumerator has been removed and as far as I am aware there is no other ESIMD equivalent. We have a note that these `sw_barrier` fences are for performance reasons. There is one fence in the inter-wg synchronization that I believe is necessary for correctness (I see a hang otherwise). However, it should use a global memory fence and not a software barrier as we need ordering of reads which are from global memory. I have removed the other sw_barrier fences and do not …

Resolve ESIMD sort KT compilation failures with new compiler

---

test/kt/CMakeLists.txt

The PR removes a `single_pass_scan` target, which is a duplicate of `single_pass_scan_dpwi8_wgs256_uint32`.
The main motivation is to have all the targets under `build-scan-kt-tests`/`run-scan-kt-tests` umbrellas for easier test automation.

[test] Remove single_pass_scan target duplicate

---

include/oneapi/dpl/pstl/iterator_impl.h
include/oneapi/dpl/pstl/onedpl_config.h

oneDPL's iterators like `zip_iterator`, `transform_iterator`, `permutation_iterator` can all use `sycl_iterator` as a source iterator, but `sycl_iterator` does not allow dereference.  
This PR makes the `operator*` require `std::indirectly_readable` for our iterators when c++20 concepts exist.  This fixes a bug in windows MSVC STL which was previously unable to correctly determine if a `transform_iterator<sycl_iterator>` is dereferenceable.
In practice, we never use the dereference because it is converted to the appropriate accessor for use within a kernel by our input data processing.  However, we do not control if STL implementations might try to use dereference, so we must make sure they can correctly determine if it is available.

Iterators C++20 disable `operator*` when it invalid

---

include/oneapi/dpl/experimental/kt/internal/esimd_defs.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h

Let's keep the radix_sort working with [Intel® oneAPI DPC++/C++ Compiler](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-dpc-c-compiler-release-notes.html) 2023.2. Some users may still use it.

[KT] Keep support of icpx 2023 for radix sort

---

test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp

The change fixes a warning:
> #warning "CL/sycl.hpp is deprecated, use sycl/sycl.hpp"

[test] Fix warning in inclusive_scan_by_segment.pass.cpp

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
include/oneapi/dpl/pstl/utils.h

This PR introduces oneapi::dpl::__internal::__compare which replace a lambda in hetero __parallel_stable_sort pattern

[oneDPL] + oneapi::dpl::__internal::__compare

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
test/general/implementation_details/device_copyable.pass.cpp
test/support/utils_device_copyable.h

This PR adds copy_if family to use reduce_then_scan algorithm where it is beneficial.
Moves all algorithm selection decisions to `__parallel_copy_if`, and unifies range API to also use this function.  Adding support for an assignment operator for single work group copy_if.  This allows us to unify the algorithmic selection, and provide performance improvements to the ranges API.
Adds `__parallel_reduce_then_scan_copy` function which will be used by partition and unique in the future to take advantage of shared functionality.
---
This PR is targeted to #1762, to allow for a clean diff, and is a part of the following sequence of PRs meant to be merged in order:
#1769 [MERGED] ~~Relocate __lazy_ctor_storage to utils header~~
#1770 [MERGED] ~~Use __result_and_scratch_storage within scan …

Make Copy_if family of APIs use reduce_then_scan algorithm

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
test/general/implementation_details/device_copyable.pass.cpp

This PR changes partition family of scan-like algorithms to use reduce_then_scan where it is beneficial.
Moves all algorithm selection decisions to __parallel_partition_copy.
---
This PR is targeted to #1763, to allow for a clean diff, and is a part of the following sequence of PRs meant to be merged in order:
#1769 [MERGED] ~~Relocate __lazy_ctor_storage to utils header~~
#1770 [MERGED] ~~Use __result_and_scratch_storage within scan kernels~~
#1762 Add reduce_then_scan algorithm for transform scan family
#1763 Make Copy_if family of APIs use reduce_then_scan algorithm
#1764 Make Partition family of APIs use reduce_then_scan algorithm (This PR)
#1765 Make Unique family of APIs use reduce_then_scan algorithm
This work is a collaboration between @mmichel11 @adamfidel and @danhoeflinger, and …

Make Partition family of APIs use reduce_then_scan algorithm 

---

include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
test/general/implementation_details/device_copyable.pass.cpp
test/support/utils_device_copyable.h

This PR changes the unique family of scan-like APIs to use reduce_then_scan when it is beneficial.
This PR allows us to remove `__pattern_scan_copy` functions because they are no longer used.  
We have moved the algorithm decisions to go through at the level of `__parallel_[copy_if/partition/unique]_copy`, so we no longer need the "scan_copy" at the pattern level.
Moves all algorithm selection decisions to `__parallel_unique_copy`, and unifies range API to also use this function. This allows us to unify the algorithmic selection, and provide performance improvements to the ranges API.
Unique requires some `constexpr` special casing in the kernel to allow us to avoid an extra branch for each element in the `_GenMask` for unique to avoid underflow when `index == 0`.  We special case the …

Make Unique family of APIs use reduce_then_scan

---

include/oneapi/dpl/internal/random_impl/uniform_real_distribution.h
test/xpu_api/random/device_tests/common_for_device_tests.h

When trying to build the test `test/xpu_api/random/device_tests/engine_device_test.pass.cpp` with enabled macro `TEST_LONG_RUN` , the following error appears:
`...
/oneDPL/include/oneapi/dpl/internal/random_impl/uniform_real_distribution.h:277:29: error: use of overloaded operator '-' is ambiguous (with operand types 'std::enable_if_t<!std::is_same_v<vec_data_t<DataT>, vec_data_t<float>> && !std::is_same_v<detail::ConvertToOpenCLType_t<vec_data_t<DataT>>, detail::ConvertToOpenCLType_t<vec_data_t<float>>>, vec<float, 1>>' (aka 'sycl::vec<float, 1>') and 'scalar_type' (aka 'unsigned long'))
277 |                 ((__res_tmp - __engine.min()) / (1 + static_cast<scalar_type>(__engine.max() - __engine.min()))) *
|                   ~~~~~~~~~ ^ ~~~~~~~~~~~~~~`

[RNG] Conversion fixes in uniform real distribution

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h

As discovered in https://github.com/oneapi-src/oneDPL/pull/1762#discussion_r1730044386, there is a mismatch in the return type for the transform scan pattern. A similar issue exists with `copy_if`. This PR uses the difference type of the output range as the size type for `n` to match the return type of the patterns.

Fix return type of transform scan and copy if patterns

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h

As noted by a comment from @dmitriy-sobolev https://github.com/oneapi-src/oneDPL/pull/1621#discussion_r1739290933
after the PR was merged, there was a problem with the forward declaration of `__compare` in that is was misaligned with the definition of the struct. 
The PR resolves it.
@rarutyun  if we want to make any other changes to `__compare` here for ranges, we can.

Bug fix for fwd definition of __compare in sycl_traits.h

---

test/support/test_config.h

This PR consolidates the "Latest" macros into one place, to indicate where we currently are experiencing an issue from another library, compiler, etc.  so we want to skip certain broken tests, but not skip them indefinitely and forget about them.
The idea will be to have a task to revisit this section at least once every oneDPL release and audit the usages of these "Latest" macros to see if the issue is still present.  Any issues which have been fixed should be frozen to the last broken version.  Then once we have done this audit, we should update the macro in this location to the most recent version of the external entity.
This will help mark these "Latest" macros in the code explicitly, and also have a list of such instances to re-check prior to each release to help avoid …

[Tests] Consolidate "Latest" macros; update broken macros

---

include/oneapi/dpl/pstl/histogram_extension_defs.h
include/oneapi/dpl/pstl/histogram_impl.h

Reorder histogram template parameters and remove unused default template argument.
One option for specification of histogram (version 1a from email).

Reorder histogram template parameters

---

test/xpu_api/random/conformance_tests/philox_test.pass.cpp
test/xpu_api/random/unit_tests/philox_unit_test.pass.cpp

These guards are necessary to filter out some testing, they were forgotten to be added in the initial PR.
Also, 2 unnecessary headers were noticed in the test, they were removed.

[RNG] Added compilation guards for `philox_test.pass` and `philox_unit_test.pass`

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/onedpl_config.h

Remove non-used `_ONEDPL_CPP20_SPAN_PRESENT`, and do some stylistic changes.

Code cleanup (ranges)

---

test/xpu_api/containers/sequences/array/array.comparison/greater_g.pass.cpp
test/xpu_api/containers/sequences/array/array.comparison/greater_or_equal_g.pass.cpp
test/xpu_api/containers/sequences/array/array.comparison/less_g.pass.cpp
test/xpu_api/containers/sequences/array/array.comparison/less_or_equal_g.pass.cpp

With newer MSVC versions, we see compilation errors such as:
```
error: SYCL kernel cannot call an undefined function without SYCL_EXTERNAL attribute
334 |         return __std_mismatch_4(_First1, _First2, _Count);
|                ^
```
which occurs when vectorized MSVC algorithms are attempted to be called from within a SYCL kernel. This is showing up with array comparisons within kernels.
To resolve this issue, we can set `_USE_STD_VECTOR_ALGORITHMS=0` which has already been applied to similar tests.

[test] Use macro workaround to avoid calling vectorized MSVC algorithms from within a SYCL kernel

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h

This is a first patch towards improving the throughput of the merge algorithm especially for large input arrays. It includes minor improvements and code cleanups. Increasing the chunk size for large inputs increases the GPU memory throughput. The speedup for large arrays increases to about 1.8x for 2^28 elements on PVC.

Tune merge launch config

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h
include/oneapi/dpl/pstl/utils.h

This PR based on issue https://github.com/oneapi-src/oneDPL/issues/1469
In this PR we rewrite the destructor of `struct __lifetime_keeper_base` :
- instead of empty body we rewrote it as `= default;`
Why it's better: https://isocpp.org/blog/2015/04/quick-q-how-is-default-different-from-for-default-constructor-and-destructo

Fix __lifetime_keeper_base destructor

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

Previously, an IGC workaround has caused kernels compiled with `[[sycl::reqd_sub_group_size(32)]]` to be silently compiled with size 16 sub-groups with `-O0` on certain devices. To comply with the SYCL spec, this case will now throw a synchronous exception at JIT time.
Single work-group radix sort uses a sub-group sizes of 32 for the smallest inputs and 16 for larger inputs to minimize register pressure. I have experimented with the current mainline version, a version only using sub-group size of 16, and a version removing the requirement altogether. The first two versions performed similarly with no measurable difference, and explicitly requiring a sub-group size of 16 offered up to a ~15% benefit over the version with no requirement at all.
By using only sub-group sizes of 16 in single …

Always use size 16 sub-groups in single work-group radix sort if supported

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h

Tests with other benchmarks and devices has shown mixed results for the tuning proposed in #1826. This reverts the tuning until we've found a smarter approach that takes the device and input data characteristics into account.

Revert merge algorithm chunk size tuning due to mixed results

---

test/support/test_complex.h

In this PR we remove `TestUtils::invoke_test_if` from tests :
- starting from C++17  we can use `if constexpr` instead.

Remove `TestUtils::invoke_test_if` and some extra macros from tests

---

include/oneapi/dpl/pstl/execution_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h

When oneDPL is compiled without spirv, code in parallel_backend_sycl_radix_sort_one_wg.h causes unused variable error, so removing this variable should help.
Presence of function definitions in header files sometimes causes multiple definitions error, changing them to inline should solve the issue

Fix warning and compilation errors

---

include/oneapi/dpl/internal/binary_search_impl.h

Issue: https://github.com/oneapi-src/oneDPL/issues/1436
In this PR we fix implementations of the `lower_bound_impl`, `upper_bound_impl` and `binary_search_impl`:
- the way they were implemented before doesn't match Tag Dispatching design because they has called public `oneDPL` algorithms instead of internal pattern calls.

Fix implementations of `lower_bound_impl`, `upper_bound_impl` and `binary_search_impl` functions

---

test/CMakeLists.txt
test/general/multiple_translation_units/header_umbrella.h
test/general/multiple_translation_units/multiple_translation_units.pass.cpp
test/general/multiple_translation_units/translation_unit1.cpp
test/general/multiple_translation_units/translation_unit2.cpp

The newly added test checks for ODR violations.
There are two object files including all oneDPL public headers which are linked with another one which contains `main` and does nothing.
It addresses #1229.

[tests] Multiple translation units

---

test/support/utils.h
test/xpu_api/algorithms/alg.sorting/alg.binary.search/binary.search/partitioned_g1.pass.cpp
test/xpu_api/algorithms/alg.sorting/alg.binary.search/lower.bound/partitioned_g2.pass.cpp
test/xpu_api/algorithms/alg.sorting/alg.binary.search/upper.bound/partitioned_g.pass.cpp

Issue: https://github.com/oneapi-src/oneDPL/issues/1382
In this PR we fixing value comparisons in oneDPL tests: the goal is to compare `floating point` values through `std::numeric_limits<T>::epsilon()` precision usage.

Fix comparison of expected and actual values in tests

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/support/test_dynamic_load_utils.h
test/support/test_dynamic_selection_utils.h

Issue: https://github.com/oneapi-src/oneDPL/issues/1216
In this PR we remove some unrequired `typename` keywords from oneDPL code and tests.

[oneDPL][tests] Remove unrequired `typename` keywords

---

include/oneapi/dpl/internal/random_impl/philox_engine.h
test/general/multiple_translation_units/header_umbrella.h

`<oneapi/dpl/random>` relies on namespace lookup mechanism which does not work well in some cases. There are compilation issues if `<oneapi/dpl/dynamic_selection>` is included first.
Simplified reproducer of the issue with the namespace lookup:
```
namespace dpl::experimental::internal{}
namespace dpl {
namespace internal {
template <typename T>
void feature() {}
}
namespace experimental {
template <typename U>
void test() {
internal::feature<U>();
}
}
}
>>  error: no template named 'feature' in namespace 'dpl::experimental::internal'; did you mean '::dpl::internal::feature'?
```
dynamic_selection adds `oneapi::dpl::experimental::internal` namespace, and a compiler stops looking for other namespaces after encountering it. Hence, it fails to find entities such as …

Fix namespace lookup issues in <oneapi/dpl/random> header

---

documentation/index.rst
documentation/library_guide/api_for_sycl_kernels_main.rst
documentation/library_guide/conf.py
documentation/library_guide/dynamic_selection_api/policies.rst
documentation/library_guide/dynamic_selection_api_main.rst
documentation/library_guide/index.rst
documentation/library_guide/kernel_templates/esimd_main.rst
documentation/library_guide/kernel_templates_main.rst
documentation/library_guide/parallel_api/async_api.rst
documentation/library_guide/parallel_api_main.rst

The patch restructures the table of content to better organized documentation topics. It also does related minor changes such as page reordering and title modifications.

Improve the tables of content

---

documentation/CHANGES.rst
documentation/library_guide/introduction.rst
documentation/library_guide/kernel_templates/esimd/radix_sort.rst
documentation/library_guide/kernel_templates/esimd/radix_sort_by_key.rst
documentation/library_guide/kernel_templates/kernel_configuration.rst
documentation/library_guide/kernel_templates/single_pass_scan.rst
documentation/release_notes.rst

The link to the specification in the introduction is updated. The links in change logs are removed, as the specification rule which the logs refer to has been removed since then.
Additionally, I looked at other links and made some modifications, particularly for the links to the SYCL specification, and a few other cosmetic improvements.

[doc] Fix or remove outdated links to the oneDPL specification

---

documentation/library_guide/dynamic_selection_api/auto_tune_policy.rst
documentation/library_guide/dynamic_selection_api/dynamic_load_policy.rst
documentation/library_guide/dynamic_selection_api/fixed_resource_policy.rst
documentation/library_guide/dynamic_selection_api/functions.rst
documentation/library_guide/dynamic_selection_api/policies.rst
documentation/library_guide/dynamic_selection_api/round_robin_policy.rst
documentation/library_guide/dynamic_selection_api_main.rst
documentation/library_guide/introduction.rst
documentation/library_guide/kernel_templates/esimd/radix_sort.rst
documentation/library_guide/kernel_templates/esimd/radix_sort_by_key.rst
documentation/library_guide/kernel_templates/single_pass_scan.rst
documentation/library_guide/parallel_api/iterators.rst

Instead of `.. code:: none` directive (or the one with no language), it is better to use so-called literal blocks (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#rst-literal-blocks) for output, command lines etc.
And vice versa, for code samples it is better to use the directive, not a literal block.

[doc] Use code directives for code and literal blocks for output

---

documentation/library_guide/kernel_templates/esimd/radix_sort.rst
documentation/library_guide/kernel_templates/esimd/radix_sort_by_key.rst
documentation/library_guide/kernel_templates/esimd_main.rst

The information is partially outdated. Additionally the set of the supported systems matches what the compiler/driver stack supports, that is why I suggest omitting it.

Remove system requirements section for ESIMD-based KT

---

test/general/multiple_translation_units/header_umbrella.h

Bugfix for multi translational units test.
Ranges header can only be included in combination with certain STL versions, we need to guard the ranges header include.

[Test] Fix for ranges testing in multi translational units

---

include/oneapi/dpl/experimental/kt/single_pass_scan.h

Single pass scan neglects to use `__dpl_sycl::__local_accessor` which causes problems when used with older versions of the SYCL library.  This is causing some errors in the multiple translation unit tests when used with older compilers.
This PR fixes that issue.

Use __dpl_sycl accessor in single pass scan

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/iterator_impl.h
include/oneapi/dpl/pstl/utils_ranges.h
test/support/test_config.h

A couple of changes lurking in my working copy, plus the changes for unused variables from #471 that still apply, and dropping colons before `std` in the code around.

Cleaning up a few places in the code

---

rfcs/README.md
rfcs/archived/README.md
rfcs/experimental/README.md
rfcs/proposed/README.md
rfcs/supported/README.md
rfcs/template.md

The proposed RFC structure and process generally match those recently accepted by oneTBB (see oneapi-src/oneTBB#1464) with some modifications, primarily just in the description. To see only the modifications, exclude the first commit when viewing the changes.

Add the directory structure for RFC documents

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h

`sycl::mode_tag_t` is not a part of SYCL 2020. It was a part of the provisional specification, but it is absent in the newer revisions. 
There is a more radical approach: remove seemingly unused `access_mode` from `sycl_iterator` class entirely, but I am not sure about design / ABI implications.
Note, that the host_task tags (such as `read_write_host_task`) were not added, because they are not currently supported, and there is no sense to do so. The oneDPL specification suggest that the `begin` and `end` functions should be  provided during code submission to a device, which is not applicable within a host task context:
> The begin and end functions can take SYCL 2020 deduction tags and sycl::no_init as arguments to explicitly mention which access mode should be applied to the buffer …

Align with SYCL 2020: remove sycl::mode_tag_t

---

test/parallel_api/numeric/numeric.ops/scan_2.pass.cpp

scan algorithms are defined in `numeric` header instead of `algorithm`.

Fix includes in scan_2 test

---

include/oneapi/dpl/pstl/execution_defs.h
include/oneapi/dpl/pstl/glue_algorithm_ranges_defs.h
include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/glue_numeric_ranges_defs.h
include/oneapi/dpl/pstl/glue_numeric_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
include/oneapi/dpl/pstl/utils_ranges.h

Utilities for Range API should be in `utils_ranges.h` instead of `execution_defs.h`.

Move difference_t utility to utils_ranges header

---

include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/onedpl_config.h

1. Microsoft standard libraries older than _MSC_VER == 1939 have std::ranges::<algo> definition as function instead of a global function object. It leads to a error in oneDPL implementation. The PR fixes this issue via a workaround. https://godbolt.org/z/sTfcsj897
2.  Added _ONEDPL_STD_RANGES_WINDOWS_NON_GLOBAL_FUN_OBJ  macro

[oneDPL][ranges] + fix for std::ranges::sort using (windows); 

---

include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/onedpl_config.h

[oneDPL][ranges] A macro `_ONEDPL_STD_RANGES_FUN_OBJ_WINDOWS_BROKEN `renamed to `_ONEDPL_STD_RANGES_ALGO_CPP_FUN`

[oneDPL][ranges] A macro _ONEDPL_STD_RANGES_FUN_OBJ_WINDOWS_BROKEN renamed

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h

Attempting to use a `sycl::read_only` access tag results in a compilation error with code such as the following:
```
#include <iostream>
#include <oneapi/dpl/algorithm>
#include <oneapi/dpl/execution>
#include <oneapi/dpl/iterator>
#include <sycl/sycl.hpp>
int main()
{
sycl::buffer<int> buf1(1);
{
buf1.get_host_access()[0] = 2;
}
sycl::buffer<int> buf2(1);
auto beg1 = oneapi::dpl::begin(buf1, sycl::read_only);
auto end1 = oneapi::dpl::end(buf1, sycl::read_only);
auto beg2 = oneapi::dpl::begin(buf2, sycl::write_only);
oneapi::dpl::copy(oneapi::dpl::execution::dpcpp_default, beg1, end1, beg2);
std::cout << buf2.get_host_access()[0] << std::endl;
}
```
The single member of the read only specialization of `__access_mode_resolver` just needs to be updated to `__value` to be consistent with its …

Correct member name of `__access_mode_resolver` to address compilation issues

---

include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
include/oneapi/dpl/pstl/glue_numeric_impl.h

The PR's aim is to fix #1886.
#1886 reproduces when oneDPL headers are included in the following order:
```
#include <oneapi/dpl/execution>
#include <oneapi/dpl/algorithm>
#include <oneapi/dpl/numeric>
```
The reason appears to be that  `glue_numeric_impl.h` is included before `glue_numeric_defs.h` in `inclusive_scan_by_segment_impl.h`, what means that `reduce` uses `transform_reduce`, which is defined later.
Unfortunately, I was not able to reproduce the issue with a simple reproducer (outside of the distributed-ranges context), to come up with a new test.

Fix inclusion order of numeric header

---

include/oneapi/dpl/pstl/utils_ranges.h

The PR includes all the necessary standard headers while fixing the issue:
```bash
utils_ranges.h:81:23: error: 'uint8_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
```

Include all necessary standard headers in utils_ranges.h

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h

This PR implements a TODO:
```
// TODO: split the submitter into multiple ones to avoid extra compilation of kernels:
// - _LeafSortKernel and _CopyBackKernel do not need _IndexT
```
It results in reduced kernel compilation times. The table below shows a JIT compilation speed up for different devices:
  | Named Kernels: JIT speedup, times | Unnamed Kernels: JIT speedup, times
-- | -- | --
Intel® Data Center GPU Max Series   (zeModuleCreate calls) | 1.18 | 1.61
Intel(R) Xeon(R) Platinum 8480+   (clBuildProgram calls) | 1.26 | 1.85
There is no observable impact on the execution time besides kernel compilation.
I used the following program as a benchmark:
```
#include <sycl/sycl.hpp>
#include <oneapi/dpl/algorithm>
#include <oneapi/dpl/execution>
#include <iostream>
#include <algorithm>
int …
```

Reduce the number of kernels to compile in merge-sort

---

test/general/test_policies.pass.cpp

Closes #1901.
The oneDPL specification has recently changed (https://github.com/uxlfoundation/oneAPI-spec/pull/567) to move `is_execution_policy` and `is_execution_policy_v` from the `oneapi::dpl::execution` namespace to `oneapi::dpl`. This PR changes the tests to use the struct in the `oneapi::dpl` namespace for testing.

Modify is_execution_policy test to reflect change in specification

---

include/oneapi/dpl/internal/random_impl/philox_engine.h
test/xpu_api/random/unit_tests/philox_unit_test.pass.cpp

**What introduces this PR:**
1. Fix for the incorrect counter incrementing in case `w` is not the recommended value (`w!=32` and `w!=64`)
2. `discard_overflow_test` was extended: previously only the first chunk of the counter was overflowing, now introduced the high-level loop, which iterates through the other positions of the counter(2nd and 3rd) and also checks for the overflow.
3. Introduced a new unit test - `counter_management_test`. 
- The testing is based on comparing the work of two different methods of the engine - simple `set_counter` and more complicated `increase_counter_internal(unsigned long long __z)` which is called by `discard`
- The test discards the engine by the increment which takes at least 2 chunks of the counter type(`2*w`) - this way `increase_counter_internal` …

Fixed coverity issue in Philox RNG engine

---

test/general/test_policies.pass.cpp

A straightforward fix would be to add missing `>`. However, testing the `fpga_policy` as it is looks a better choice due to being a basic case. I guess the change in #1907 with wrapping  `fpga_policy` into `device_policy` was a typo.

Fix test_policies for FPGA

---

include/oneapi/dpl/internal/random_impl/philox_engine.h
test/xpu_api/random/unit_tests/philox_unit_test.pass.cpp

**Fixed failed unit test details:**
```
void counter_management_test() [Engine = philox2x32_w18] failed
void counter_management_test() [Engine = philox2x32_w30] failed
void counter_management_test() [Engine = philox4x32_w18] failed
void counter_management_test() [Engine = philox4x32_w30] failed
```
- The problem appeared only under Windows, because `in_mask` is of type `scalar_type`, which is for failed cases`uint_fast32_t`  -  the bitsize of this type is implementation-defined and differs on Windows(4 bytes) and Linux(8 bytes). On Windows the higher bits of the increment were removed by  `(~in_mask)`, that is why some unit tests failed.
- Lower bits of the shifted counter are removed by shift operation anyway, so the masking operation is not necessary there.
**Fixed warning in test …

[RNG] Fixed warnings in Philox tests build and test failures under Windows

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h

Fixes #1922. You can find elaborate description of the issue there.
It appears that `_Proj`, a lambda declared in `__pattern_sort_by_key` template, will have different types for different `__patter_sort_by_key` instantiations:
https://github.com/oneapi-src/oneDPL/blob/28cb633583570457a2e21a752f6a517f5fc7134a/include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h#L1274-L1275
Here is a simplified example of a lambda having different types in different function template instantiations: https://godbolt.org/z/ddrM6Tseq

Make kernel names unique in radix sort 

---

CMakeLists.txt
test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp

`transform_binary.pass` with the OpenMP backend in debug builds has been timing out. This is caused by testing of forward and bidirectional iterators. When no compiler optimization is present, a large number of re-computation of iterators occurs in this line: https://github.com/oneapi-src/oneDPL/blob/66ead74ff6db1eb7e047227086da836531499a74/include/oneapi/dpl/pstl/omp/parallel_for_each.h#L40 which has an expensive cost for iterators without random access. In release builds, there is no problem due to compiler optimization.
The test is updated to reduce test sizes in this timeout case. I have also updated our `CMakeLists.txt` to set the `PSTL_USE_DEBUG` macro for OpenMP builds as well.

[test] Reduce test input sizes for debug builds with OpenMP in `transform_binary.pass`

---

test/parallel_api/algorithm/alg.modifying.operations/shift_left_right.pass.cpp

We have recently seen timeouts in CI in `shift_left_right.pass` when running on CPUs with large core counts using the OMP backend. This has occurred mostly with debug builds but also in a small number of release builds. Due to the small problem sizes in our tests, the grain size per thread is too small when a large number of threads are launched resulting in significant performance loss due to excessive parallelism and cross-socket traffic.
To resolve this issue, we cap the number of threads to `32` in `shift_left_right.pass` which enables the tests to pass in a reasonable time while also launching enough threads to assess the correctness of the parallel implementation.

[test] Limit the number of launched threads in `shift_left_right.pass` with the OMP backend to avoid timeouts

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
test/general/implementation_details/device_copyable.pass.cpp

Allow passing a non-trivially-copyable comparator to sort

---

test/general/implementation_details/device_copyable.pass.cpp
test/support/utils_device_copyable.h

It turns out that the internal range type is instantiated with older ICPX compiler versions (2024.0 and older). The error:
```c++
In file included from oneDPL/test/general/implementation_details/device_copyable.pass.cpp:18:
In file included from oneDPL/include/oneapi/dpl/execution:67:
In file included from oneDPL/include/oneapi/dpl/pstl/algorithm_impl.h:26:
In file included from oneDPL/include/oneapi/dpl/pstl/execution_impl.h:22:
In file included from oneDPL/include/oneapi/dpl/pstl/parallel_backend.h:32:
In file included from oneDPL/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h:34:
oneDPL/include/oneapi/dpl/pstl/hetero/dpcpp/../../utils_ranges.h:115:52: error: no matching function for call to '__check_size'
using __difference_t = …
```

Fix device_copyable test

---

include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
test/parallel_api/ranges/std_ranges_adjacent_find.pass.cpp
test/parallel_api/ranges/std_ranges_all_of.pass.cpp
test/parallel_api/ranges/std_ranges_any_of.pass.cpp
test/parallel_api/ranges/std_ranges_count.pass.cpp
test/parallel_api/ranges/std_ranges_count_if.pass.cpp
test/parallel_api/ranges/std_ranges_equal.pass.cpp
test/parallel_api/ranges/std_ranges_find.pass.cpp
test/parallel_api/ranges/std_ranges_find_if.pass.cpp
test/parallel_api/ranges/std_ranges_find_if_not.pass.cpp
test/parallel_api/ranges/std_ranges_is_sorted.pass.cpp
test/parallel_api/ranges/std_ranges_max_element.pass.cpp
test/parallel_api/ranges/std_ranges_min_element.pass.cpp
test/parallel_api/ranges/std_ranges_none_of.pass.cpp
test/parallel_api/ranges/std_ranges_search.pass.cpp
test/parallel_api/ranges/std_ranges_search_n.pass.cpp
test/parallel_api/ranges/std_ranges_sort.pass.cpp
test/parallel_api/ranges/std_ranges_stable_sort.pass.cpp
test/parallel_api/ranges/std_ranges_test.h
test/support/test_macros.h

[oneDPL][ranges][tests] a fix for std::ranges::sort using with Windows C++ standard library.
This PR is a sequel for https://github.com/oneapi-src/oneDPL/pull/1885.

[oneDPL][ranges][tests] a fix for std::ranges::<algo> using with Windows C++ standard library.

---

test/parallel_api/ranges/std_ranges_test.h
test/parallel_api/ranges/std_ranges_test_views.pass.cpp

The PR introduces the checks for following standard view adapters:
- transform_view
- reverse_view
- take_view
- drop_view
NOTICE: std::ranges::views::all, std::ranges::subrange, std::span are tested implicitly within the 'test_range_algo' test engine.
single_view - is a trivial view and it doesn't  make sense for testing in the parallel code.

[oneDPL][ranges][test] + test_range_algo::test_view functionality

---

test/kt/esimd_radix_sort.cpp
test/kt/esimd_radix_sort_by_key.cpp
test/kt/esimd_radix_sort_by_key_out_of_place.cpp
test/kt/esimd_radix_sort_out_of_place.cpp
test/kt/single_pass_scan.cpp
test/support/utils.h

Let's test if we allow the compiler to generate unique kernel names for a default kernel name case.

Improve kernel name generation for unnamed lambda (kernel templates)

---

CONTRIBUTING.md
MAINTAINERS.md

As part of the process of adopting UXL governance this PR introduces the roles developers may fill in the project and the process of moving into roles with increased responsibility and privilege.  The work is based on the process defined by [oneDNN](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md) and what has been proposed for [oneTBB](https://github.com/oneapi-src/oneTBB/pull/1560).

Defining developer roles, responsibilities, and privileges and leadership process

---

CMakeLists.txt

Let's use -fsycl only if it is supported by a compiler.

[Cmake] Make SYCL detection more portable

---

documentation/library_guide/onedpl_gsg.rst

The PR adds notes to the Getting Started Guide on installing the oneAPI for NVIDIA GPUs plugin as well as a reference to the System Requirements section of the Developer's guide for the installation requirements to run oneDPL on CPU.  This is meant to provide the documentation requested in https://github.com/uxlfoundation/open-source-working-group/issues/51 on how to use oneDPL on different vendor hardware platforms.

Adding information on how to use oneDPL on other vendor platforms

---

include/oneapi/dpl/internal/version_impl.h
test/general/version.pass.cpp

`main` still shows 2022.7.0 and the same holds for the 2022.7.1 release tag, see https://github.com/oneapi-src/oneDPL/blob/oneDPL-2022.7.1-release/include/oneapi/dpl/internal/version_impl.h. In particular, this hinders me from testing the changes related to the fixes in  https://github.com/oneapi-src/oneDPL/pull/1927 and https://github.com/oneapi-src/oneDPL/pull/1932 (easily).

Update version to 2022.7.1

---

README.md

There previous one, https://github.com/oneapi-src/oneDPL/blob/release_oneDPL/CONTRIBUTING.md, is outdated.

Show relevant CONTRIBUTORS.md on the main page

---

.github/workflows/ci-docs.yml
.github/workflows/ci-testing.yml
CONTRIBUTING.md
README.md
documentation/library_guide/notices_disclaimers.rst
examples/convex_hull/README.md
examples/dot_product/README.md
examples/random/README.md

The reliance on the `release_oneDPL` branch for documentation appears to be a historical artifact. This PR removes its usage.

Avoid using release_oneDPL branch

---

rfcs/README.md
rfcs/experimental/README.md
rfcs/proposed/README.md
rfcs/supported/README.md
rfcs/template.md

Following an internal team discussion, this PR updates the RFC documentation to reflect that
- at any state proposals can be developed iteratively in several revisions;
- there is no single strictly defined flow, and each state can be skipped;
- "umbrella" documents might be simultaneously in a few states, as necessitated by the progress of sub-features.

RFC process clarification

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
test/parallel_api/numeric/numeric.ops/reduce_by_segment_zip.pass.cpp

For differing input and output key / value types, we cannot store an input element into a variable that is the output type. This is especially important for discard iterators in the output where we are met with a compile-time error if we attempt to store an input into this type as it can hold no value.
A test case has been added which combines zip and discard iterators. This catches the compilation issue before the fix.

Bugfix for reduce-by-segment with differing input and output types

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

Code sections which use `sycl::sub_group::<load()|store()>` DPC++ extension are not entirely disabled. Non-template expressions are still checked by a compiler even if they are within a discarded `if constexpr` branch. 
This makes the code non-compatible with compilers other than DPC++, and it results in a deprecation warning with the most recent DPC++ builds.
A mock-up example: https://godbolt.org/z/svhnY14r5

Do not use deprecated sub-group load/store extension

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

`__local_mem_size` may differ from `_Size` in some cases leading to "error: call to 'min' is ambiguous".

Fix ambiguous call to sycl::min

---

CONTRIBUTING.md
README.md
SECURITY.md
documentation/CHANGES.rst
documentation/library_guide/_templates/layout.html
documentation/library_guide/conf.py
documentation/library_guide/index.rst
documentation/library_guide/introduction/onedpl_gsg.rst
documentation/library_guide/notices_disclaimers.rst
documentation/library_guide/onedpl_gsg.rst
documentation/release_notes.rst
examples/convex_hull/README.md
examples/dot_product/README.md
jenkinsfiles/RHEL_Check.groovy
jenkinsfiles/UB18_Check.groovy
jenkinsfiles/UB20_Check.groovy
jenkinsfiles/Windows_Check.groovy

This PR should be merged after the migration of the oneDPL repository to the UXL Foundation GitHub organization.  It corrects URLs in the documentation, examples, and Jenkins files (not currently used) to point to the correct location.

Change repo organization from oneapi-src to uxlfoundation.

---

README.md
documentation/library_guide/dynamic_selection_api/dynamic_load_policy.rst
examples/random/README.md
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h
test/parallel_api/algorithm/alg.sorting/alg.min.max/minmax_element.pass.cpp
test/parallel_api/ranges/std_ranges_test.h
test/parallel_api/ranges/transform2_ranges_factory_sycl.pass.cpp
test/parallel_api/ranges/transform2_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform_ranges_factory_sycl.pass.cpp
test/parallel_api/ranges/transform_ranges_sycl.pass.cpp
test/support/test_complex.h
test/xpu_api/cmath/nearbyint/xpu_nearbyint.pass.cpp
test/xpu_api/containers/sequences/array/zero_sized_arrays_g.pass.cpp
test/xpu_api/utilities/meta/meta.rel/is_convertible.pass.cpp

The codespell scan on #1992 identified several spelling errors in the repository -- https://github.com/uxlfoundation/oneDPL/actions/runs/12658581533/job/35275850152?pr=1992
This PR corrects those errors and updates two URLs in documentation where the oneapi-src organization was not replaced with uxlfoundation.

Fix spelling errors

---

rfcs/archived/asynchronous_api_general/readme.md
rfcs/proposed/asynchronous_api_general/readme.md

The proposal aims at designing a consistent approach to asynchronous execution that would be utilized by various APIs of oneDPL, such as asynchronous algorithms and dynamic selection.
Update: the decision was made not to proceed with the proposal, the PR is now for wrapping up and archiving.
The associated discussion: #1917

RFC to design a unified oneDPL approach to asynchrony

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

In this PR we remove usage of `__kernel_name_generator` from `__parallel_find_or` as not required.
We should avoid to use `__kernel_name_generator` for not-compiler Kernels (when absent the call of `__kernel_compiler` in the code) due a lot of char codes in template names.
For example we may see these names with char codes from VTune.
- when you will check the differences for this PR, please **Hide whitespace**.
Otherwise you will see a lot of unsignificant changes due the formatting has been changed.
Thanks.

Remove usage of `__kernel_name_generator` as not required for non-compiled Kernel's

---

test/support/test_config.h

Updating the macro version, since these tests fail with newer compiler versions (icpx 2025.0.4 and internal builds for the next release).
Some values were also changes:
- `_PSTL_LAMBDA_PTR_TO_MEMBER_WINDOWS_BROKEN`: set to <20250200 since the update is expected with that compiler version.
- `_PSTL_TEST_COMPARISON_BROKEN` and  `_PSTL_RED_BY_SEG_WINDOWS_COMPILE_ORDER_BROKEN`: set <20250100 since the issues do not reproduce with icpx 2025.0.
- `_PSTL_ICPX_FPGA_TEST_USM_VECTOR_ITERATOR_BROKEN` was set to <20250100 since it is expected to be fixed with that version (not-verified yet, but we can raise the version in the future if needed).

Update broken macro for XPU tests

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h

On some implementations, the max subgroup size is 1, which is too small for the sorting algorithm to produce correct results. Make the value at least 4.

Ensure `__max_sg_size` is at least 4 in sort

---

documentation/library_guide/api_for_sycl_kernels/tested_standard_cpp_api.rst
test/xpu_api/language.support/support.types/nullptr_t.pass.cpp

The initial motivation was to replace `cl_int`, which should not be used, at least in a generic code parts due to being specific to OpenCL backend. Since it involves changing the Tested API example, I prefer to update other parts of it because it is outdated.

Modernize Tested API example, replace cl_int

---

include/oneapi/dpl/internal/scan_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/onedpl_config.h

Disable kernel compilation if it is not supported. For instance, ACPP does not support kernel bundles, nor `sycl::program`, which appears to be a former DPC++ feature or an artifact from previous SYCL revisions.

Make kernel compilation logic more portable

---

include/oneapi/dpl/pstl/histogram_binhash_utils.h

The PR fixes a warning:
> histogram_binhash_utils.h:108:23: warning: unused variable '__num_bins' [-Wunused-variable]

Fix unused variable warning

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h

In this PR we fix compile errors in `__serial_merge` function for case when the types of `__rng2` and `__rng1` aren't the same:
```C++
/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h:162:17: error: conditional expression is ambiguous; '__return_t' (aka 'const oneapi::dpl::__internal::tuple<unsigned long, unsigned long>') can be converted to 'decltype(this->make_reference(::std::declval<_tuple_ranges_t>(), __i, ::std::make_index_sequence<__num_ranges>()))' (aka 'tuple<const unsigned long &, const unsigned long &>') and vice versa
162 |                 ? __rng2[__rng2_idx++]
|                 ^ ~~~~~~~~~~~~~~~~~~~~
163 |                 : __rng1[__rng1_idx++];
|                   ~~~~~~~~~~~~~~~~~~~~
/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h:198: …
```

Fix compile error in `__serial_merge`

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
test/general/implementation_details/device_copyable.pass.cpp

The ValueType should not be necessary for device copyability because it is not a member field of the helper struct.  It is only the return value of the callable.  Therefore, we should not base device copyability on it.
(Not fixing any reported bug here, just saw this as I was looking at sycl traits for some use case ideas, but I believe it is correct.)

Bugfix for device copyable of unique copy helper

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h

This is the second attempt of https://github.com/uxlfoundation/oneDPL/pull/2013: the source compile error has been introduced in the PR https://github.com/uxlfoundation/oneDPL/pull/1970
Example of the source compile error: https://godbolt.org/z/x6z7GMv1W
In the PR https://github.com/uxlfoundation/oneDPL/pull/2013 I detected performance issue.
The goal of this PR - to use ternary operator when it's possible.
Checks on GodBold: 
1) https://godbolt.org/z/6zPcWEMsn - implementation with `__assing_impl`
2) https://godbolt.org/z/fdsPdoPz3 - implementation without `__assing_impl`
Thanks to @MikeDvorskiy and @dmitriy-sobolev for their implementations of `__can_use_ternary_op_v` !

Fix performance issue in `__serial_merge`

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
test/parallel_api/algorithm/alg.sorting/alg.set.operations/set_common.h

On certain integrated graphics architectures, sub-group sizes of 32 are not supported for kernels with certain properties when compiled with -O0 using the `icpx` compiler. The compiler is normally able to workaround this issue by compiling to a sub-group size of 16 instead. However, in cases in which an explicit sub-group size is required, then the compiler throws an exception at JIT time. This issue directly affects our reduce-then-scan implementation which has a required sub-group size of 32.
To properly work around this issue, several things must be done. Firstly, exception handling is implemented to catch this synchronous exception while re-throwing any other exceptions back to the user. Secondly, after discussion with compiler developers, kernel compilation must be separated from …

Work around crashes and incorrect results in scan-based algorithms when compiling with -O0

---

.github/workflows/ci-docs.yml

Python 3.13 deprecates `imghdr`, which is still used until Sphinx 6.2. https://github.com/python/cpython/issues/104818
We could upgrade Sphinx from 4.4->6.2 but it seems like we have limited Sphinx at 4.4 it there for some other reason.  For now, lets just limit python to a version (3.12) which works.

[Docs] Explicit python 3.12 for sphinx and imghdr

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

This adds a using statement to define `__result_and_scratch_storage`   which does the decay of the execution policy for the caller, and makes the actual type `__result_and_scratch_storage_impl`.
I'm not sure I like this, because it "hides" the decay of the policy.  It certainly makes usage easier, but also obfuscates what is really happening here. 
What do you guys think?

Improve usage Pattern for result_and_scratch_storage

---

include/oneapi/dpl/pstl/algorithm_impl.h

__out is a macro in Microsoft C++ SAL (Source Annotation Language).
We cant use it as a variable name.  Causes compiler errors for microsoft platforms.

Bugfix to avoid `__out` for MSVC

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h

https://github.com/uxlfoundation/oneDPL/pull/2031 reverted the change in https://github.com/uxlfoundation/oneDPL/pull/1997 which always passed execution policies through reduce-then-scan as const l-value references. After this, we began to see duplicate kernel name compilation errors in `scan_2.pass`.
This observed bug is caused by the fact that the execution policy is passed to the submitter function objects as a forwarding reference in the reduce-then-scan submitters. This means that even though the kernel names have been properly generated to be "unique", different cv / ref qualifiers of the execution policy will lead to separate function template instantiations and will be submitting separate kernels as a result. This subtle issue results in duplicate kernel names even if the kernels …

Fix duplicate kernel naming in reduce-then-scan kernels

---

include/oneapi/dpl/pstl/omp/util.h
include/oneapi/dpl/pstl/parallel_backend_serial.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h
include/oneapi/dpl/pstl/parallel_backend_utils.h

`tbb/enumerable_thread_specific.h` includes an indirect inclusion of windows.h on windows.  
This is undesirable, and therefore we would like to avoid it.  Without enumerable_thread_specific to depend upon in TBB, we can instead unify all implementations into a shared one which uses a pair of helpers: 
`__get_thread_num()`
and  
`__get_num_threads()` 
which are passed to the shared implementation from the parallel backends as template arguments during creation in the make function.  
We implement a make function for each backend to properly pass in the appropriate helper functions for the parallel backend. We no longer need to bury the __enumerable_thread_local_storage in a `__details` namespace, since all backends could in theory directly use the constructor if they fill out all the …

Implement unified ETLS without TBB and use it for all host backends

---

include/oneapi/dpl/pstl/omp/util.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h
include/oneapi/dpl/pstl/parallel_backend_utils.h

This patch returns to the CRTP-based implementation, with a workaround applied to make the VS 2017 C++ compiler happy.
But more importantly, it addresses two other issues: stores the construction arguments as a tuple of values (by removing references from the deduced types) and replaces `unique_ptr` with `optional` to avoid memory allocations.

Improve the implementation of __enumerable_thread_local_storage

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
include/oneapi/dpl/pstl/onedpl_config.h

GCC defines the `__OPTIMIZE__` macro which evaluates to `1` if compiler optimizations are enabled, and is `0` otherwise. Similarly, clang does not seem to explicitly document it, but it exposes an `__OPTIMIZE__` macro with the same semantics as GCC's. This same macro is defined in the Intel LLVM based compiler. We can use this knowledge to implement the reduce-then-scan `-O0` workaround with no performance penalty by switching the required sub-group size to `16` when optimizations are not present.

Implement alternative `-O0` workaround for reduce-then-scan with compiler optimization detection

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

This changes the global barrier's fence spaces for histogram  catch all which uses global atomics and no SLM.
I'm not sure if we want to add this in right now, or take care of this after the release.  
This is only used when the number of histogram bins is very large as compared to the memory space of the device.
If we have any question marks here, lets wait on these changes.

Global barrier fence histogram fix

---

documentation/library_guide/macros.rst
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

Value (`__buf_val`) and Count (`__buf_count`) buffers store data in either local or global memory. Let's use group barriers with proper fences (local or global memory fences) to avoid memory contention issues, which are observed on Xe2 architectures.
The fix changes how `__group_barrier` is defined, so the PR additionally includes what is done in #1988 to avoid conflicts and fix another issue related to the barriers: we use SYCL 1.2.1 barriers, but oneDPL claims to be SYCL 2020 compatible.

Fix synchronization issues in radix sort and histogram

---

test/parallel_api/algorithm/alg.modifying.operations/alg.reverse/reverse.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.reverse/reverse_copy.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/copy_move.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/fill.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/generate.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/replace.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/replace_copy.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/rotate.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/rotate_copy.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/swap_ranges.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/transform_unary.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/for_each.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/transform_if.pass.cpp
test/parallel_api/numeric/numeric.ops/adjacent_difference.pass.cpp
test/support/utils.h

The input sizes used for testing for-based algorithms is dependent on the number of execution units on the SYCL queue. This approach was used to ensure we generate large enough inputs to test the large for submitter path in oneDPL. A hard cap is set at 10,000,000 elements which is sufficient to test the large submitter path on high-performance GPUs with many EUs.
However, we recently spotted that this approach results in test timeouts on client GPUs such as BMG and Arc in debug mode. To fix this issue, a new approach has been added for debug mode to avoid such timeouts while ensuring a single test case for the large submitter path. The "normal" set of inputs is used (factors of PI up to 100k elements) followed by a single test case above the threshold to invoke the large submitter.  For …

[test] Reduce for algorithm testing with debug builds to prevent timeouts

---

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h

PR #1976 introduced a circular dependency between `oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h` and `oneapi/dpl/pstl/ranges_defs.h`. This shows up as an issue in kernel templates where the following produces a compiler error:
```
#include <oneapi/dpl/experimental/kernel_templates>
int main()
{
}
```
In `utils_ranges_sycl.h`, the include was added to be able to use `__nanorange::nano::ranges::contiguous_range`, so we can fix this by directly including the nanorange header. This resolves the circular dependency and the compilation issue.

Fix circular dependency between utils_ranges_sycl.h and ranges_defs.h

---

.github/workflows/scorecard.yml

With the move to uxlfoundation the OSSF scorecard scans previously automatically performed on oneapi-src repos are no longer being done for oneDPL.  This PR reintroduces the OSSF scan to ensure we continue to follow OSS security best practices.

Reintroduce OSSF Scorecard scan for the repo in scorecard.yml

---

.github/scripts/job_summary.py
.github/workflows/ci-testing.yml

Addresses #1850, with #1994 being an additional motivator.
This PR adds `-Wall` (for GCC/Clang/ICX/ICPX) and `/W4` (for MSVC) compiler flags to detect various warnings, such as unused variables, dangerous type conversions and other.
The number of warnings is large to the extent it can be challenging to navigate through the log files. To address this, the PR also adds a summary for each CI job to simplify analysis of their outputs.
The summary looks like:
and can be found on the [actions tab](https://github.com/uxlfoundation/oneDPL/actions/runs/13393516011?pr=1996).

Report more warnings, summarize job output

---

include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h
include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
include/oneapi/dpl/pstl/histogram_binhash_utils.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h
include/oneapi/dpl/pstl/parallel_impl.h

The PR fixes warnings, where the fix is the most straightforward one:
- -Wreorder-ctor
- -Wunused-variable
- -Wlogical-op-parentheses
- -Wunused-lambda-capture
- -Wunused-parameter
Examples of the messages:
1. dpl/pstl/algorithm_impl.h(387): warning C4100: '__exec': unreferenced formal parameter
3. oneDPL/include/oneapi/dpl/pstl/histogram_binhash_utils.h:68:29: warning: field '__num_bins' will be initialized after field '__range_size' [-Wreorder-ctor]
4. oneDPL/include/oneapi/dpl/pstl/parallel_backend_tbb.h:868:14: warning: unused variable '__ky' [-Wunused-variable]
5. oneDPL\include\oneapi\dpl\pstl\parallel_backend_tbb.h(887): warning C4189: '__ny': local variable is initialized but not referenced
6. oneDPL/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h:182:99: …

Fix various warnings in the library

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h

In this PR we remove direct usage of `kernel_name` type and using `oneapi::dpl::__internal::__policy_kernel_name` trait instead.

Remove direct usage of `kernel_name` type

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

Using sycl::min in this context leads to " error: no matching function for call to 'min'" with `acpp` for some reason. Let's switch to std::min for host code. Using sycl::min is not necessary.

Replace sycl::min with std::min in host code

---

.github/workflows/ci-testing.yml
CMakeLists.txt

Addresses #1945 by adding `RelWithAsserts` cmake configuration.
https://cmake.org/cmake/help/v3.31/manual/cmake-buildsystem.7.html#default-and-custom-configurations
Each configuration defines a set of compiler and linker flag variables for the language in use. These variables follow the convention `CMAKE_<LANG>_FLAGS_<CONFIG>`, where `<CONFIG>` is always the uppercase configuration name. When defining a custom configuration type, make sure these variables are set appropriately, typically as cache variables.
Additionally, I've noticed more configuration specific variables: `CMAKE_EXE_LINKER_FLAGS`, `CMAKE_MODULE_LINKER_FLAGS` and `CMAKE_SHARED_LINKER_FLAGS` investigating cache after ninja run (a single-config generator).

Add RelWithAsserts cmake config for testing

---

include/oneapi/dpl/internal/async_impl/glue_async_impl.h
include/oneapi/dpl/pstl/algorithm_ranges_impl.h
include/oneapi/dpl/pstl/glue_algorithm_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/utils.h

In this PR we fix two functors: `__transform_if_unary_functor` and `__transform_if_binary_functor` :
1) remove `&&` params qualifiers in constructor;
2) using `std::move` instead of `std::forward`.

Fix constructors of two `__transform_if_`-functors

---

test/support/iterator_utils.h

In this PR we fix `sizeLimit` type in tests to avoid warning about comparison signed and unsigned data types in tests for `g++` compiler.

Fix `sizeLimit` type in tests

---

test/general/implementation_details/internal_tuple.pass.cpp

Avoid comparing signed and unsigned integers in tests.

[Tests] Remove warnings in internal_tuple.pass signed unsigned comparison

---

include/oneapi/dpl/internal/async_impl/glue_async_impl.h
include/oneapi/dpl/pstl/algorithm_ranges_impl.h
include/oneapi/dpl/pstl/glue_algorithm_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

In this PR we remove extra changes, which we made earlier in the PR https://github.com/uxlfoundation/oneDPL/pull/2091

Restore std::move for constructors of `__transform_if_`-functors

---

test/parallel_api/ranges/exclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/find_ranges_sycl.pass.cpp
test/parallel_api/ranges/inclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/reduce_by_key_ranges_sycl.pass.cpp
test/parallel_api/ranges/zip_view.pass.cpp

It should fix the remaining warnings arising with [CPU,bknd=dpcpp,cmplr=icpx,ubuntu-latest,std=с++17,cfg=release](https://github.com/uxlfoundation/oneDPL/actions/runs/13680766496#summary-38252303253) configuration.

Fix unused variable and lambda capture warnings in device tests

---

.github/workflows/ci-testing.yml

There are 15 configurations under `linux-testing` umbrella. Let's assume they are numbered:
- 7th duplicates 6th
- 10th duplicates 8th
- 11th duplicates 3rd

Remove duplicated CI configurations

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h

In this PR we remove extra `std::move` call in the code:
```C++
template <typename _ValueT, typename _Wi, typename _Src, typename _Values>
static void
__block_load(const _Wi __wi, const _Src& __src, _Values& __values, const uint32_t __n)
{
_ONEDPL_PRAGMA_UNROLL
for (uint16_t __i = 0; __i < __block_size; ++__i)
{
const uint16_t __idx = __wi * __block_size + __i;
if (__idx < __n)
new (&__values[__i]) _ValueT(::std::move(__src[__idx]));
}
}
```
The justification - `__src` parameter declared `const reference`

Remove extra `std::move` call

---

.github/scripts/job_summary.py

This will also allow detecting warnings like that:
> warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]

Improve warning parsing in CI

---

documentation/library_guide/notices_disclaimers.rst
documentation/release_notes.rst

Final cherry pick for release notes.

cherry pick #2075

---

documentation/library_guide/common_cross_document_links.txt
documentation/library_guide/introduction/onedpl_gsg.rst
documentation/library_guide/onedpl_gsg.rst

@dcbenito notified me that the Yocto instructions have been removed from the IoT Toolkit and there's not a redirect or replacement available.  Removing the dead link from the getting started guide.

Removing invalid link to Yocto instructions.

---

test/parallel_api/algorithm/alg.modifying.operations/alg.partitions/is_partitioned.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/find.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/transform_if.pass.cpp
test/parallel_api/algorithm/alg.sorting/partial_sort.pass.cpp
test/parallel_api/dynamic_selection/test_auto_tune_policy_inline.pass.cpp
test/parallel_api/iterator/iterators.pass.cpp
test/parallel_api/iterator/permutation_iterator_parallel_stable_sort.pass.cpp
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/parallel_api/ranges/std_ranges_copy.pass.cpp
test/parallel_api/ranges/std_ranges_transform.pass.cpp
test/support/test_dynamic_selection_utils.h
test/support/test_offset_utils.h
test/support/utils_sort.h

It fixes warnings:
- `-Wunused-function`:
For example, |utils_sort.h:230:1: warning: unused function 'Equal'"
- `-Wunused-variable`
For example, transform_if.pass.cpp:198:26: warning: unused variable 'init_val'
- `-Wunused-local-typedef`
For example, transform_binary.pass.cpp:41:77: warning: unused typedef 'Out'
Additionally, the PR renamed `p` variable to `m` in `partial_sort.pass.cpp` to denote "middle" parameter and avoid variable shadowing with another `p` which means "number of processors". Also some macros were reordered in this test to avoid unused-variable warning.

Fix warnings in tests: unused variable, function, typedef

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h

We only use `__exec` once here, so we can forward the forwarding reference to the `__parallel_for` call from `__pattern_walk1`.

Forward execution policy in __pattern_walk1 of hetero backend

---

test/parallel_api/algorithm/alg.nonmodifying/all_of.pass.cpp

It fixes warning:
> all_of.pass.cpp:72:19: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]

Fix int-in-bool-context warning in all_of test

---

test/parallel_api/algorithm/alg.nonmodifying/any_of.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/none_of.pass.cpp

It fixes the same warning as in #2120, but in other tests which slipped my attention.

Fix int-in-bool-context warning in any_of and none_of

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h

The `_RangeTypes` variadic class template in `__parallel_for_large_submitter` is a remnant of an older prototype of the current implementation and unused, so we are able to remove it. Thanks @SergeyKopienko for pointing this out.

Remove unused class template from __parallel_for_large_submitter

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h

This PR fixes a warning:
> sycl_iterator.h(66,5): warning: definition of implicit copy constructor for 'sycl_iterator<sycl::access::mode::read, int>' is deprecated because it has a user-provided copy assignment operator [-Wdeprecated-copy-with-user-provided-copy]
The copy assignment operator was removed to avoid the warning. An implicitly generated operator will do the same operations.
Note, the change will allow an implicit generation of a move constructor and a move assignment operator. I see no issues here, rather the opposite, but I would like to highlight that in case you see any potential problems.

Fix deprecated-copy-with-user-provided-copy warning

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

The PR fixes:
> parallel_backend_sycl.h(1308,64): warning: missing field '__rng_transform' initializer [-Wmissing-field-initializers]
I believe that the original behavior was also correct, which relied on that[ aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization) rule:
> Otherwise, if the element is not a reference, the element is [copy-initialized](https://en.cppreference.com/w/cpp/language/copy_initialization) from an empty initializer list.
Hence, `__gen_mask{pred}` was an equivalent of `__gen_mask{pred, {}}` (but with the use of a copy constructor). It resulted in the warning, though.

Fix missing-field-initializers warning

---

test/parallel_api/iterator/transform_iterator.pass.cpp

In this PR we remove unused code - `struct test_copy_if`

Remove unused code from `struct test_copy_if`

---

test/parallel_api/algorithm/alg.merge/inplace_merge.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.copy/copy_if.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.partitions/is_partitioned.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.partitions/partition.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/alg.partitions/stable_partition.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/remove.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/replace.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/replace_copy.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/transform_unary.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/unique.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/find_end.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/find_first_of.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/find_if.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/for_each.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/nth_element.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/search_n.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.heap.operations/is_heap.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.lex.comparison/lexicographical_compare.pass.cpp
test/parallel_api/algorithm/alg.sorting/partial_sort_copy.pass.cpp
test/support/utils.h

Remove `invoke_if()` function in tests: this function simple calls their argument and looks like not required:
```C++
template <typename Policy, typename F>
static void
invoke_if(Policy&&, F f)
{
f();
}
```
In tests we simple replaces their calls with arguments to direct calls:
- before:
```C++
invoke_if(exec, [&]() {
partition(exec, iter, iter, non_const(is_even));
});
```
- after:
```C++
partition(exec, iter, iter, non_const(is_even));
```

Remove `invoke_if()` function in tests

---

include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/reduce_by_segment_impl.h
include/oneapi/dpl/internal/scan_by_segment_impl.h
include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
include/oneapi/dpl/pstl/omp/parallel_scan.h
include/oneapi/dpl/pstl/omp/util.h
include/oneapi/dpl/pstl/parallel_backend_serial.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h
include/oneapi/dpl/pstl/parallel_backend_utils.h

In this PR we remove `ExecutionPolicy` template param from internal oneDPL buffers as not required:
- from `__buffer` template aliases;
- from `class __buffer_impl` (both implementations);
- from `__buffer` instances in oneDPL code.

Remove `ExecutionPolicy` template param from internal oneDPL buffers

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/utils.h

Adjust biased binary search by removing division, adjusting magic numbers.
Removing biased search forward, as it is likely to be small in size.

Adjust biased binary search

---

include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/numeric_impl.h
include/oneapi/dpl/pstl/omp/parallel_scan.h
include/oneapi/dpl/pstl/parallel_backend_serial.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h

In this PR we made the next changes:
- Remove `_ExecutionPolicy` patameter from `__parallel_strict_scan_body` function as not required anymore;
- Remove `_ExecutionPolicy` parameter from `__parallel_strict_scan` function as not required anymore;
- Comment unused template parameter `_ExecutionPolicy` in `__pattern_transform_scan` function.
This changes required due the PR https://github.com/uxlfoundation/oneDPL/pull/2146 has been merged into main branch.

Comment/remove unused parameter `_ExecutionPolicy&& __exec` in some functions

---

include/oneapi/dpl/internal/random_impl/philox_engine.h
test/xpu_api/random/conformance_tests/philox_test.pass.cpp
test/xpu_api/random/statistics_tests/philox_uniform_real_distr_dp_test.pass.cpp
test/xpu_api/random/statistics_tests/philox_uniform_real_distr_sp_test.pass.cpp
test/xpu_api/random/unit_tests/philox_unit_test.pass.cpp

**The scope of the changes:**
1. [Philox] Corrected `set_counter` API with setting `idx` to `n-1` according to the C++ proposal's wording:
2. [Testing] Generated reference numbers of the 10000th element for Philox with `word_count = 2`  and extended `philox_test.pass`.
3. [Testing] Changed the `philox2x32` and `philox2x64` aliases in the tests.

[RNG] Small refactoring of Philox engine implementation and updates in the testing 

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h

https://github.com/uxlfoundation/oneDPL/pull/2046 introduced a workaround for a hardware bug that prevents sub-group sizes of 32 from being used with `-O0` compilation on certain devices based on the detection of optimization via the `__OPTIMIZE__` macro. However, this approach does not work when the host and device compiler use different optimization levels, specifically when only one of the two phases uses `-O0` compilation. The integral sub-group size constant is embedded in the kernel name causing the host to call a kernel not compiled by the device which results in "Kernel not found" errors.
To support these cases where the host and device compiler optimization levels may differ, we need to make the following changes:
1. Remove the sub-group size from the kernel name. This can be …

Correct reduce-then-scan -O0 workaround behavior with different host and device optimization levels

---

test/support/test_config.h
test/xpu_api/containers/sequences/array/array.special/swap1.pass.cpp
test/xpu_api/containers/sequences/array/array.swap/swap.pass.cpp

We added a workaround for an issue with swapping with MSVC in #1560, but neglected to remove the test's "broken" macro.
This PR removes the broken macro, which allows us to resume testing on windows with the workaround.

[Tests] Remove broken macro for MSVC array swap

---

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h

The vectorization utilities in https://github.com/uxlfoundation/oneDPL/pull/1976 enforced a requirement that the underlying range / iterator type must be contiguous in order to enable vectorization paths along with other requirements we enforce. While this was not needed for correctness reasons, it was intended to enable good performance for the `reverse_iterator` case. Hardware vector instructions support vector load / stores only on increasing addresses, so in the case where addresses decrease with iterator increments, this is not directly vectorizable.
After further experimentation and study of generated assembly, I see that the oneAPI compiler is able to optimize the loads / stores in the case of `oneapi::dpl::reverse_iterator` to enable the generation of vector instructions / wider …

Enable vectorization of reverse iterators in SYCL backend parallel-for

---

test/xpu_api/random/conformance_tests/philox_test.pass.cpp

Let's fix:
> philox_test.pass.cpp:23:24: error: no template named 'philox_engine' in namespace 'oneapi::dpl::experimental'
error, when the unnamed lambda mode if off.

Fix philox_test.pass

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

In this PR we fix issue https://github.com/uxlfoundation/oneDPL/issues/2188.
Probably, this issue was introduced in the PR https://github.com/uxlfoundation/oneDPL/pull/521

Fix incorrect return type in the `__pattern_swap` function for `__hetero_tag` + ranges

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h

In this PR we fix double type definition in `__parallel_transform_reduce_work_group_kernel_submitter::operator()`
This error has been introduced in the PR https://github.com/uxlfoundation/oneDPL/pull/2167

Fix double type definition in `__parallel_transform_reduce_work_group_kernel_submitter::operator()`

---

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h
include/oneapi/dpl/experimental/kt/single_pass_scan.h
include/oneapi/dpl/internal/async_impl/async_impl_hetero.h
include/oneapi/dpl/internal/async_impl/glue_async_impl.h
include/oneapi/dpl/internal/scan_by_segment_impl.h
include/oneapi/dpl/pstl/glue_algorithm_impl.h
include/oneapi/dpl/pstl/glue_memory_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h
include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h

In this PR we revert https://github.com/uxlfoundation/oneDPL/pull/2161
The reason: https://github.com/uxlfoundation/oneDPL/pull/2161#issuecomment-2813669387
Also the change in `kt` namespace (from `sycl::queue` to `sycl::queue&` in params) breaks our experimental API and looks as incorrect.

Revert: Removal ExecutionPolicy from submitters and etc. stuff #2161

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
include/oneapi/dpl/pstl/hetero/utils_hetero.h

In this PR we remove some duplicated structures which were introduces in the PR https://github.com/uxlfoundation/oneDPL/pull/2153
Some structures has duplicated implementations and has been moved into include/oneapi/dpl/pstl/hetero/utils_hetero.h :
- `__pattern_minmax_element__reduce_fn` (renamed to `__pattern_minmax_element_reduce_fn`);
- `__pattern_minmax_element_transform_fn`;
- `__pattern_count_transform_fn`;
- `__pattern_min_element_transform_fn`.
Also `struct __pattern_min_element_reduce_fn` has two different implementations...
Just for note: before https://github.com/uxlfoundation/oneDPL/pull/2153 this code has been duplicated in the `lambda`-form

Remove some duplicated structures

---

include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/scan_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_by_segment.h

As described https://github.com/uxlfoundation/oneDPL/pull/2198#discussion_r2050818264
This fix provides better naming and namespace structure for `*_scan_by_segment`.  
It makes more clear the divide between hetero and device backend, and provides an entry point above the submitter within the device backend to transition from Policy to sycl queue and KernelName.  It also puts things in the correct namespaces.
I'm considering moving stuff between files, and changing the file structure out of the scope of this PR, but this should also be done at some point...
Should be applied before #2198 (as it provides the appropriate place to transition from policy to queue)

Fix naming and namespaces for scan_by_segment

---

.github/workflows/ci-testing.yml

Update ICPX/oneTBB links in the CI

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h

.... for me the approach from https://github.com/uxlfoundation/oneDPL/pull/709 looks like a little bit strange:
```C++
//The file is an internal file and the code of that file is included by a major file into the following namespaces:
//namespace oneapi
//{
//namespace dpl
//{
//namespace __par_backend_hetero
//{
```
So in someone case I received warning and in this PR I am trying to fix it.
In ideal case probably the approach from https://github.com/uxlfoundation/oneDPL/pull/709 should be reimplemented in we should place this code into normal `oneapi::dpl::__par_backend_hetero` namespace.

Fix an error in  __one_group_submitter

---

include/oneapi/dpl/internal/scan_by_segment_impl.h

It fixes an error:
> scan_by_segment_impl.h(376,5): error: no matching function for call to object of type '__sycl_scan_by_segment_impl<_CustomName, true>'
...
note: candidate template ignored: couldn't infer template argument '_BackendTag'
This issue has been introduced by @SergeyKopienko in the PR https://github.com/uxlfoundation/oneDPL/pull/2198

Fix segmented scans: remove extra template parameter

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
test/parallel_api/numeric/numeric.ops/reduce_by_segment_zip.pass.cpp
test/support/utils.h

`__red_by_seg_op` has a potential ambiguous return when the return type of `__binary_op` differs from the input segment's underlying value type. To resolve this issue, we can ensure the second element in the tuple returned by `__red_by_seg_op` matches the return type of `__binary_op` through a conversion.
In practice, this issue was encountered when performing a `reduce_by_segment` operation over zip iterators where a `std::tuple` is explicitly returned by the reduction operator. I have added a test case which catches this issue in `reduce_by_segment_zip.pass`

Resolve ambiguous return in `__red_by_seg_op` in SYCL backend

---

include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/numeric_impl.h
include/oneapi/dpl/pstl/omp/parallel_scan.h
include/oneapi/dpl/pstl/parallel_backend_serial.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h

This PR restores execution policy parameter in `__parallel_strict_scan` used by multiple backends, which was removed in #2157. 
Thanks @danhoeflinger for [noticing it](https://github.com/uxlfoundation/oneDPL/pull/2216#discussion_r2070222326).

Restore execution policy at mid-level (algorithm_impl)

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h

The PR fixes an error:
```
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h:420:13: error: no matching function for call to 'min'
420 |             ::std::min(__global_mem_size / (__num_bins * sizeof(_bin_type)),
|             ^~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/algorithmfwd.h:420:5: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('typename info::device::global_mem_size::return_type' (aka 'unsigned long long') vs. 'unsigned long')
```
It happens with AdaptiveCPP based on clang++18.

Fix a compile error with mismatching types in std::min

---

test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment_zip.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment_zip.pass.cpp

In https://github.com/uxlfoundation/oneDPL/pull/2206, the test utility `TupleAddFunctor` was renamed to `TupleAddFunctor1`. In addition to being used in `reduce_by_segment_zip.pass`, it is also used in the zip inclusive and exclusive scan by segment tests.
I've verified all instances in testing have now been updated and that the tests run:
```
~/repos/oneDPL/test$ grep -r "TupleAddFunctor" .
./support/utils.h:struct TupleAddFunctor1
./support/utils.h:struct TupleAddFunctor2
./parallel_api/numeric/numeric.ops/reduce_by_segment_zip.pass.cpp:    run_test_with_op(TestUtils::TupleAddFunctor1{});
./parallel_api/numeric/numeric.ops/reduce_by_segment_zip.pass.cpp:    run_test_with_op(TestUtils::TupleAddFunctor2{});
./parallel_api/numeric/numeric.ops/exclusive_scan_by_segment_zip.pass.cpp: …
```

[test] Update usages of `TupleAddFunctor` to `TupleAddFunctor1`

---

include/oneapi/dpl/internal/binary_search_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h
include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h

In this PR we fix early memory deallocation in algorithm implementations.
Typically in oneDPL algorithms we have the code like:
```C++
__par_backend_hetero::__parallel_partial_sort(
_BackendTag{}, ::std::forward<_ExecutionPolicy>(__exec),
__par_backend_hetero::make_iter_mode<__par_backend_hetero::access_mode::read_write>(__first),
__par_backend_hetero::make_iter_mode<__par_backend_hetero::access_mode::read_write>(__mid),
__par_backend_hetero::make_iter_mode<__par_backend_hetero::access_mode::read_write>(__last), __comp)
.__deferrable_wait();
```
where `__parallel_partial_sort` return the instance of `__future<sycl::event>`.
So in this case the is no memory management inside and so on.
But in the some cases we have another calls, for example:
```C++ …
```

Fix early memory deallocation in algorithm implementations

---

test/general/implementation_details/balanced_path_unit_tests.pass.cpp
test/support/test_config.h

Fix for unit test of balanced path.
Insufficient temp storage was provided to the set operation, now we have added enough space.  We mistook an issue with windows testing as an issue in MSVC STL, but it really was the result of an OOB write. This removes the broken macro incorrectly made in the previous PR.

[Test] Balanced path tests fix

---

documentation/library_guide/conf.py
include/oneapi/dpl/internal/version_impl.h
test/general/version.pass.cpp

The PR updates the oneDPL version macro and test verifying it.
According to https://github.com/uxlfoundation/oneAPI-spec/blob/4f3aad16ec26780b98fe5135ac4de9b8f27f8dd8/roadmap.rst a new version of the oneAPI specification is not expected at this time, so the ONEAPI_SPEC_VERSION macro is not updated in this PR.
This PR should not be merged until code freeze for the coming release.

Update the ONEDPL_VERSION number for the coming release

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
include/oneapi/dpl/pstl/iterator_impl.h
test/parallel_api/iterator/indirectly_device_accessible.pass.cpp

Fixing bug, ADL name which did not match [specification ](https://github.com/uxlfoundation/oneAPI-spec/pull/620/files).
Also adjusting type of function call to not include lvalue reference.  There is no reason to do that, these are never actually called.

Bugfix fix naming of ADL overload indirectly device accessible

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

It is not defined the order of evaluation of function arguments, so forwarding the ranges in the same line as calling `size()` on them is a a possible forward then use bug.
This PR also updates the set_a_write function to call the updated signature.
Credit to @mmichel11 for finding the issue / fix

[Bugfix] Forwarding then use bug 

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h

In this PR we declare return type in the function `__future::__wait_and_get_value(...)` instead of `auto`.
The goal - to improve readability.

Declare return type in the function `__future::__wait_and_get_value(...)`

---

include/oneapi/dpl/experimental/kt/single_pass_scan.h
include/oneapi/dpl/internal/scan_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h

In this PR we remove `__device_backend_tag` parameter in the cases when we have
`oneapi::dpl::__internal::__device_backend_tag, sycl::queue& __q` in sycl-submitters::operator() or in the functions of hetero-backend in the namespace `oneapi::dpl::__par_backend_hetero`.
Justification - the `__device_backend_tag` parameter doesn't required as it's not brings to us any semantic: we already have `sycl::queue` in params so implements something for sycl-backend.

Remove extra `__device_backend_tag` parameter from sycl-submitters and functions

---

include/oneapi/dpl/pstl/ranges/nanorange.hpp

When compiling with g++ (GCC) 15.1.1 20250425 (available in Fedora 42), there are the following issues:
```c++
nanorange.hpp:8009:80: error: ‘const class __nanorange::nano::ranges::counted_iterator_::counted_iterator<I>’ has no member named ‘current_’ [-Wtemplate-body]
// 3 more locations
nanorange.hpp:17045:42: error: ‘const struct __nanorange::nano::ranges::iota_view<W, Bound>::iterator’ has no member named ‘value’; did you mean ‘value_’?
```
Minimal reproducer: https://godbolt.org/z/zGM6zPbb4
```c++
// error: 'const struct S<T>' has no member named 'x' [-Wtemplate-body]
template <typename T>
struct S
{
friend void f(const S& s) noexcept(noexcept(s.x)) {}
T x;
};
int main() {}
```

Fix nanorange with gcc 15

---

include/oneapi/dpl/pstl/ranges/nanorange.hpp
test/support/test_macros.h

The PR fixes a warning, which is triggered with g++15:
> /usr/include/c++/15/ciso646:46:4: warning: #warning "\<ciso646\> is deprecated in C++17, use \<version\> to detect implementation-specific macros" [-Wcpp]
There is also an important note on [cppreference](https://en.cppreference.com/w/cpp/header/ciso646):
> \<ciso646\> is removed in C++20
However, I have not seen this error to trigger in practice.

Fix warnings related to <ciso646> deprecation

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/utils_hetero.h

This PR is a follow-up to https://github.com/uxlfoundation/oneDPL/pull/2200 and addresses https://github.com/uxlfoundation/oneDPL/issues/2204. We remove the duplicate definitions of `__pattern_min_element_reduce_fn` and place the implementation in the `utils_hetero.h` header.
The two existing implementations are slightly different. The version of the functor that differentiates between SPIR-V and non SPIR-V target backends is chosen to keep as it continue to show the best performance across assessed platforms.
I do not think this is considered a feature but am okay with holding off on merging until after the milestone's completion if we wish.

Remove duplicate `__pattern_min_element_reduce_fn` implementations

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
include/oneapi/dpl/pstl/iterator_impl.h

g++ has a warning: "friend declaration declares a non-template function [-Wnon-template-friend]"
This is to flag a common error [(as described here)](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Making_New_Friends) where one declares but does not define a non-template `friend` function in a class with the intention of having a one-to-one mapping of the class instance and the friend.  However, without a forward declaration of a template function, and some other adjustments this is not possible.
The warning in our case is a false one as far as I can understand.  Our intention is to never define a body for this function declaration, since it is only used to communicate a return type, so we have no such problem .  
However, the warning is of course undesirable, and its best to not have …

Resolving g++ warnings with `is_onedpl_indirectly_device_accessible`

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
include/oneapi/dpl/pstl/iterator_impl.h

Cherry picking #2241 on to the 2022.9 release branch at the suggestion of @akukanov .

Resolving g++ warnings with `is_onedpl_indirectly_device_accessible` (#2241)

---

test/support/utils_sycl.h

Sometimes due incorrect environment setting we have throwed exceptions in `oneDPL` tests.
They throws from `get_test_queue()` function, when we get `sycl::queue` for test.
In this PR we added logging of these exceptions from `get_test_queue()` into `std::cerr` and then throw it up.

Log exceptions from `get_test_queue()` into `std::cerr`

---

include/oneapi/dpl/pstl/algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

It fixes warnings like:
> algorithm_ranges_impl_hetero.h(983,41): warning: unused parameter '__tag' [-Wunused-parameter]
and:
> algorithm_ranges_impl.h(700,84): warning: unused parameter '__exec' [-Wunused-parameter]

Fix unused-parameter warning (policies and tags)

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

The PR fixes warnings like:
> parallel_backend_sycl_merge.h(304,65): warning: unused parameter '__rng1' [-Wunused-parameter]
> parallel_backend_sycl_for.h(160,60): warning: unused parameter '__brick' [-Wunused-parameter]
> unseq_backend_sycl.h(1323,24): warning: unused parameter '__is_full' [-Wunused-parameter]
The warnings occur with icx and -W4 flag in Windows.

Fix unused-parameter warnings (device backend)

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

It fixed the warning:
> parallel_backend_sycl.h:1068:12: warning: unused variable '__total_repeats' [-Wunused-variable]
The target release is 2022.9, because this warning may block https://github.com/oneapi-src/distributed-ranges releases.

Fix unused-variable warning (set balanced path)

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h

Let's cherry-pick that fix into 2022.9, because this warning may block https://github.com/oneapi-src/distributed-ranges releases.

Fix unused-variable warning (set balanced path) (#2243)

---

include/oneapi/dpl/pstl/utils.h

This PR removes double support requirements when calling `__dpl_signbit` with integral types.  `__dpl_signbit` exists to resolve an ambiguity (build error) in MSVC STL for integral types. The previous strategy was to convert to `double`, as this is the semantic requirement for functionality from the spec for integral overloads.  
However, this requires double support, which is unexpected for callers not using double input types to the algorithms, and also this likely incurs some performance penalty in the static case vs a more direct mask approach.

Fix __dpl_signbit to prevent double support requirement

---

include/oneapi/dpl/internal/scan_by_segment_impl.h
test/parallel_api/algorithm/alg.sorting/alg.binary.search/binary.search/binary_search.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/lower.bound/lower_bound.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.binary.search/upper.bound/upper_bound.pass.cpp
test/parallel_api/numeric/numeric.ops/exclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/histogram.pass.cpp
test/parallel_api/numeric/numeric.ops/inclusive_scan_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment.pass.cpp
test/parallel_api/numeric/numeric.ops/reduce_by_segment_zip.pass.cpp

The PR fixes warnings like:
- `unused-variable`
- `unused-parameter`
There are additional checks in `reduce_by_segment_zip.pass.cpp` to avoid `unused-variable` for `new_last`.
It's been cherry-picked from https://github.com/uxlfoundation/oneDPL/pull/2249 for easier review.

Fix warnings in additional algorithms

---

include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h
include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h
test/general/sycl_iterator/sycl_iterator_sort.pass.cpp

The PR fixes `unused-variable`, `unused-parameter` and `unused-local-typedefs` warnings.
It's been cherry-picked from #2249 for easier review.

Fix warnings in esimd KT

---

.github/workflows/ci-testing.yml

Let's treat already fixed warnings as errors. This PR excludes warnings which are still present - they should be iteratively removed.
This exclusion logic is possible with g++/clang++/icpx. cl does not support it; its warning-to-error list will expand and, probably, at some point, we would like to replace the whole list with /WX (treat all warnings as errors).

CI: treat a subset of warnings as errors

---

test/xpu_api/random/statistics_tests/common_for_distributions.hpp
test/xpu_api/random/statistics_tests/lognormal_distr_dp_portion_test.pass.cpp
test/xpu_api/random/statistics_tests/normal_distr_dp_portion_test.pass.cpp
test/xpu_api/random/unit_tests/philox_unit_test.pass.cpp

The PR fixes `unused-local-typedef` and `unused-variable` warnings in the statistics tests.
It's been cherry-picked from https://github.com/uxlfoundation/oneDPL/pull/2249 for easier review.

Fix warnings in the statistics tests

---

include/oneapi/dpl/pstl/experimental/internal/induction_impl.h
include/oneapi/dpl/pstl/unseq_backend_simd.h

Examples of the warnings:
> induction_impl.h:53:5: error: definition of implicit copy constructor for '__induction_object<int, unsigned long>' is deprecated because it has a user-provided copy assignment operator
> unseq_backend_simd.h:547:5: error: definition of implicit copy assignment operator for '_Combiner<oneapi::dpl::__internal::tuple<unsigned long, unsigned int>, oneapi::dpl::internal::segmented_scan_fun<unsigned long, unsigned int, std::plus<unsigned long>>>' is deprecated because it has a user-provided copy constructor
---
Note that `_Combiner` has `_Combiner(const _Combiner& __obj) : __value{}, __bin_op(__obj.__bin_op) {}` constructor, which behavior is unusual. However, if a corresponding copy assignment operator also default initializes `__value`, several tests produce wrong …

Fix deprecated-copy warning in the library

---

.github/workflows/ci-testing.yml
include/oneapi/dpl/pstl/omp/parallel_for.h
include/oneapi/dpl/pstl/omp/parallel_for_each.h
include/oneapi/dpl/pstl/omp/parallel_invoke.h
include/oneapi/dpl/pstl/omp/parallel_merge.h
include/oneapi/dpl/pstl/omp/parallel_reduce.h
include/oneapi/dpl/pstl/omp/parallel_scan.h
include/oneapi/dpl/pstl/omp/parallel_stable_sort.h
include/oneapi/dpl/pstl/omp/parallel_transform_reduce.h
include/oneapi/dpl/pstl/omp/util.h
include/oneapi/dpl/pstl/onedpl_config.h

Let's use `_ONEDPL_PRAGMA` in oneDPL instead of `_PSTL_PRAGMA`. 
It will fix this warning, which I suppose happens if Parallel STL is already present on a system (e.g. as a part of libstdc++):
> oneDPL/include/oneapi/dpl/pstl/./omp/util.h:34:13: warning: '_PSTL_PRAGMA' macro redefined [-Wmacro-redefined]
It also fixes a bug with the enablement of `PSTL_USE_NONTEMPORAL_STORES` mode, which used non-defined `_PSTL_PRAGMA`, hence expanding to nothing and having no effect.

Fix macro-redefined warning, fix enablement of PSTL_USE_NONTEMPORAL_STORES

---

test/parallel_api/algorithm/alg.modifying.operations/alg.partitions/is_partitioned.pass.cpp
test/parallel_api/algorithm/alg.modifying.operations/transform_binary.pass.cpp
test/parallel_api/algorithm/alg.sorting/alg.lex.comparison/lexicographical_compare.pass.cpp
test/parallel_api/algorithm/alg.sorting/is_sorted.pass.cpp
test/parallel_api/iterator/transform_iterator.pass.cpp
test/parallel_api/ranges/exclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/inclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/is_sorted_ranges_sycl.pass.cpp
test/parallel_api/ranges/is_sorted_until_ranges_sycl.pass.cpp
test/parallel_api/ranges/minmax_ranges_sycl.pass.cpp
test/parallel_api/ranges/reduce_ranges_sycl.pass.cpp
test/parallel_api/ranges/stable_sort_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform_inclusive_scan_ranges_sycl.pass.cpp
test/parallel_api/ranges/transform_reduce_ranges_sycl.pass.cpp
test/support/utils.h

The PR fixes a warning:
> test\support/utils.h(1033): warning C4459: declaration of 'max_n' hides global declaration
It renames local `max_n` to `max_size` to avoid a conflict with `TestUtils::max_n` or removes `using namespace TestUtils;`, whatever is simpler.

Fix warning in tests: declaration of <x> hides global declaration

---

.github/workflows/ci-testing.yml

Note that some of these warnings still occur when building all the tests with device backend (which is not currently covered in this CI). Anyway, let's have a strict warning policy with what we currently have in the CI.

CI: remove fixed warnings from -Werror exclusions

---

integration/env/vars.bat
integration/env/vars.sh
integration/etc/vars.bat
integration/etc/vars.sh
integration/modulefiles/dpl

Installations of oneDPL include an environment activation scripts which define environment variables as needed for DPL to work.
In particular, it defines an environment variable with name 'DPL_ROOT', which points at the path where the DPL installation is to be found.
The name "DPL_ROOT" with an underscore is inconsistent with the rest of oneAPI products, which define similar variables without underscores in their names.
For example:
MKLROOT
TBBROOT
IPPROOT
DALROOT
This PR introduces `DPLROOT` to make the library consistent with other oneAPI libraries to improve the user experience. It mirrors `DPL_ROOT` so no invasive changes to the library are immediately necessary and a plan to deprecate `DPL_ROOT` can be implemented.

Adding definition of DPLROOT variable to make the library consistent with other oneAPI libraries

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

A hot fix for the change from https://github.com/uxlfoundation/oneDPL/pull/2240
It fixes the following tests (experimental range API test cases)
- adjacent_find_ranges_sycl
- is_sorted_until_ranges_sycl.pass
- is_sorted_ranges_sycl.pass

[oneDPL][ranges][hetero] A hot fix for __pattern_adjacent_find; experimental ranges API use/test case

---

documentation/release_notes.rst

Adding missing known issue.  Discussions with the SYCLomatic team reminded me of this issue.
It is fixed in #2251, but that did not make it in for 2022.9.0.

[Docs] Adding set algorithm known issue

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
include/oneapi/dpl/pstl/hetero/utils_hetero.h
include/oneapi/dpl/pstl/utils_ranges.h
test/general/sycl_iterator/sycl_iterator_find.pass.cpp
test/parallel_api/algorithm/alg.nonmodifying/equal.pass.cpp

[oneDPL][hetero] adjacent_find pattern perf potential fix (based on refactoring paralle_find_or hetero pattern).
1) Used directly data access (ranges access for several middle layer algorithm patterns) instead of "indirectly access via zip_iterator and _zip_view). 
2) Reduced number of versions of paralle_find_(or ) hetero patterns, because to have just one is absolutely enough.  
3) Extended test coverage for "equal" algorithm
4) At the same time  - a fix for `__pattern_equal` iterator based pattern (trivial sequences case).

[oneDPL][hetero] adjacent_find pattern perf potential fix (based on refactoring paralle_find_or hetero pattern)

---

documentation/library_guide/introduction.rst
documentation/library_guide/parallel_api/iterators.rst
documentation/library_guide/parallel_api/pass_data_algorithms.rst

Update iterators page from the oneDPL guide to provide information about indirectly device accessible.  
Mention public trait and ADL-based customization point.  Add details about mentioned iterators.

[docs] Indirectly device accessible update

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h

This PR  adds the appropriate kernel name wrappers for runtime branches in find_or algorithms.
#2247 removed some wrappers around find_or patterns, and exposed some issues where we are not wrapping kernel names in true runtime branches between patterns.  This results in build errors complaining of same mangled name when using unnamed lambdas.

find_or fixes for unnamed lambda

---

test/parallel_api/algorithm/alg.modifying.operations/shift_left_right.pass.cpp
test/support/utils_sort.h

In this PR we remove extra `sycl::queue` instances on stack.

Remove extra `sycl::queue` instances on stack

---

test/parallel_api/ranges/std_ranges_test.h
test/xpu_api/algorithms/alg.sorting/alg.binary.search/binary.search/binary_search2_g.pass.cpp
test/xpu_api/algorithms/alg.sorting/alg.binary.search/equal.range/equal_range2_g.pass.cpp

In this PR we fix return type in some test predicates:
from
```C++
auto pred1 = [](auto&& val) -> decltype(auto) { return val > 0; };
auto pred2 = [](auto&& val) -> decltype(auto) { return val == 4; };
auto pred3 = [](auto&& val) -> decltype(auto) { return val < 0; };
```
to
```C++
auto pred1 = [](auto&& val) -> bool { return val > 0; };
auto pred2 = [](auto&& val) -> bool { return val == 4; };
auto pred3 = [](auto&& val) -> bool { return val < 0; };
```
because they return result of some compare operation which is always `bool` type.
Also corrected two spelling check errors in comments.

Fix return type in some test predicates

---

test/support/iterator_utils.h
test/support/utils.h
test/support/utils_invoke.h
test/support/utils_sort.h

In this PR we forward execution policy in test environment through `std::forward` call.
It's important for some another PR which we going to apply later.

Forward execution policy in test environment

---

documentation/library_guide/introduction.rst
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
test/general/implementation_details/device_copyable.pass.cpp
test/parallel_api/numeric/numeric.ops/scan.pass.cpp

Currently, the result of `__unary_op` in `__gen_transform_input` will be scanned over in the reduce-then-scan implementation. This is incorrect, particularly if an initial value is provided by the user. We fix this by converting the resulting of `__unary_op` to the initial value type.
This requires an assumption that the input iterator's value type is convertible to the initial value type which is a known limitation with the TBB backend and the legacy SYCL scan implementation.

Ensure the correct type is scanned over in SYCL reduce-then-scan

---

.github/workflows/ci-testing.yml
examples/pSTL_offload/CMakeLists.txt

Fixes cmake to allow build for PSTL offlead examples (no tests running yet). For the other new examples #2191, skipping them in the CI for now with no CMakeLists.txt in the top level dir.  This allows development to continue for active PRs, using the CI without further interruption. 
We will follow up with another PR to fix for the new examples so they all build, run and pass.

Example CMake Fixes; Skip example without CMakeLists.txt

---

test/support/utils.h

This PR enhances error logging in iterator comparisons by introducing streamability detection and structured log output.
- Added a compile-time trait to detect if a type can be streamed (in the namespace `TestUtils`).
- Introduced `TagExpected`/`TagActual` and `log_value` helpers for consistent logging (in the namespace `TestUtils`).
- Updated `expect_equal_val` and `expect_equal` to use the new logging helpers.
So now we can write in the test code something like
```C++
std::vector<int> data;
// ...
auto it = data.begin();
// ...
EXPECT_EQ(data.begin(), it, "Error message");
```
Previously we would have had the compile errors in this use-case because iterator variables doesn't supports `operator<<` at all.

Support `EXPECT_EQ` call for iterators

---

include/oneapi/dpl/pstl/tuple_impl.h
include/oneapi/dpl/pstl/utils_ranges.h

[oneDPL] A fix for oneDPL C++17 zip_view.
The following trivial example doesn't work:
```
int a[10];
std::ranges::subrange r1(a, a + 10);
auto zip_view = make_zip_view(r1);
```
The PR suggests a fix for that.

[oneDPL] A fix for oneDPL internal tuple and for oneDPL C++17 zip_view

---

.github/workflows/ci-testing.yml

icpx 2025.1 and older have compatibility issues with VS 17.14, which was recently upgraded in the windows-2022 (windows-latest) image.

Workaround icpx incompatibility issues with VS 17.14

---

documentation/release_notes.rst

That issue was observed on Windows only, with icpx 2025.0 and an old GPU driver presumably built in December 2024 - a combination of tools which did not fully support Intel® Core Ultra Series architecture. 
It is not observed with icpx 2025.1 (which introduced Intel® Core Ultra Series architecture support) and 32.0.101.6647 (released together with icpx 2025.1), as well as newer versions of these tools.
Let's remove the copy of the note for oneDPL 2022.9, where it is irrelevant, and update it for 2022.8. We can also remove the notes entirely, but I suggest providing an update to the original one to avoid confusion about sudden disappearance of the issue.

Release notes: correct sort issue description

---

.github/workflows/ci-testing.yml

Let's use the latest version of icpx, which supporting the FPGA emulator.
`apt-get install intel-oneapi-compiler-fpga` package installs its own compatible icpx verison (2025.0) as a dependency. The latest compiler installed with `intel-oneapi-compiler-dpcpp-cpp`, which has recently been updated to 2025.2, is not compatible with that package.

CI: fix fpga emulator

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h

In this PR we fix an error in the `struct __subgroup_radix_sort` :
- the `std::uint32_t __radix` and `bool __is_asc` template parameters has bin missed inside generation of kernel names.
This error has been detected for cmake option `DONEDPL_TEST_EXPLICIT_KERNEL_NAMES=ALWAYS` during compile errors checks in the PR https://github.com/uxlfoundation/oneDPL/pull/2102

Fix kernel names in `struct __subgroup_radix_sort`

---

test/parallel_api/ranges/std_ranges_transform_iota_sycl.pass.cpp

In this PR we fix warning:
```
warning : use of logical '&&' with constant operand [-Wconstant-logical-operand]
return TestUtils::done(1 && 1);
```
This warning happens if  `_ENABLE_STD_RANGES_TESTING` and `TEST_DPCPP_BACKEND_PRESENT` are defined.

Fix warning in the `std_ranges_transform_iota_sycl.pass.cpp`

---

test/parallel_api/iterator/input_data_sweep.h

This PR fixes broken tests in the `input_data_sweep` suite by centralizing the no-op identity function and removing a conflicting local definition.
- Introduce a global `noop` generic lambda
- Remove the local `noop` alias to `oneapi::dpl::identity`
- Ensure consistency of the identity operation across recursive test wrappers
The errors has been introduced in the PR https://github.com/uxlfoundation/oneDPL/pull/2294

Fix broken tests

---

test/parallel_api/iterator/input_data_sweep.h

This PR explains in comments why we should implement our own `noop` operator in `inpud_data_sweep*` tests and can't use `oneapi::dpl::identity` instead.

Additional comments for `noop` implementation in tests

---

documentation/library_guide/parallel_api/iterators.rst

Add some documentation to `transform_iterator` to warn of a potential pitfall with a dangling reference when using functors similar to `oneapi::dpl::identity` in combination with source iterators returning a prvalue.

Add documentation for transform_iterator pitfall

---

test/parallel_api/experimental/asynch.pass.cpp

This PR refactors the `asynch.pass.cpp` test to improve readability, remove a redundant scope, add explicit waits for async operations, and wrap test invocations in `main()` with exception handling.
- Removed an unnecessary inner block in `test1_with_buffers`.
- Reformatted long async calls and added `wait()` to the USM `sort_async` :  !!! **Fixed `SEGFAULT` in this test**: please see https://github.com/uxlfoundation/oneDPL/pull/2337/files/f861316bc5a011baeb0a9a7d5a65fcb5095e4c5a#r2194854628 for details.
- Wrapped all test calls in `main()` with a `try/catch` to report exceptions.
**ATTENTION** : for review please do not show differences in whitespaces.

Fix crash in `asynch.pass` test

---

test/general/test_policies.pass.cpp
test/parallel_api/algorithm/alg.sorting/sort_by_key_common.h
test/parallel_api/iterator/input_data_sweep_counting_iter.pass.cpp
test/parallel_api/iterator/input_data_sweep_host_iter.pass.cpp
test/parallel_api/iterator/input_data_sweep_sycl_iter.pass.cpp
test/parallel_api/iterator/input_data_sweep_usm_allocator.pass.cpp
test/parallel_api/iterator/input_data_sweep_usm_device.pass.cpp
test/parallel_api/iterator/input_data_sweep_usm_shared.pass.cpp
test/support/utils.h
test/support/utils_invoke.h

This PR renames the execution policy parameter from `policy` to `exec` across test utilities and test cases for consistency.
- Renamed function parameters and forwarded variables from `policy` to `exec` in test helper headers.
- Updated all test implementations to use `exec` when invoking queue-based operations and wrappers.
- Ensured stable and unstable sort helpers use the new parameter name.
Previously in tests we had `Policy&& policy` and `Policy&& exec` together:
- `Policy&& exec` - 373 entries in tests;
- `Policy&& policy` -  14 (16) entries in tests.

Rename the name of execution policy parameter in tests

---

include/oneapi/dpl/pstl/algorithm_impl.h

We forward a policy calling parallel-for in an iterative loop which results in undefined behavior.

Fix use after after forward in `__pattern_shift_left` in parallel host backend

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_for.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

This PR standardizes SYCL kernel lambda parameter naming by renaming `__item_id` to `__item` across multiple parallel backend header files. The change improves naming consistency for SYCL kernel parameters that capture `sycl::nd_item<1>` and `sycl::item<1>` objects used in parallel algorithm implementations.
- Renames `__item_id` parameter to `__item` in SYCL kernel lambda functions
- Updates all usages of the renamed parameter throughout lambda function bodies  
- Includes one spelling correction for "counting_iterator" comment

Rename `__item_id` parameter into `__item` in sycl-submitters

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h

This PR fixes the logic in `__parallel_reduce_then_scan_scan_submitter` to account for unique patterns when calculating the number of inputs in a block. The change ensures that the first element, which is always copied to the output for unique patterns, is skipped when computing block size. Previously, this led to `__active_groups` being calculated incorrectly for edge case inputs, causing the write to the result in host USM being skipped.

Correct block size calculation in SYCL backend reduce-then-scan for unique pattern

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
include/oneapi/dpl/pstl/utils.h
test/parallel_api/numeric/numeric.ops/reduce.pass.cpp
test/parallel_api/numeric/numeric.ops/transform_reduce.pass.cpp
test/support/utils.h
test/support/utils_device_copyable.h

This PR removes the default constructor requirement from the SYCL backend's `result_and_scratch_storage` utility.
To do this, we require the type to be device copyable (which already was the case), but also provides that a bitwise copy is equivalent to copy construction.
This was split off from #2327.

Remove default constructible requirement from result_and_scratch_storage

---

.clang-format

To get concepts / requires clauses etc. to work with clang format we need to adjust the standard in our .clang-format file.
Currently causing strange formatting in #2359.

Adjust clang format to c++20 for concepts, etc.

---

rfcs/experimental/kernel_templates/README.md
rfcs/experimental/kernel_templates/kernel_configuration/README.md

The RFC describes the structure and common design of kernel templates. It also lists design gaps and potential improvements.
RFCs for the individual kernel templates will be added separately.

RFC for Kernel Templates

---

test/support/utils_device_copyable.h

#2354 introduces a test utility `NoDefaultCtorWrapper` in `test/support/utils.h` and uses the utility in `test/support/utils_device_copyable.h`. This PR includes `utils.h` in `utils_device_copyable.h` so the definition is available to resolve the compilation failure of `test/parallel_api/iterator/indirectly_device_accessible.pass.cpp`.

Including utils.h to make definition of NoDefaultCtorWrapper available.

---

test/parallel_api/algorithm/alg.sorting/sort_by_key_common.h

`TagUSM` and `TagBuffer` are already declared in this file.

Remove extra declarations from sort tests

---

include/oneapi/dpl/pstl/experimental/internal/for_loop_impl.h

This PR resolves an issue where because of the ordering of template arguments, we were using non-forwarded policy arguments, with a specified type for the arguments which may not match the incoming value category of policy.
Reordering the template arguments allows us to properly use forwarding / universal references for the policy again in these helpers.
Branched off from https://github.com/uxlfoundation/oneDPL/pull/2369/files#r2260684243

Fix universal references by reordering template args

---

rfcs/proposed/range_algorithms_3/README.md

[oneDPL][rfc][ranges][L1] the third portion of the range based API

[oneDPL][rfc][ranges][L1] the third portion of the range based API

---

include/oneapi/dpl/pstl/algorithm_impl.h

In this PR we switch from forwarding after a capture by value to a capture by reference and then pass through.
Forwarding doesn't make sense here as the type may no longer match.
branched off from 
https://github.com/uxlfoundation/oneDPL/pull/2369/files#r2254402955

Fix forwarded value captured policy 

---

include/oneapi/dpl/pstl/algorithm_impl.h

In #2373, we missed that this code actually still has an issue. If this policy is an rvalue, the forward of the policy into the function `__parallel_invoke` results in a move operation.
The lambdas which capture the policy by reference are defined before the `std::forward` and resulting possible move of the policy, but they are not used until the body of the `__parallel_invoke` function.  This means that they would be used after the policy they hold a reference to has been moved from its scope.  This capture by reference for the lambda means that we need also to not forward the policy itself into `__parallel_invoke`.
In practice, this is currently benign because these policies will always be const lvalue ref in this code location but we should still fix it.

Remove forward of policy

---

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h

This PR fixes a data type issue in some pattern implementations for heterogeneous execution tags:
-  `__pattern_set_union`;
- `__pattern_set_symmetric_difference`.
The change corrects the temporary buffer's data type to match the second sequence's element type rather than the output iterator's value type.
- Corrected temporary buffer data type from output iterator's value type to second sequence's value type
- Added explanatory comment describing the purpose of the temporary buffer
This issue has been found and fixed together with @dmitriy-sobolev
```C++
struct A1
{
int field_a;
operator int() const { return field_a; }
};
struct A2
{
int field_b;
operator int() const { return field_b; }
};
auto __comp = [](auto&& __val1, auto&& __val2){
// compare A1 and A2 by their fields field_a, …
```

Fix temporary buffer data type in `__pattern_set_union` and `__pattern_set_symmetric_difference` for `__hetero_tag`

---

include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/function.h
include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
include/oneapi/dpl/internal/reduce_by_segment_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_scan_by_segment.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
include/oneapi/dpl/pstl/tuple_impl.h
include/oneapi/dpl/pstl/utils.h
test/general/implementation_details/device_copyable.pass.cpp

This PR adds a path for `inclusive_scan_by_segment` and `exclusive_scan_by_segment` using our reduce-then-scan infrastructure to improve performance. Additionally, some reorganization of existing "fallback" implementations is required 
Summary of changes:
- `__parallel_scan_by_segment_reduce_then_scan` and associated reduce-then-scan building blocks are added to implement scan-by-segment. The implementation is similar but unique from reduce-by-segment.
- The high level scan-by-segment fallback has been re-implemented at the parallel pattern level to consolidate the location of SYCL backend implementations.
- `__segmented_scan_fun` and `__replace_if_fun` have been moved to our general utilities as they are shared between implementations in `pstl/hetero/dpcpp` and `internal` directories.

Reduce-then-scan path for SYCL scan-by-segment implementations

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

This PR fix the return types of two pattern functions in the oneAPI DPL library to use `borrowed_iterator_t` instead of `iterator_t` for C++20 ranges compliance.
- Updated return types from `std::ranges::iterator_t` to `std::ranges::borrowed_iterator_t` in two function signatures
- Ensures proper iterator borrowing semantics for range-based algorithms
From issue #2394

Fix return types in `oneapi::dpl::__internal::__ranges::__pattern_minmax_element` and `oneapi::dpl::__internal::__ranges::__pattern_mismatch`

---

test/parallel_api/ranges/std_ranges_test.h

#2389 added tests for dangling iterators when APIs are called with temporary ranges.  
`std::vector` is not device copyable, so it does not make sense to pass it as a temporary range, even to test for dangling iterator returns.  
`std::array` is sycl device copyable and can be used in a similar way.   With this, we can use the same type for both device and host policies.  
This removes the static assertion when `auto` is used as the return type for range functional structs.  It was due to a real issue with the device copyability of `std::vector`, but is suppressed when replacing `auto` with an explicit return type.  This explicit return type seems like it allowed the compiler to short circuit within a `decltype` context without compiling the rest of the call stack, since it has an …

Fix testing temp range type for device policies

---

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h

This PR fixes compilation errors in the oneAPI DPL library by adding explicit template parameter specifications to `oneapi::dpl::__internal::__compare` instantiations. The changes ensure proper template argument deduction for the `__compare` class template.
- Adds explicit template parameters `<_Pred, _Proj>`, `<_Comp, _Proj>` to `__compare` instantiations
- Fixes template argument deduction issues that were causing compile-time errors
- Updates multiple algorithm implementations including adjacent_find, is_sorted, min_element, min, minmax_element, and minmax
```C++
oneapi/dpl/pstl/algorithm_ranges_impl.h:247:40: error: alias template '__compare' requires template arguments; argument deduction only allowed for class templates
247 |     oneapi::dpl::__internal::__compare __pred_2{__pred, …
```

Fix `oneapi::dpl::__internal::__compare` specializations

---

test/parallel_api/numeric/numeric.ops/exclusive_scan.pass.cpp

This PR replaces the usage of `std::exclusive_scan` with `exclusive_scan_serial` in a test file to ensure consistent serial execution behavior in test calculations.
- Replaces `std::exclusive_scan` with `exclusive_scan_serial` for expected result calculation
- Adds necessary include for the serial implementation

Replace `std::exclusive_scan` to `exclusive_scan_serial` call

---

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/utils.h

This PR refactors projection utilities by removing the `__projection` struct and updating return type specifications for better type handling. It eliminates redundant wrapper classes and improves reference handling in projection operations.
- Removed `__projection` struct and replaced its usage with direct `std::invoke` calls
- Updated `__projection_deref` to use `decltype(auto)` return type with explicit lvalue/rvalue reference handling
- Cleaned up SYCL trait specializations by removing references to the deleted `__projection` struct
Per-commit CI checks started in https://github.com/uxlfoundation/oneDPL/pull/2405/checks

Clarify new predicate return types to merge

---

include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/algorithm_ranges_impl.h
include/oneapi/dpl/pstl/utils.h

This PR removes the `struct _SubscriptAdapter` that was used to adapt iterator access patterns and replaces it with direct function implementations that use projection-based approaches, simplifying the codebase architecture.
- Removes the `_SubscriptAdapter` struct and its single `operator[]` method
- Introduces new direct projection-based variants of `__pstl_lower_bound` and `__pstl_upper_bound` functions
- Updates all call sites across multiple algorithm implementation files to use the new direct function variants
https://github.com/uxlfoundation/oneDPL/pull/2410/checks

Remove `struct _SubscriptAdapter`

---

include/oneapi/dpl/pstl/algorithm_ranges_impl.h

There is no need to construct an initialized list and then construct `std::ranges::borrowed_iterator_t` from it.
This change is moved from #2292 as not related.

Avoid proxy construction of borrowed_iterator_t with an init list

---

test/support/compile_only_checks.h
test/support/test_config.h

No comma operator tests are causing very long build times without additional benefit for debug runs. 
We don't gain any coverage of code by running these compile only tests in DEBUG mode or in no unnamed lambda mode.
Lets turn off the no comma tests for those cases.

[Test] Restrict no comma operator test builds

---

documentation/library_guide/introduction.rst
include/oneapi/dpl/internal/async_impl/glue_async_impl.h
include/oneapi/dpl/internal/serial_numeric_impl.h
include/oneapi/dpl/pstl/glue_numeric_impl.h
include/oneapi/dpl/pstl/glue_numeric_ranges_impl.h
include/oneapi/dpl/pstl/numeric_impl.h
include/oneapi/dpl/pstl/omp/parallel_transform_reduce.h
include/oneapi/dpl/pstl/parallel_backend_serial.h
include/oneapi/dpl/pstl/parallel_backend_tbb.h
include/oneapi/dpl/pstl/unseq_backend_simd.h
include/oneapi/dpl/pstl/utils.h
test/parallel_api/numeric/numeric.ops/reduce.pass.cpp
test/parallel_api/numeric/numeric.ops/transform_reduce.pass.cpp
test/support/utils.h

This PR adds support within [transform_]reduce for types with only move constructor and move assignment operator (no copy assignment or construction) for host backends (tbb and omp).
It adds host policy tests for move only types within [transform_]reduce.pass.  
This is part of the resolution for #1955.

Move only type support for [transform_]reduce for host backends

---

include/oneapi/dpl/pstl/utils.h

This PR reorganizes the `__pstl_left_bound` function by simplifying its implementation to use `__pstl_lower_bound` directly instead of converting to an upper bound search with argument reordering.
- Replaces complex argument reordering logic with negation-based comparison
- Switches from `__pstl_upper_bound` to `__pstl_lower_bound` for the underlying implementation
https://github.com/uxlfoundation/oneDPL/pull/2431
This PR has been checked manually.

Reorganize `__pstl_left_bound` function

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h

In balanced path set operations, we originally assumed that the type returned by size() was aligned between different ranges.  This is not the case, especially as we move to support the ranges set APIs.
This PR aligns types better across ranges so that we do not encounter trouble here.

Align size types for set alg helpers

---

include/oneapi/dpl/internal/dynamic_selection_impl/default_backend.h
include/oneapi/dpl/internal/dynamic_selection_impl/dynamic_load_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/fixed_resource_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/policy_base.h
include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy.h
include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h
test/parallel_api/dynamic_selection/sycl/test_dynamic_load_policy_sycl.pass.cpp
test/parallel_api/dynamic_selection/sycl/test_fixed_resource_policy_sycl.pass.cpp
test/parallel_api/dynamic_selection/sycl/test_round_robin_policy_sycl.pass.cpp
test/support/test_dynamic_load_utils.h
test/support/test_dynamic_selection_utils.h

This PR allows users to provide a `resource_adapter` alongside a `resource` where the resulting `base_resource = resource_adapter(resource)` defines the default backend implementation.
This enables a use case where a user may want a resource to contain more or even a different variant as compared to the core base resource which defines a backend implementation.
The motivating use case is using `sycl::queue*` as the resource type alongside an adapter which dereferences.  This allows less overhead copying pointers rather than full queues.  It also allows the pointer to be used as a unique identifier to do things like look up a memory space in a global map.
Alternatively, you could envision a resource being provided which is a `std::pair<sycl::queue, usm_pointer>`, and an adapter functor …

Dynamic Selection Adding ResourceAdapter to support queue*

---

test/support/test_config.h

Updates the Intel LLVM compiler version definition used in PSTL tests from version `20250200` to `20250300`.
- Increments the `_PSTL_TEST_LATEST_INTEL_LLVM_COMPILER` macro value
- Updated the definition of `_PSTL_LAMBDA_PTR_TO_MEMBER_WINDOWS_BROKEN` macro

Update compiler version in tests

---

include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/algorithm_ranges_impl.h

In this PR we fix incorrect usage of `_DifferenceType1` / `_DifferenceType2` in the code.
Introduced in #2320 and earlier

Fix incorrect usage of `_DifferenceType1` / `_DifferenceType2` in the code

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h

This PR fixes Coverity static analysis issues in set parallel range algorithms by addressing potential object lifetime problems. The changes replace direct projection of temporary objects with proper intermediate variable storage to ensure object lifetime extends through the projection operation.
- Introduces intermediate variables to store array element values before applying projections
- Modifies three different set operation implementations to use the safer pattern
- Addresses potential dangling reference issues that could cause undefined behavior
Alternative approach implemented in the PR https://github.com/uxlfoundation/oneDPL/pull/2459
Source issue has been introduced in the PR #2320

Fix coverity issues in set parallel range algorithms #1

---

test/general/header_inclusion_order_memory_0.pass.cpp
test/general/header_inclusion_order_memory_1.pass.cpp

`std::make_unique_for_overwrite` is available in libstdc++11 and newer.

Fix header inclusion memory tests for libstdc++10

---

test/support/test_config.h
test/xpu_api/ranges/xpu_std_drop_view.pass.cpp

Known limitations:
> * ``std::ranges::drop_view`` from libstdc++ version 10 may throw exceptions.
This can lead to a "SYCL kernel cannot use exceptions" compilation error
when it is used to pass data to a range-based algorithm with a device policy.
Issue:
> In file included from /tmp/oneDPL/test/xpu_api/ranges/xpu_std_drop_view.pass.cpp:18:
In file included from /tmp/oneDPL/test/support/utils.h:24:
In file included from /tmp/oneDPL/include/oneapi/dpl/execution:23:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/execution:32:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/pstl/glue_execution_defs.h:50:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/pstl/algorithm_impl.h:13:
In file …

Skip XPU drop_view test with libstdc++10

---

test/parallel_api/iterator/permutation_iterator.h

This PR removes complexity from the permutation iterator tests by directly assigning to usm_shared index data rather than copying from a host `std::vector` and copying via a `queue.copy` call.  This reduces complexity but also works around what seems to be a bug in the sycl runtime, where usm_shared memory assigned on the device is used directly within a parallel section as the first usage on the host resulting in a segfault.

[Tests] Permutation Iterator tests, directly assign to usm_shared for indexes

---

documentation/release_notes.rst
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
include/oneapi/dpl/pstl/onedpl_config.h

icpx 2025.3 (latest nightly build version) fails to compile `__histogram_general_registers_local_reduction` kernel for CPU devices.
The issue has already been reported, but a potential fix will not likely make it into the release. A quick solution is to fall back to a less optimized kernel. 
The fall back is done on demand by defining `ONEDPL_DISABLE_HISTOGRAM_REGISTER_REDUCTION` to a non-zero value.
The plan is to mention this macro in the release notes as a workaround with no promise of having it for the future releases.

Histogram: workaround kernel compilation issues with icpx 2025.3

---

documentation/release_notes.rst

The issue does not reproduce with other Rolling or LTS versions of the GPU driver.
This addition complements the existing known issue for the 2022.9 release.
Let's update the 2022.9 section of [the release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-dpcpp-library-release-notes.html) if it's expected to be revised in the next release.
If not, it would be more appropriate to add this to the oneDPL 2022.10 section instead.
Upd. Agreed to remove the note entirely as outdated - the mentioned Rolling driver version is no longer supported.

Update a known issue for range-based count_if

---

include/oneapi/dpl/pstl/algorithm_ranges_impl.h
include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
include/oneapi/dpl/pstl/utils.h

This PR removes the `__predicate` and `__compare` structs from the `oneapi::dpl::__internal` namespace and replaces their usage with existing alternatives.
- Removes the generic `__predicate` template struct and its alias `__compare`
- Updates all usages to use `__binary_op` for binary operations and `__unary_op` for unary operations
- Removes corresponding SYCL device copyable trait specializations
- `struct __predicate` and `struct __compare` hides in code for which amount of arguments they going to be applied.

Remove `__predicate` and `__compare` structs

---

include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/hetero/memory_ranges_impl_hetero.h

This PR fixes an issue where range iterators were being used after the range objects had been moved, which could lead to undefined behavior. It's looked not quite correct. The changes remove unnecessary `std::forward` calls when passing range parameters that need to remain valid for subsequent iterator operations.
- Remove `std::forward` calls for range parameters that are accessed after being passed to functions
- Ensure range objects remain valid when their iterators are used later in the same scope
- Apply consistent parameter passing pattern across multiple algorithm implementations

Fix range iterators usage after range perfect forwarding

---

include/oneapi/dpl/pstl/algorithm_ranges_impl.h
include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
include/oneapi/dpl/pstl/memory_ranges_impl.h

This PR refactors the ranges staff implementation by removing explicit `std::ranges::borrowed_iterator_t` and `std::ranges::borrowed_subrange_t` wrapper constructions in favor of direct returns or brace initialization. The changes simplify the code while maintaining the same return types through template argument deduction.
- Removes explicit type wrapper constructions for borrowed iterators and subranges
- Replaces `auto` return types with explicit type annotations for better API clarity
- Simplifies return statements using brace initialization instead of explicit constructor calls
- Avoid multiple `std::ranges::begin`, `std::ranges::end` and `std::ranges::size` calls

Ranges stuff refactoring

---

documentation/release_notes.rst
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h

The compiler devs have already fixed the issue workarounded by #2465. The fix going to be cherry-picked into icpx 2025.3.
The documentation change is better to be done separately to target oneDPL 2022.10.

Revert the workaround for kernel compilation issues in histogram

---

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
test/parallel_api/numeric/numeric.ops/reduce.pass.cpp

When `oneapi::dpl::reduce` is called multiple times with a device policy and the only difference in the calls is the type of the initial value, different kernels are generated but we use the same kernel name. This results in a compilation error.
To fix this issue, we need to add the initial value type `_Tp` as a template argument to the call to `__kernel_name_generator` when generating the reduction kernel name.

Fix duplicate kernel name issue in __parallel_transform_reduce_impl with differing init types

---

include/oneapi/dpl/pstl/algorithm_impl.h
include/oneapi/dpl/pstl/algorithm_ranges_impl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
include/oneapi/dpl/pstl/histogram_binhash_utils.h
include/oneapi/dpl/pstl/utils.h
test/general/implementation_details/balanced_path_unit_tests.pass.cpp

This PR modifies binary search utility functions to compare result of both projections in one `std::invoke` call at one place.
So we avoid any life-time extensions for the source/projected values and pass projected values into comparator preserving their value category.
Synthetic example **with compile error** based on current state of `main` branch: https://godbolt.org/z/zE7KTKPf9, https://godbolt.org/z/7e5z685cj (https://godbolt.org/z/hj6YMv6rq, https://godbolt.org/z/f9oPGbbeM with additional `static_assert` according to comment https://github.com/uxlfoundation/oneDPL/pull/2461#discussion_r2392307799 from @akukanov)
Synthetic example **without compile errors** based on current state of this PR: https://godbolt.org/z/sbz3ehhK6 (https://godbolt.org/z/aq5GxWhej with additional …

Refactoring of utility functions to evaluate projected values and compare result  in one place

---

documentation/release_notes.rst

The oneDPL release for the 2022.10.0 milestone covers roughly the changes from merged PRs #2207 to #2465.

Release notes for 2022.10

---

test/support/utils.h

This PR fixes a compile error in the `MinimalisticRange` struct by removing trailing semicolons from the `begin()` and `end()` method definitions.
- Removes unnecessary semicolons after the closing braces of inline method definitions

Fix compile error in struct MinimalisticRange
