jenkinsfiles/RHEL_Check.groovy, jenkinsfiles/UB18_Check.groovy, jenkinsfiles/UB20_Check.groovy, jenkinsfiles/Windows_Check.groovy
Signed-off-by: Xiaodong, Li <xiaodong.li@intel.com>
Add CI scripts.
The approval from bb-sycl is used to verify the whole process of pre-commit test.
=>  Add CI scripts

README.md
Updated links for the Samples (#34)
=> Update link for samples

documentation/CHANGES.rst
CHANGES.rst is the list of the most significant changes made over time in oneDPL.
=> Add CHANGES.rst

CMakeLists.txt, documentation/library_guide/conf.py, include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h, include/oneapi/dpl/internal/function.h
Align mentioned names with official naming
=> Naming alignment

CONTRIBUTING.md, CREDITS.txt
Removed redundant parts from CONTRIBUTING.md, fixed links, aligned the branch naming with the existing, and added CREDITS.txt
=> Update CONTRIBUTING.md and add CREDITS.txt

include/oneapi/dpl/numeric, test/support/test_iterators.h, test/xpu_api/numerics/numeric.ops/accumulate/xpu_accumulate.pass.cpp, test/xpu_api/numerics/numeric.ops/accumulate/xpu_accumulate_op.pass.cpp, test/xpu_api/numerics/numeric.ops/inner.product/xpu_inner_product.pass.cpp, test/xpu_api/numerics/numeric.ops/inner.product/xpu_inner_product_comp.pass.cpp, test/xpu_api/numerics/numeric.ops/numeric.iota/xpu_iota.pass.cpp, test/xpu_api/numerics/numeric.ops/partial.sum/xpu_partial_sum.pass.cpp, test/xpu_api/numerics/numeric.ops/partial.sum/xpu_partial_sum_op.pass.cpp
Signed-off-by: Haonan Yang <haonan.yang@intel.com>
=> Add numeric test

jenkinsfiles/RHEL_Check.groovy, jenkinsfiles/UB18_Check.groovy, jenkinsfiles/UB20_Check.groovy, jenkinsfiles/Windows_Check.groovy
The change will switch our Jenkins CI test to use good compiler in OneDPL link.
Verified manually with:
http://icl-jenkins2.sc.intel.com:8080/job/Tools_SH/job/test_jobs/job/onedpl_test/job/RHEL_Test/19/console
http://icl-jenkins2.sc.intel.com:8080/job/Tools_SH/job/test_jobs/job/onedpl_test/job/UB20_Test/8/console
http://icl-jenkins2.sc.intel.com:8080/job/Tools_SH/job/test_jobs/job/onedpl_test/job/UB18_Test/5/console
http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/Tools_SH%2Ftest_jobs%2Fonedpl_test%2FWin_test/detail/Win_test/46/pipeline
=> Modify Jenkinsfiles to use good compiler in the Last Good OneDPL link file

include/oneapi/dpl/pstl/glue_algorithm_ranges_defs.h, include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h, include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h, include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h, test/parallel_api/ranges/merge_ranges_sycl.pass.cpp, test/parallel_api/ranges/sort_ranges_sycl.pass.cpp, test/parallel_api/ranges/stable_sort_ranges_sycl.pass.cpp
1. Ranges API for sort, stable_sort, merge algorithms (hetero versions)
2. The minimal tests for ranges API sort, stable_sort, merge algorithms (hetero versions)
=> [dpc++] + ranges API for sort, stable_sort, merge algorithms (hetero versions), the tests

CONTRIBUTING.md
Add coding convention.
jie.jane.zhang@intel.com
=> Add coding convention.

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
The patch fixes an issue on CPU with Debug mode. Performance is not worse than before the patch.
=> Change indexing for parallel_find_or pattern

jenkinsfiles/RHEL_Check.groovy, jenkinsfiles/UB18_Check.groovy, jenkinsfiles/UB20_Check.groovy, jenkinsfiles/Windows_Check.groovy
=> Extend CI tests

include/oneapi/dpl/pstl/algorithm_impl.h
[pstl] + a hot fix for an identity value for __pattern_minmax_element
=> [pstl] + a hot fix for an identity value for __pattern_minmax_element

jenkinsfiles/Windows_Check.groovy
In some cases job status is reported incorrectly
=> CI: updating windows test steps

include/oneapi/dpl/internal/random_impl/discard_block_engine.h, include/oneapi/dpl/internal/random_impl/linear_congruential_engine.h, include/oneapi/dpl/internal/random_impl/normal_distribution.h, include/oneapi/dpl/internal/random_impl/subtract_with_carry_engine.h, include/oneapi/dpl/internal/random_impl/uniform_int_distribution.h, include/oneapi/dpl/internal/random_impl/uniform_real_distribution.h, test/rng_testsuite/statistics_tests/normal_distribution_test.pass.cpp
Add RNG optimizations and clean-up the code
=> [RNG] Add optimizations

include/oneapi/dpl/pstl/algorithm_impl.h
[pstl][host] + a hot fix for "swap" algorithm; 
A fix for host implementation of swap algo; incorrect execution policy using:
unseq,  -> were interpreted as par_unseq 
par  -> were interpreted as seq
=> [pstl][host] + a hot fix for "swap" algorithm

include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
[pstl][ranges] + a hot fix for C++11 compliance
=> [pstl][ranges] + a hot fix for C++11 compliance

documentation/library_guide/tested_standard_cpp_api.rst
Signed-off-by: gejin <ge.jin@intel.com>
Tested std API updates include:
1. std::complex llvm libcxx implementation can work in SYCL device code now with DPCPP compiler's support.
2. Some serial algorithm from <numeric> are tested in SYCL device.
=> [DOC] Update tested API library guide for 2021.2 update

documentation/library_guide/extension_api.rst
Adding paragraph to users guide describing use of async api including example.
=> Update documentation for async api

documentation/library_guide/extension_api.rst
[dpc++] + range based API for merge, sort, stable_sort algorithms
=> [dpc++] + range based API for merge, sort, stable_sort algorithms

documentation/library_guide/extension_api.rst
separate pull request including feedback from @dcbenito
=> Update async api documentation

documentation/release_notes.rst
Release Notes update for 2021.2 and typo fix in 2021.1 Release Notes
=> Release Notes update for 2021.2

documentation/library_guide/pstl_main.rst
=> + fix a typo

documentation/library_guide/pstl/dpcpp_policies_usage.rst
updated formatting to use standard Sphinx notes/ordered lists
=> Updated Note and Number Lists

documentation/CHANGES.rst
Added 2021.2 release changes and fixed typos, broken link in previous releases changes
=> Update CHANGES file with 2021.2 release changes

test/xpu_api/numerics/numeric.ops/inner.product/xpu_inner_product.pass.cpp, test/xpu_api/numerics/numeric.ops/inner.product/xpu_inner_product_comp.pass.cpp
clang-format tests and disable tests.
=> Disable some cases in inner_product tests in debug mode

test/parallel_api/algorithm/alg.nonmodifying/equal.pass.cpp
Added testing with a predicate and 4 iterators. Added cases with non-equal sized sequences.
=> Improve testing coverage for equal algorithm

test/parallel_api/numeric/numeric.ops/transform_reduce.pass.cpp
Added case with 3 iterators with default predicates. Additionally improved diagnostics.
=> Improve testing coverage of transform_reduce algorithm

test/parallel_api/algorithm/alg.sorting/alg.set.operations/includes.pass.cpp
Added case when no predicate is passed.
=> Improve testing coverage of includes algorithm

include/oneapi/dpl/pstl/iterator_impl.h, test/parallel_api/iterator/iterators.pass.cpp
1) Added default constructor to transform_iterator
2) Expanded code coverage of transform iterators methods base() and functor()
=> Added default constructor to transform_iterator and expanded code coverage of its methods

include/oneapi/dpl/pstl/tuple_impl.h
It needs to resolve issues introducing by https://github.com/intel/llvm/commit/962b00aa314831688fa3ef194fdf08f0c9dfd6cf
=> Added fully qualified namespaces for tuple implementation

include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
A hot fix for swap customization in case of using 'reverse'  algo.
=> [dpc++] A hot fix for 'reverse'  algo (CP for std::swap)

documentation/library_guide/extension_api.rst
The next subset of  range-based algorithms were added (according to #199)
=> [doc][ranges] new range-based algorithms were added

include/oneapi/dpl/internal/async_impl/async_utils.h
Fixing compilation issues for certain pattern of async api when USM or fancy iterators are used.
=> bugfix for future<Tp> with usm ptr or fancy iter.

documentation/release_notes.rst
Release Notes update for oneDPL 2021.3 release
=> Release Notes update for 2021.3

documentation/library_guide/pstl_main.rst
Updated a link to oneapi.com in PSTL Main.
=> Updated link in PSTL Main topic

test/parallel_api/numeric/numeric.ops/scan.pass.cpp
Added test for inclusive_scan algorithm's interface without initial element.
=> Code coverage improvement for the inclusive_scan algorithm

documentation/CHANGES.rst
=> Update CHANGES file with 2021.3 release changes

documentation/CHANGES.rst
=> Update CHANGES file with 2021.3 release changes (#224)

test/parallel_api/algorithm/alg.merge/inplace_merge.pass.cpp
inplace_merge is now also tested without comparator.
=> Code coverage improvement for the inplace_merge algorithm 

test/parallel_api/algorithm/alg.sorting/alg.set.operations/set.pass.cpp
set_union, set_intersection and other set algorithms are now also tested without comparator.
=> Code coverage improvement for set algorithms

include/oneapi/dpl/internal/random_impl/linear_congruential_engine.h, include/oneapi/dpl/internal/random_impl/normal_distribution.h, include/oneapi/dpl/internal/random_impl/subtract_with_carry_engine.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
Optimizations for Subtract with Carry engine + fixes for implementations for -Wall flag
=> [RNG] Optimizations for SWC and fixes for -Wall

jenkinsfiles/UB18_Check.groovy, jenkinsfiles/Windows_Check.groovy
In order to support newer compiler in CI we have to apply some alignments into CI.
=> CI: update Ubuntu 18.04 conf and fix Windows conf

include/oneapi/dpl/algorithm, include/oneapi/dpl/array, include/oneapi/dpl/async, include/oneapi/dpl/cmath, include/oneapi/dpl/complex, include/oneapi/dpl/cstddef, include/oneapi/dpl/execution, include/oneapi/dpl/functional, include/oneapi/dpl/internal/common_config.h, include/oneapi/dpl/iterator, include/oneapi/dpl/memory, include/oneapi/dpl/numeric, include/oneapi/dpl/optional, include/oneapi/dpl/random, include/oneapi/dpl/ranges, include/oneapi/dpl/ratio, include/oneapi/dpl/tuple, include/oneapi/dpl/type_traits, include/oneapi/dpl/utility
Signed-off-by: gejin <ge.jin@intel.com>
=> add gcc workaround to all public headers

jenkinsfiles/RHEL_Check.groovy, jenkinsfiles/UB18_Check.groovy, jenkinsfiles/UB20_Check.groovy, jenkinsfiles/Windows_Check.groovy
Will merge head commit of base branch when run pre-CI tests.
In this way each CI check will merge the current commit with head of base branch before launching test process.
Verified with:
http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/OneDPL_CI%2FRHEL_Check/detail/RHEL_Check/1011/pipeline
http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/OneDPL_CI%2FUB1804_Check/detail/UB1804_Check/990/pipeline
http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/OneDPL_CI%2FUB20_Check/detail/UB20_Check/860/pipeline
http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/OneDPL_CI%2FWindows_Check/detail/Windows_Check/1066/pipeline
=> [CI]Will merge head commit of base branch when run pre-CI tests

documentation/library_guide/extension_api.rst
=> [Doc] Update range-based API description

documentation/library_guide/conf.py, documentation/library_guide/extension_api.rst, documentation/library_guide/pstl/dpcpp_policies_usage.rst, documentation/library_guide/pstl/macros.rst, documentation/library_guide/tested_standard_cpp_api.rst
Minor edits to text and formatting for the 2021.4 release
I incorrectly named the branch 2021.3, but this is for 2021.4
=> Small doc edits for 2021.4

documentation/library_guide/extension_api.rst
=> Add new async algorithms to the documentation

include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
I checked the optimization (f0f68dbfb311f8c1495705b8c68bce688f6b913c) and found that it does not make notable performance improvements.
=> Making work group size multiple to a recommended size 

documentation/library_guide/conf.py, documentation/library_guide/extension_api.rst, documentation/library_guide/pstl/dpcpp_policies_usage.rst, documentation/library_guide/pstl/macros.rst, documentation/library_guide/tested_standard_cpp_api.rst
Documentation sync for 2021.4 release
=> Documentation sync for 2021.4 release

documentation/release_notes.rst
* Update release_notes.rst
* Update release_notes.rst
* Address review feedback
* Add new known issue about ``-fopenm-simd`` option 
* Remove note about internal hetero patterns rework
* Address review feedback
Singed-off-by: Valentina Kats valentina.kats@intel.com
* Address review feedback
=> Release Notes update for 2021.4 (#272)

.github/workflows/ci.yml
=> CI: workaround for vars sourcing

.github/workflows/ci.yml, jenkinsfiles/RHEL_Check.groovy, jenkinsfiles/UB20_Check.groovy, jenkinsfiles/Windows_Check.groovy
=> CI: extend GitHub Actions testing

include/oneapi/dpl/internal/random_impl/exponential_distribution.h, include/oneapi/dpl/random, test/rng_testsuite/interface_tests/distributions_methods.pass.cpp, test/rng_testsuite/statistics_tests/exponential_distribution_test.pass.cpp
Add exponential distribution and tests
=> [RNG] Implemented exponential distribution

include/oneapi/dpl/internal/random_impl/bernoulli_distribution.h, include/oneapi/dpl/internal/random_impl/exponential_distribution.h, include/oneapi/dpl/internal/random_impl/geometric_distribution.h, include/oneapi/dpl/internal/random_impl/normal_distribution.h, include/oneapi/dpl/internal/random_impl/uniform_int_distribution.h, include/oneapi/dpl/internal/random_impl/uniform_real_distribution.h, include/oneapi/dpl/random, test/rng_testsuite/interface_tests/distributions_methods.pass.cpp, test/rng_testsuite/statistics_tests/bernoulli_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/geometric_distribution_test.pass.cpp
Implement bernoulli and geometric distributions and tests
=> [RNG] Implement bernoulli and geometric distributions

include/oneapi/dpl/internal/async_impl/async_utils.h, include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h, include/oneapi/dpl/internal/function.h, include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h, include/oneapi/dpl/internal/reduce_by_segment_impl.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h, include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h, include/oneapi/dpl/pstl/utils.h, test/parallel_api/numeric/numeric.ops/reduce_by_segment_zip.pass.cpp
[dpc++][pstl][zip] + support embedded zip iterators with tmp SYCL buffers in PSTL implementation
=> [dpc++][pstl][zip] + support embedded zip iterators with tmp SYCL buffers in PSTL implementation

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h, include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h, include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h, include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h, include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h, test/general/buffer_wrapper.pass.cpp, test/general/lambda_naming.pass.cpp, test/support/utils_sycl.h
[dpc++][sycl] deprectations support: namespace renamed: __sycl to __dpl_sycl
=> [dpc++][sycl] deprectations support: namespace renamed: __sycl to __dpl_sycl

documentation/library_guide/tested_standard_cpp_api.rst, include/oneapi/dpl/algorithm, test/xpu_api/algorithms/alg.nonmodifying/alg.count/xpu_count.pass.cpp, test/xpu_api/algorithms/alg.nonmodifying/alg.count/xpu_count_if.pass.cpp, test/xpu_api/algorithms/alg.nonmodifying/alg.foreach/xpu_for_each.pass.cpp
=> Add serial count, count_if and for_each to oneapi::dpl

documentation/library_guide/random.rst
Add documentation for new distributions
=> [RNG] Add documentation

jenkinsfiles/RHEL_Check.groovy, jenkinsfiles/UB18_Check.groovy, jenkinsfiles/UB20_Check.groovy, jenkinsfiles/Windows_Check.groovy
=> CI: add test configuration names to Jenkins pipeline name

test/rng_testsuite/statistics_tests/bernoulli_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/exponential_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/extreme_value_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/geometric_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/lognormal_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/normal_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/uniform_int_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/uniform_real_distribution_test.pass.cpp, test/rng_testsuite/statistics_tests/weibull_distribution_test.pass.cpp
=> [RNG] Returning tests

include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h, test/support/utils_sycl.h
[oneDPL][sycl] + usage of new namespaces ext::oneapi, ext::intel
=> [oneDPL][sycl] + usage of new namespaces ext::oneapi, ext::intel

documentation/release_notes.rst
Signed-off-by: valentina.kats@intel.com
=> Update release notes for oneDPL 2021.5 release

documentation/library_guide/api_for_dpcpp_kernels/tested_standard_cpp_api.rst, include/oneapi/dpl/algorithm, include/oneapi/dpl/internal/serial_algorithm_impl.h, test/xpu_api/algorithms/alg.nonmodifying/alg.foreach/xpu_for_each_n.pass.cpp
=> [oneDPL] Add serial for_each_n to oneapi::dpl

documentation/library_guide/api_for_dpcpp_kernels/tested_standard_cpp_api.rst, include/oneapi/dpl/algorithm, test/xpu_api/algorithms/alg.modifying.operations/alg.copy/xpu_copy.pass.cpp, test/xpu_api/algorithms/alg.modifying.operations/alg.copy/xpu_copy_backward.pass.cpp, test/xpu_api/algorithms/alg.modifying.operations/alg.copy/xpu_copy_if.pass.cpp, test/xpu_api/algorithms/alg.modifying.operations/alg.copy/xpu_copy_n.pass.cpp
=> Add serial copy to oneapi::dpl

documentation/release_notes.rst
signed-off-by: Valentina Kats valentina.kats@intel.com
=> Add a new Known Issue into Release Notes for oneDPL 2021.5

documentation/CHANGES.rst
=> Update CHANGES with 2021.4 and 2021.5 changes

README.md
=> Update link to oneDPL documentation

README.md
(cherry picked from commit d3952ec42f3df0c5c9e1abae8bbf8720b137516a)
=> Update link to oneDPL documentation (#370)

.github/workflows/ci.yml
=> CI: enable testing on macOS (OpenMP backend + icpc compiler)

include/oneapi/dpl/pstl/iterator_defs.h, test/support/utils_sycl.h
Just noticed a couple of misspellings and prepared a quick fix.
=> Fix a couple of misspellings  

CONTRIBUTING.md, README.md, documentation/CHANGES.rst, documentation/library_guide/api_for_dpcpp_kernels/tested_standard_cpp_api.rst, documentation/library_guide/macros.rst, documentation/library_guide/onedpl_gsg.rst, documentation/library_guide/overview.rst, documentation/library_guide/parallel_api/buffers_and_usm.rst, documentation/library_guide/parallel_api/execution_policies.rst, documentation/library_guide/parallel_api/range_based_api.rst, documentation/release_notes.rst
=> Documentation sync for 2021.6

_static/documentation_options.js, api_for_dpcpp_kernels/random.html, api_for_dpcpp_kernels/tested_standard_cpp_api.html, api_for_dpcpp_kernels/utility_function_object_classes.html, api_for_dpcpp_kernels_main.html, genindex.html, index.html, macros.html, notices_disclaimers.html, onedpl_gsg.html, overview.html, parallel_api/additional_algorithms.html, parallel_api/async_api.html, parallel_api/buffers_and_usm.html, parallel_api/execution_policies.html, parallel_api/iterators.html, parallel_api/range_based_api.html, parallel_api_main.html, search.html
=> Fix version typo

documentation/library_guide/conf.py
=> Update documentation version for 2021.6 release

documentation/library_guide/conf.py
=> Update documentation version for 2021.6 release (#453)

test/parallel_api/algorithm/alg.sorting/sort.pass.cpp, test/parallel_api/algorithm/alg.sorting/sort_by_key.pass.cpp
1) Expanded test sort.pass.cpp for USM shared/device memory
2) Added new test sort_by_key.pass.cpp for USM shared/device memory
=> Expand test sort.pass.cpp for USM shared/device memory

.gitignore, documentation/library_guide/.gitignore, documentation/library_guide/Makefile
BUILDDIR changed from _build to build in  documentation/library_guide files
=> Updated files to change _build to build

include/oneapi/dpl/functional
Signed-off-by: Sobolev, Dmitriy <dmitriy.sobolev@intel.com>
=> Do not use entities with c++20 removed in this revision

documentation/library_guide/Makefile
Removed ditaxml info (specific to IDZ builds)
=> Updated Doc Makefile

documentation/library_guide/api_for_dpcpp_kernels/tested_standard_cpp_api.rst, include/oneapi/dpl/algorithm, test/xpu_api/algorithms/alg.sorting/alg.sort/is.sorted/xpu_is_sorted.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.sort/is.sorted/xpu_is_sorted_comp.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.sort/is.sorted/xpu_is_sorted_until.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.sort/is.sorted/xpu_is_sorted_until_comp.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.sort/partial.sort.copy/xpu_partial_sort_copy.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.sort/partial.sort.copy/xpu_partial_sort_copy_comp.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.sort/partial.sort/xpu_partial_sort.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.sort/partial.sort/xpu_partial_sort_comp.pass.cpp
=> Add serial sort algorithm to oneapi::dpl

documentation/library_guide/api_for_dpcpp_kernels/tested_standard_cpp_api.rst, include/oneapi/dpl/algorithm, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/is.heap/xpu_is_heap.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/is.heap/xpu_is_heap_comp.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/is.heap/xpu_is_heap_until.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/is.heap/xpu_is_heap_until_comp.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/make.heap/xpu_make_heap.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/make.heap/xpu_make_heap_comp.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/pop.heap/xpu_pop_heap.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/pop.heap/xpu_pop_heap_comp.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/push.heap/xpu_push_heap.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/push.heap/xpu_push_heap_comp.pass.cpp
=> Add serial heap algorithm to oneapi::dpl

documentation/release_notes.rst
=> Update release notes for oneDPL 2021.6.1

documentation/CHANGES.rst
=> Update CHANGES with 2021.6.1 changes

documentation/CHANGES.rst, documentation/release_notes.rst
* Update release_notes.rst
* Update CHANGES.rst
(cherry picked from commit 0bd676a2e45074c7d5c59242eb6c36bc76a52aa8)
=> Fix format in release notes and changes files (#499)

documentation/library_guide/api_for_dpcpp_kernels/tested_standard_cpp_api.rst, include/oneapi/dpl/algorithm, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/sort.heap/xpu_sort_heap.pass.cpp, test/xpu_api/algorithms/alg.sorting/alg.heap.operations/sort.heap/xpu_sort_heap_comp.pass.cpp
=> Add serial sort_heap algorithm to oneapi::dpl

examples/random/src/main.cpp
Fixed compile error in CI -  error: SYCL kernel cannot use a non-const global variable
=> Fix CI build errors in tests

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
Using one kernel bundle for several kernels.
=> Using one kernel bundle for several kernels

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
[onedpl][sycl] + a hot fix for sycl::program support.
Tested with SYCL OS 2021.09.21 
http://cmplrexplorer.intel.com/z/7Ex8fG
=> [onedpl][sycl] + a hot fix for sycl::program support

include/oneapi/dpl/internal/reduce_by_segment_impl.h
=> [oneDPL] removed unused ValueType

test/support/utils.h, test/support/utils_sycl.h
Added comment for test offset const
=> Add comment for test offset const

documentation/library_guide/onedpl_gsg.rst
=> Added pkg-config support info to GSG

test/support/iterator_utils.h
Fixed errors in BidirectionalIterator :
1) BidirectionalIterator operator++()  --->>> BidirectionalIterator& operator++()
2) BidirectionalIterator operator--()  --->>> BidirectionalIterator& operator--()
=> Make BidirectionalIterator from tests fulfill Iterator requirements

documentation/library_guide/conf.py, documentation/library_guide/overview.rst, documentation/library_guide/parallel_api/execution_policies.rst
=> Update documentation for 2021.7

documentation/CHANGES.rst, documentation/release_notes.rst
Signed off by: Valentina Kats valentina.kats@intel.com
=> Update release notes and changes for 2021.7

documentation/library_guide/onedpl_gsg.rst
(cherry picked from commit 527fbca672c95e853f9d3728f7f7fccc9cc87a1a)
=> GSG update for 2021.7

documentation/library_guide/_templates/footer.html, documentation/library_guide/_templates/layout.html, documentation/library_guide/requirements.txt
Added content to the _templates folder. Updated layout.html and added footer.html for collecting analytics.
=> Analytics step 2

include/oneapi/dpl/internal/async_impl/async_impl_hetero.h, include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h, include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h, include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h, test/parallel_api/numeric/numeric.ops/in_place_scan.pass.cpp, test/parallel_api/numeric/numeric.ops/scan.pass.cpp
[oneDPL] + a fix for in-place scan, dpcpp policy, a test was added as well
=> [oneDPL] + a fix for in-place scan, dpcpp policy, a test was added as well

documentation/library_guide/conf.py
=> Update documentation version for oneDPL 2021.7.1

jenkinsfiles/RHEL_Check.groovy, jenkinsfiles/UB18_Check.groovy, jenkinsfiles/UB20_Check.groovy, jenkinsfiles/Windows_Check.groovy
Signed-off-by: Xiaodong Li <xiaodong.li@intel.com>
Verified with:
https://github.com/oneapi-src/oneDPL/pull/620#partial-pull-merging
=> [CI] Update Jenkins files for CI checks

documentation/release_notes.rst
=> Update release notes for oneDPL 2021.7.1

test/xpu_api/numerics/complex.number/ccmplx/ccomplex.pass.cpp
Remove absent file from includes
=> [tests] Remove absent file inclusion from ccomplex.pass.cpp

documentation/library_guide/parallel_api/iterators.rst
Updated example for permutation_iterator.
=> Update example for permutation_iterator in our documentation

test/parallel_api/algorithm/alg.sorting/sort.pass.cpp
[oneDPL] sort test coverage extension: + negative data, unsigned type
=> [oneDPL] sort test coverage extension: + negative data, unsigned type

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
My sense of beauty really wants this change:)
=> Change _Ascending helper definition

documentation/index.rst, documentation/library_guide/index.rst, documentation/library_guide/oneDPL_2022.0_changes.rst
Description of breaking changes in oneDPL 2022.0.0 release
=> oneDPL 2022.0.0 changes description

test/support/iterator_utils.h, test/support/utils_invoke.h
In this PR we fix usage of potentially moved object in test utils
=> Fix usage of moved local variable in test utils

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
The guess is `__in` is some conflicting name with macro that defined in Microsoft header. We don't have `__in` as the name in other places
=> Fix conflicting argument names

documentation/release_notes.rst
Release notes for oneDPL 2022.0.0
=> Update release notes for oneDPL 2022.0

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
[oneDPL] one group radix_sort: + kernel name "provider": auto or a custom(user) name  plus call number.
=> [oneDPL] one group radix_sort, kernel name: auto or a custom(user) name + call number

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h, include/oneapi/dpl/pstl/utils.h
=> Use CHAR_BIT or numeric_limits for the size of a byte

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
[onedpl][hetero][radix] a hot fix for 64bit integer types
=> [onedpl][hetero][radix] a hot fix for 64bit integer types

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
Move check of ```_IsGPU{}``` to compile time.
=> Check _IsGPU{} in compile time

.github/workflows/ci.yml
CPU,bknd=dpcpp,cmplr=icpx,windows-2019,std=c++17,cfg=release job was failing after a a conda update. I fixed the script to run the job successfully.
=> CI: Fix TBB misconfiguration issue on Windows systems

include/oneapi/dpl/pstl/algorithm_fwd.h, include/oneapi/dpl/pstl/algorithm_impl.h, include/oneapi/dpl/pstl/glue_algorithm_defs.h, include/oneapi/dpl/pstl/glue_algorithm_impl.h, include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h, test/parallel_api/algorithm/alg.sorting/sort_by_key.pass.cpp
[oneDPL][host][hetero] + sort_by_key API
=> [oneDPL][host][hetero] + sort_by_key API

test/CMakeLists.txt
In this PR we revert https://github.com/oneapi-src/oneDPL/pull/910 - we have access violation in tests
=> Revert PR "Setup _ITERATOR_DEBUG_LEVEL to 0 on Windows for tests"

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_cooperative.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h, test/parallel_api/experimental/radix_sort_esimd.pass.cpp
A part of changes in #918 that improves the test and corrects the copyright headers.
=> [KT] Improve the radix sort test

include/oneapi/dpl/experimental/kt/esimd_radix_sort_cooperative.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h
A part of code changes in #918 that is non-contradictory and generally useful.
=> [KT] Improve the radix sort utilities

include/oneapi/dpl/experimental/kt/esimd_radix_sort_cooperative.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h, test/parallel_api/experimental/radix_sort_esimd.pass.cpp
Small improvements here and there come as a bonus :)
=> [KT] Add support for signed and floating point types to cooperative radix sort

test/parallel_api/iterator/zip_iterator.pass.cpp
Adds a test case to `zip_iterator.pass.cpp` using `oneapi::dpl::zip_iterator`  and `oneapi::dpl::discard_iterator`.  Provided as an example of an simpler rewrite of the previous test case which uses `oneapi::dpl::transform_iterator` with `std::forward_as_tuple` and `std::ignore` to accomplish the same effect as described in #949.
=> Add zip_iterator with discard_iterator example

include/oneapi/dpl/experimental/kt/esimd_radix_sort_cooperative.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
In this PR we remove commented code from esimd radix sort implementation.
=> [KT] Remove commented code

test/parallel_api/experimental/radix_sort_esimd.pass.cpp
=> Small test refactoring

licensing/third-party-programs.txt
=> Add new 3rd party component

include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h
Let's calculate the number of stages only once.
=> [KT] Pass number of stages to histogram kernel

documentation/release_notes.rst
=> Update release notes for oneDPL 2022.1.1

include/oneapi/dpl/experimental/kernel_templates, include/oneapi/dpl/experimental/kt/esimd_radix_sort.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h, include/oneapi/dpl/experimental/kt/kernel_param.h, test/parallel_api/experimental/radix_sort_esimd.pass.cpp
- Adding a dedicated namespace under `experimental`
- Move generic kernel configuration parameters into a special class
- Changing an execution policy to a SYCL queue
- Some uglification
- A fix for a compilation error in the test
=> [KT] API adjustments

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h, test/kt/esimd_radix_sort.cpp
In this PR skip all test cases with an error "LLVM ERROR: SLM size exceeds target limits"
=> [KT] Skip all test cases with an error "LLVM ERROR: SLM size exceeds target limits"

test/parallel_api/dynamic_selection/sycl/test_sycl_sanity.pass.cpp, test/support/sycl_sanity.h
Updates to fix the sycl warnings from the API changes.
=> Deprecated sycl warnings fix

include/oneapi/dpl/internal/dynamic_selection.h, include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy_impl.h, include/oneapi/dpl/internal/dynamic_selection_impl/static_policy_impl.h, test/parallel_api/dynamic_selection/sycl/test_round_robin_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_static_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/test_round_robin_policy_inline.pass.cpp, test/parallel_api/dynamic_selection/test_static_policy_inline.pass.cpp, test/support/test_ds_utils.h
1. Refactoring invoke_async to submit
2. Refactoring invoke to submit_and_wait
=> Refactoring submit and submit_and_wait

include/oneapi/dpl/internal/dynamic_selection.h, include/oneapi/dpl/internal/dynamic_selection_impl/backend_defs.h, include/oneapi/dpl/internal/dynamic_selection_impl/scoring_policy_defs.h, include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h, test/parallel_api/dynamic_selection/sycl/test_internal_sycl_scheduler.pass.cpp, test/parallel_api/dynamic_selection/test_internal_inline_scheduler.pass.cpp, test/support/inline_backend.h, test/support/test_ds_utils.h
Added unwrap and modified tests
Created execution_info namespace, moved properties and updated policies and tests
=> [Dynamic Selection] Added unwrap and execution_info support

include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy_impl.h
Added offset and initialization
=> RR updates

include/oneapi/dpl/dynamic_selection, include/oneapi/dpl/internal/dynamic_selection_impl/static_policy_impl.h, test/parallel_api/dynamic_selection/sycl/test_static_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/test_static_policy_inline.pass.cpp
Added offset, initialize and changed name to fixed resource policy.
Will change the file names in a different PR. Didn't want to bite too much.
=> Fixed resource policy updates

test/parallel_api/dynamic_selection/sycl/test_dynamic_load_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_internal_sycl_scheduler.pass.cpp
Deprecated sycl warning removal
=> sycl warning fixes

include/oneapi/dpl/internal/dynamic_selection_impl/fixed_resource_policy.h
Initialized the offset, updated the constructor types.
=> fixed resource updates

documentation/library_guide/conf.py
Update documentation version for oneDPL 2022.3.0.
Signed-off-by Valentina Kats valentina.kats@intel.com
=> Update documentation version for oneDPL 2022.3.0

include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy.h
=> RRP updates

test/parallel_api/dynamic_selection/sycl/test_dynamic_load_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_fixed_resource_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_round_robin_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/test_auto_tune_policy_inline.pass.cpp, test/parallel_api/dynamic_selection/test_dynamic_load_policy_inline.pass.cpp, test/parallel_api/dynamic_selection/test_fixed_resource_policy_inline.pass.cpp, test/parallel_api/dynamic_selection/test_round_robin_policy_inline.pass.cpp, test/support/test_dynamic_load_utils.h, test/support/test_dynamic_selection_utils.h
=> Fixing Auto-tune policy tests and adding test_select to all policies

include/oneapi/dpl/internal/dynamic_selection.h
Moving helpers to internal namespaces
=> moving helpers to internal 

include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h
The file doesn't exist anymore.
=> [Dynamic Selection] remove concurrent_queue.h header file from sycl_backend.h

include/oneapi/dpl/dynamic_selection, include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h, include/oneapi/dpl/internal/dynamic_selection_traits.h
Moved the header files to the out dynamic_selection and renamed the file dynamic_selection.h to dynamic_selection_traits.h
=> [Dynamic Selection] Added dynamic_selection_traits.h

.github/workflows/ci.yml
Let's test FPGA backend in the CI to detect any related issues early.
=> [CI] add FPGA emulator testing

include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
Restores auto tune timing indexing inadvertently removed.
=> auto_tune_fixes

documentation/library_guide/cmake_support.rst, documentation/library_guide/onedpl_gsg.rst
Updated the GSG and a header in the cmake_support file.
=> Add info on oneAPI Samples Catalog

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_onesweep.h, include/oneapi/dpl/experimental/kt/esimd_radix_sort_utils.h
Also, `class simd2d` was removed because it is not used.
=> [KT] Uglification

include/oneapi/dpl/dynamic_selection, include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h, include/oneapi/dpl/internal/dynamic_selection_impl/dynamic_load_policy.h, include/oneapi/dpl/internal/dynamic_selection_impl/fixed_resource_policy.h, include/oneapi/dpl/internal/dynamic_selection_impl/policy_traits.h, include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy.h, include/oneapi/dpl/internal/dynamic_selection_impl/scoring_policy_defs.h, include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h, include/oneapi/dpl/internal/dynamic_selection_traits.h, test/parallel_api/dynamic_selection/sycl/test_auto_tune_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_dynamic_load_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_fixed_resource_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_internal_sycl_scheduler.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_round_robin_policy_sycl.pass.cpp, test/parallel_api/dynamic_selection/sycl/test_sycl_sanity.pass.cpp, test/parallel_api/dynamic_selection/test_auto_tune_policy_inline.pass.cpp, test/parallel_api/dynamic_selection/test_customizations.pass.cpp, test/parallel_api/dynamic_selection/test_dynamic_load_policy_inline.pass.cpp, test/parallel_api/dynamic_selection/test_fixed_resource_policy_inline.pass.cpp, test/parallel_api/dynamic_selection/test_internal_inline_scheduler.pass.cpp, test/parallel_api/dynamic_selection/test_round_robin_policy_inline.pass.cpp, test/support/test_dynamic_load_utils.h, test/support/test_dynamic_selection_one_policy.h, test/support/test_dynamic_selection_utils.h
=> [Dynamic Selection] Modify Dynamic Selection files to clang format

include/oneapi/dpl/pstl/unseq_backend_simd.h
[onedpl][simd] cleanup - removed the unused 'simd_walk_1'
=> [onedpl][simd] cleanup - removed the unused 'simd_walk_1'

documentation/release_notes.rst
Update Release Notes for oneDPL 2022.3.0 release. 
=> Update Release Notes for 2022.3.0 release

documentation/library_guide/dynamic_selection_api/auto_tune_policy.rst, documentation/library_guide/dynamic_selection_api/dynamic_load_policy.rst, documentation/library_guide/dynamic_selection_api/fixed_resource_policy.rst, documentation/library_guide/dynamic_selection_api/functions.rst, documentation/library_guide/dynamic_selection_api/policies.rst, documentation/library_guide/dynamic_selection_api/round_robin_policy.rst, documentation/library_guide/dynamic_selection_api_main.rst, documentation/library_guide/index.rst
Documentation draft for dynamic selection
=> Add documentation for dynamic selection

documentation/library_guide/introduction.rst, documentation/library_guide/introduction/onedpl_gsg.rst
Updated links in Intro and GSG.
=> Update links for 2022.3 release

test/parallel_api/algorithm/alg.nonmodifying/transform_if.pass.cpp
Fixing unnamed lambda in transform_if tests. (same mangled name)
=> Fixing transform_if test for unnamed lamdba

include/oneapi/dpl/experimental/kt/esimd_radix_sort.h, include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h, include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h, include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h, include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_utils.h, include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h, include/oneapi/dpl/pstl/utils_ranges.h
The purpose of this PR is to reduce code duplication.
=> [KT] Merge radix_sort and radix_sort_by_key middle layer entities

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
Co-authored-by: Dmitriy Sobolev <Dmitriy.Sobolev@intel.com>
(cherry picked from commit 075b3e9f3b97261009a4c094c786fb88bf3a187f)
=> [onedpl][hetero][radix] a hot fix for 64bit integer types (#878)

documentation/library_guide/parallel_api/additional_algorithms.rst
Adds documentation of transform_if (https://github.com/oneapi-src/oneDPL/pull/276) to additional algorithms.
=> Adding documentation for transform_if to guide

documentation/library_guide/introduction.rst, documentation/library_guide/parallel_api/additional_algorithms.rst, documentation/library_guide/parallel_api/iterators.rst
Pulling in updates to documentation that would benefit the 2022.4 release.
=> Cherry-pick doc updates to 2022.4

documentation/library_guide/requirements.txt
=> [Doc] Fix doc generation (note:: directive)

test/parallel_api/iterator/permutation_iterator.h, test/parallel_api/iterator/permutation_iterator.pass.cpp, test/support/utils.h, test/support/utils_test_base.h
In this PR we implement results check for premutation iterator tests.
This PR corelated with https://github.com/oneapi-src/oneDPL/pull/1325
=> [test] Check results for any patterns with permutation iterator

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h, include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
Static analysis has identified a function marked as noexcept where the SYCL code called may through an exception.  A separate issue identified is the use of an object after it was forwarded.  This PR addresses both issues.
=> Address issues in algorithms identified by static analysis

include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h, include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
Cherry-picking the updates from #1340
=> Update release with static analysis fixes

include/oneapi/dpl/internal/dynamic_selection_impl/fixed_resource_policy.h, include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy.h, include/oneapi/dpl/internal/dynamic_selection_impl/scoring_policy_defs.h, test/support/test_config.h
*Dropping std::decay where it's not needed
*Renaming offset to index in fixed policy
etc
=> Fixing comments from original DS integration

documentation/library_guide/introduction.rst
A limitation about algorithms which work with an uninitialized storage added to introduction.rst
=> [oneDPL][doc] A limitation about algorithms which work with an uninitialized storage.

documentation/library_guide/parallel_api/iterators.rst
[oneDPL][doc] + limitation for permutation_iterator using
=> [oneDPL][doc]  limitation for permutation_iterator using

include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
1. Added a static assert for submit - sizeof...(KeyArgs) == sizeof...(Args)
2. Removed std::decay for wrapped_resource_t
=> [Dynamic Selection] Addressed comments for auto tune policy

documentation/release_notes.rst
Update Release Notes for oneDPL 2022.4.0
=> Update Release Notes for oneDPL 2022.4.0

documentation/library_guide/kernel_templates/esimd/radix_sort.rst, documentation/library_guide/kernel_templates/esimd_main.rst, documentation/library_guide/kernel_templates/kernel_configuration.rst, documentation/library_guide/kernel_templates_main.rst, documentation/library_guide/parallel_api/pass_data_algorithms.rst, documentation/library_guide/parallel_api/range_based_api.rst, documentation/release_notes.rst
Add a structure for any kernel template (for future extension) and document esimd-based ones.
=> [Doc] Document Kernel Templates

.github/workflows/ci.yml
The change aims to cover the basic functionality from #1457.
=> [CI] Add c++20 configurations with tests for ranges

include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h, include/oneapi/dpl/internal/reduce_by_segment_impl.h, include/oneapi/dpl/internal/scan_by_segment_impl.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h, include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
[oneDPL][sycl] + sycl::is_device_copyable specialization of the SYCL trait for some oneDPL types.
=> [oneDPL][sycl] sycl::is_device_copyable specialization of the SYCL trait for some oneDPL types

documentation/release_notes.rst
oneDPL 2022.5.0 Release Notes Update
=> oneDPL 2022.5.0 Release Notes Update

test/parallel_api/ranges/transform2_ranges_sycl.pass.cpp
[oneDPL][ranges] + another hot fix for a test (experimental ranges)
=> [oneDPL][ranges] Another hot fix for a test (experimental ranges)

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
This PR addresses the post-merge comment of @SergeyKopienko: https://github.com/oneapi-src/oneDPL/pull/1487#discussion_r1562196963
=> Improve bad alloc check in #1487

SECURITY.md
Security policy update to support UXL Foundation Guidelines.
=> Update Security Policy

documentation/library_guide/kernel_templates/single_pass_scan.rst, documentation/library_guide/kernel_templates_main.rst, test/kt/single_pass_scan.cpp
This PR adds documentation for the scan kernel template.
=> Documentation for scan kernel template

documentation/library_guide/kernel_templates/single_pass_scan.rst
This PR adds a citation for decoupled lookback.
=> Add citation to scan kernel template documentation

documentation/library_guide/parallel_api/iterators.rst
A sub-bullet list didn't have the correct white space for a sub-bullet list, I have fixed and tested the fix.
=> Fixed a bullet list in the iterators topic.

documentation/release_notes.rst
Added oneDPL 2022.6.0 Release Notes
=> Update Release Notes for oneDPL 2022.6.0 release

include/oneapi/dpl/experimental/kt/two_pass_scan.h, test/kt/CMakeLists.txt, test/kt/two_pass_scan.cpp
This PR adds support for iterators / buffers / ranges to the prototype two-pass scan algorithm.
=> [PROTOTYPE] Add support for iterators / buffers / ranges to two-pass scan

test/kt/two_pass_scan.cpp
This PR adds tests for all of the numeric types for the two-pass scan prototype.
=> [PROTOTYPE] Improve tests for two-pass scan

include/oneapi/dpl/internal/distributed_ranges_impl/detail/ranges_shim.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/detail/sycl_utils.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/algorithms/exclusive_scan.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/algorithms/fill.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/algorithms/inclusive_scan.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/algorithms/reduce.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/algorithms/sort.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/init.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/remote_vector.hpp
also removed && from operators and comparators and added comment about remote_vector
=> Jiraids removed

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
#1653 saw significant slowdowns in FPGA emulation over mainline. These are due to high work-group sizes (65536 on my test system). This limits the work-group size to 2048, which has shown to provide a good balance between throughput and required synchronization in group reductions.
=> Limit work-group size to fix FPGA slowdowns in find_or (#1653)

include/oneapi/dpl/experimental/kt/two_pass_scan.h, test/kt/two_pass_scan.cpp
Adding no-init inclusive scan.  Initial draft, can probably clean this up a bit, but this is passing tests.  
Using existing `__init_processing` where possible, but we need to reach in to handle some cases directly within the kernel to avoid default construction.  I attempt to keep order of operations consistent here with the existing code, skipping calculations which don't exist.
Refactoring repeating code into scan_through_elements_helper with some constexpr branches to represent required differences.
Also adding test to exercise new API.
=> [PROTOTYPE] two pass scan: no_init processing for inclusive scan

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
A minor code change - sycl::kernel_bundle API usage fixes.
=> [oneDPL][sycl] sycl::kernel_bundle API usage fixes

include/oneapi/dpl/internal/distributed_ranges_impl/shp/algorithms/exclusive_scan.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/algorithms/inclusive_scan.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/shp/algorithms/sort.hpp
as requested in https://github.com/oneapi-src/oneDPL/pull/1479#discussion_r1680082872
=> preserve dpl futures in exclusive_scan and sort

include/oneapi/dpl/internal/distributed_ranges_impl/detail/utils.hpp
=> Remove extraneous function

include/oneapi/dpl/dynamic_selection
Existing check is not permissive enough to work with https://github.com/intel/llvm
=> Enable DS with intel/llvm

include/oneapi/dpl/internal/distributed_ranges_impl/sp/algorithms/exclusive_scan.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/sp/algorithms/inclusive_scan.hpp, include/oneapi/dpl/internal/distributed_ranges_impl/sp/algorithms/reduce.hpp
Removed redundant conditions (assert/if) in ex/inclusive_scan and reduce implementations
=> Redundant conditions removed

include/oneapi/dpl/internal/distributed_ranges_impl/sp/zip_view.hpp
applying https://github.com/oneapi-src/oneDPL/pull/1479#discussion_r1686700981
=> removed is_owning_view

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h, include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h, include/oneapi/dpl/pstl/parallel_backend_utils.h
needed to compile distributed-ranges with latest oneDPL
=> removed unused type

documentation/library_guide/api_for_sycl_kernels/random.rst, documentation/library_guide/api_for_sycl_kernels/utility_function_object_classes.rst, documentation/library_guide/introduction.rst, documentation/library_guide/parallel_api/async_api.rst, documentation/library_guide/parallel_api/execution_policies.rst, documentation/library_guide/parallel_api/iterators.rst, documentation/library_guide/parallel_api/pass_data_algorithms.rst, documentation/library_guide/parallel_api_main.rst
A number of various improvements in the documentation files.
It might be simpler to review each commit in the patch individually, as the total diff seems somewhat messy.
=> Documentation improvements

include/oneapi/dpl/pstl/algorithm_impl.h
Fixed oneDPL which has some unused type and that fails DR compilation.
=> removed unused _ValueType type

include/oneapi/dpl/internal/random_impl/exponential_distribution.h
I came across my copy-paste mistake in exponential_distribution code. Now it's fixed
=> [RNG] exponential distribution operator>> fix

documentation/library_guide/dynamic_selection_api/auto_tune_policy.rst
I have added a note about the auto_tune_policy with direction from @timmiesmith.
=> Add auto_tune_policy note

CREDITS.txt
As @dmitriy-sobolev mentioned in https://github.com/oneapi-src/oneDPL/pull/1849 , I would be very glad if I could be added to CREDITS.txt
=> Add Xewar313 to CREDITS.txt

documentation/release_notes.rst
Please review the notes I've compiled based on the input from contributors for the pending release.
=> Release notes for 2022.7.0

include/oneapi/dpl/internal/random_impl/bernoulli_distribution.h, include/oneapi/dpl/internal/random_impl/cauchy_distribution.h, include/oneapi/dpl/internal/random_impl/exponential_distribution.h, include/oneapi/dpl/internal/random_impl/extreme_value_distribution.h, include/oneapi/dpl/internal/random_impl/geometric_distribution.h, include/oneapi/dpl/internal/random_impl/lognormal_distribution.h, include/oneapi/dpl/internal/random_impl/random_common.h, include/oneapi/dpl/internal/random_impl/weibull_distribution.h, test/xpu_api/random/interface_tests/engines_methods.pass.cpp, test/xpu_api/random/statistics_tests/bernoulli_distribution_test.pass.cpp, test/xpu_api/random/statistics_tests/uniform_int_distribution_test.pass.cpp, test/xpu_api/random/statistics_tests/uniform_real_distribution_test.pass.cpp, test/xpu_api/random/template_tests/linear_congruential_std_template_test.pass.cpp, test/xpu_api/random/template_tests/subtract_with_carry_std_template_test.pass.cpp
Fixed warnings in the `<random>` part. Warnings are shown if  `-Wall -Wextra` are switching on
=> [RNG] Fixed warnings in the <random> part

include/oneapi/dpl/pstl/algorithm_ranges_impl.h, include/oneapi/dpl/pstl/glue_algorithm_impl.h, include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h, include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
[oneDPL][ranges] + dispatch fixes for ranges::sort, ranges::sort_stable implementation
=> [oneDPL][ranges] + dispatch fixes for ranges::sort, ranges::sort_stable implementation

include/oneapi/dpl/pstl/utils_ranges.h
It fixes `header_order_ranges_1` test.
=> Include a missing header

documentation/library_guide/common_cross_document_links.txt, documentation/library_guide/dynamic_selection_api/auto_tune_policy.rst, documentation/library_guide/dynamic_selection_api/fixed_resource_policy.rst, documentation/library_guide/dynamic_selection_api/round_robin_policy.rst
There were three instances of curly quotes in text, plus removed whitespace at the end of lines.
=> Update curly quotes 2022.7

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
In this PR we combine two submitters `__parallel_merge_submitter` and `__parallel_merge_submitter_large` into one `__parallel_merge_submitter`
=> Combine two submitters `__parallel_merge_submitter` and `__parallel_merge_submitter_large` into one `__parallel_merge_submitter`

.github/workflows/ci-testing.yml
=> Update ICX/oneTBB links in the CI

make/Makefile.common
A makefile fix: usage of ONEAPI_DEVICE_SELECTOR variable
=> [oneDPL][make] A fix: usage of ONEAPI_DEVICE_SELECTOR variable

include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
Fixing spelling-check error in comment
=> Fix spelling-check error

documentation/library_guide/parallel_api/execution_policies.rst
Addresses https://github.com/uxlfoundation/oneDPL/issues/1965.
=> Remove device selector as an argument to construct a policy

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h, include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h, include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
This PR cherry-picks the commits to resolve radix sort and histogram barrier issues into the branch for the 2022.8.0 release.
=> Fix synchronization issues in radix sort and histogram (#2054)

documentation/library_guide/introduction.rst, documentation/release_notes.rst
---------
Co-authored-by: Matthew Michel <106704043+mmichel11@users.noreply.github.com>
Co-authored-by: Dmitriy Sobolev <Dmitriy.Sobolev@intel.com>
Co-authored-by: Alexey Kukanov <alexey.kukanov@intel.com>
Co-authored-by: Matthew Michel <matthew.michel@intel.com>
=> Cherry pick release notes to 2022.8.0 branch

documentation/library_guide/notices_disclaimers.rst, documentation/release_notes.rst
This PR contains changes that were identified in Release Notes after #2068 was merged.
=> Small corrections to 2022 8 release notes and an update to notices and disclaimers

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
Minor bugfix for forwarding of policy.
found by @SergeyKopienko
=> Fix policy forwarding for fpga histogram

test/support/utils_device_copyable.h
In this PR we fixing some spelling check errors in tests.
=> Fix spelling check error in tests

include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
Remove bounds check within iterations in favor of bounds check before the iterations.
=> Balanced path Remove Bounds check

test/support/test_config.h
In this PR we update compiler version in tests
=> Update compiler version in tests

test/general/sycl_iterator/sycl_iterator_for.pass.cpp
In this PR we fix issue https://github.com/uxlfoundation/oneDPL/issues/2184
=> Fix predicate in `test_adjacent_difference`

include/oneapi/dpl/experimental/kt/single_pass_scan.h
The PR fixes a regression since #2198.
=> Fix scan kernel template

include/oneapi/dpl/pstl/ranges/nanorange.hpp
Cherry picking the fix in nanorange for GCC 15 to the release branch.
=> Fix nanorange with gcc 15 (#2234)

include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h, include/oneapi/dpl/pstl/ranges_defs.h
[oneDPL][ranges] usage subrange view instead of take and drop views.
=> [oneDPL][ranges] usage subrange view instead of take and drop views

test/support/utils_device_copyable.h
The PR removes unused parameters.
=> Fix unused-parameter warnings in device copyable test

documentation/library_guide/introduction.rst, documentation/release_notes.rst
This PR cherry picks the release notes on to the release branch.
=> Release notes for 2022.9.0 release. (#2267)

include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h, include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h, include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h, include/oneapi/dpl/pstl/utils.h
[oneDPL][ranges][hetero] usage of functors instead of lambdas
=> [oneDPL][ranges][hetero] usage of functors instead of lambdas

documentation/library_guide/parallel_api/iterators.rst, documentation/library_guide/parallel_api/pass_data_algorithms.rst
From @dmitriy-sobolev, changes to docs for indirectly device accessible.
=> Simplify description and some rewrites

include/oneapi/dpl/pstl/algorithm_ranges_impl.h, include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
Additionally, some clang-format is applied for better readability.
=> Match template and argument order in range for_each pattern

test/support/utils_invoke.h
The previous fix #2393 had issues with where a kernel name could clash between this level and the subsequent call's policy clones.  Since not all calls on this level of the callstack were wrapped, the kernel name could match between this cloned policy and a policy cloned at the next level of the callstack.  
This is a better fix which clones all calls at this level, causing them to be explicitly unique with each other with the same level of name nesting.
This PR also rearranges the order to group together the paired tests which are supposed to check that different value category policy calls don't clash with each other.
The previous fix resolved most issues but a few tests had remaining failures due to this sort of clashing.
=> Real fix for mangled name comma operator deletion
